### ISSUE TITLE
Timeline media page

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#1021]
@Fay It is not possible to add a link to a stand-alone page in a Xerte object. We can not find what is wrong. Can you take a look?
I added a link in the example on the https://xot310beta.dlearning.nl/.

**Comment by FayCross** [comment]
@ingedonke is the project shared with me? I can only see projects that I've made when I login there.

**Comment by ingedonke** [comment]
I shared it now with you :)

**Comment by JohnSmith-LT** [comment]
TimelineJS library seems to be mangling the code because we have href="#" because links with urls work fine. Have added the main text back in after the timeline is loaded so that at least a Xerte Link in the main page text box now works...

To get links within the items to work is going to require changing the library code.
