### ISSUE TITLE
allow use of variables for images and dynamic image location and urls and dynamic url location

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1028]
This has cropped up a few times on the forum and during #Xerte21 and in other conversations particularly regarding images but also urls.

It seems at the moment we don't expose variable values to the image or url fields in the wizard or editor but would be useful if we could.

Re Images there's a discussion and response by John on the forums about a way this could be achieved: https://xerte.org.uk/index.php/en/forum/bugs-and-issues/2018-variable-substitution-issue#6493

However I've been partially working on a project where LOs are being developed in one install but then exported and moved to a different install/domain so there is an issue with embedded and linked XOT urls which will need to be changed. In some cases this is XOT links embedded in Bootstrap and in others XOT embedded in XOT and displayed in a lightbox. The variables can hold those urls but at the moment those variable are not picked up if added to url fields e.g. in bootstrap the link to xot field.

What do we need to change to enable this?
I guess enabling variables in the url fields in the editor via the image and link buttons is more challenging than enabling variables to work in the url and image fields in our wizards but would be good to at least get the wizard method working.

**Comment by FayCross** [comment]
@ronm123 This already works in XOT & Bootstrap when you add images via WYSIWYG editor. It worked originally but had broken in an earlier release and was then fixed last year (https://github.com/thexerteproject/xerteonlinetoolkits/commit/c2dcd80098c726aa5fb8cabb1b3ef6165c1b6cc5) 

It wouldn't be too hard to also get this working for images and other files added via a URL field in the editor too - the variables code includes a list of attributes to check for variables so this can be added to with 'url', 'image' etc. to include all the new attributes you want to search through. The one thing that doesn't work with variables in image URLs though is that they aren't updated if the project includes text fields where students can submit new values for the variables. This is because the update of variables looks for span tags around the variable text - this span obviously can't be added to a part of a src and I'm not sure of the best way of doing this with out those.

**Comment by FayCross** [comment]
@ronm123 I've just made a quick change so that variables will now work in iframe & links added in text editor

**Comment by ronm123** [comment]
@FayCross my immediate 'use case' doesn't require the url values to be updated via student text fields just the ability to edit a list of urls in the variable table for use in a different install rather than having to go through everywhere in a project where those urls need changing. As I was typing this I see you have made a commit so I'll pull that down and see if it works for this 'use case'.

**Comment by FayCross** [comment]
I'll have to do the same change in Bootstrap too - I'll commit that later
