### ISSUE TITLE
Textcorrection page stays blank

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1035]
@FayCross  An existing textcorrection page gives a blank page. The code stumbles on line 133 that seems to be added by you on May 19, 2021. Specificlly it stumbles on $(answer), where answer is a string.

Does that ring any bells?

**Comment by FayCross** [comment]
@torinfo I've just had a look at this and I think it's related to answer in xwd being changed from type="textArea" to type="script". I think this was done to make sure it's just plain text being added (otherwise marking wasn't done reliably). The line it's failing on for you is making sure any line breaks in the text from the script field aren't lost when shown on screen. Not sure why your example won't work though, I've tried changing answer back to a text area and new pages I create work ok. _answer_ is always a string. Can you share it with me?

**Comment by torinfo** [comment]
Yes, sure. I'll place it in xot310beta and share with you so you can export if needed.

**Comment by torinfo** [comment]
@FayCross LO 27 is just the textcorrection page that shows the problem in xot310beta.dlearning.nl. It is shared with you.
Thank you for looking into this. Let me know if you want the zip file.

**Comment by FayCross** [comment]
I think this fixes it.  $(answer) doesn't seem to have been doing anything useful - I think I must have changed lines above this and not taken this out. I've removed it and tested with your example & newly created pages & they seem to work ok.

**Comment by torinfo** [comment]
@FayCross Thank you!
