### ISSUE TITLE
Export project download speed

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1070]
Downloading projects via the export tab in project properties can be very slow and often fails all together if project contains media. I've just had a situation where in order to download a SCORM package of a project I have had to:

1. duplicate the project
2. download an MP4 from the project
3. delete the MP4 via the media browser
4. download the SCORM zip
5. upzip SCORM, add MP4 back in & zip up again

The MP4 and SCORM zip were both quick to download when done separately but when you try to download the zip containing the MP4 it always times out. Can anything be done to improve this?

**Comment by ronm123** [comment]
@FayCross what's the size of the projects that are failing? Is this on your online server or via xampp? I suspect this might be a server configuration issue because although large projects can take some time in my experience they do work and shouldn't time out.

BTW from memory I think there's some fall back code involved if one of the required extensions (probably zip) is not installed/enabled so might be work checking that too. Also memory_limit and script timeoult values etc.

**Comment by torinfo** [comment]
@FayCross Yes, please make sure that the php zip extension is installed (because it uses a much better zip library). If the extension was installed, please let me know the size of the mp4.

**Comment by FayCross** [comment]
@ronm123 @torinfo thanks - I'll look into server settings. It wasn't a huge video
