### ISSUE TITLE
Skip to main content link in Bootstrap

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1072]
It would be useful to have a (hidden until tabbed to) skip to main content link in the Bootstrap template in a similar way to the one we have in XOT template. At moment you have to tab through page links & section links before you can access the main content.

**Comment by ronm123** [comment]
@FayCross I remembered seeing this and I think a recent forum post and agree we should try to get this added in time for the next release. I'll add it to the agenda for the next dev day but will also have a look if I can add it without problems in a similar way that I added it to the XOT template.

**Comment by ronm123** [comment]
@FayCross I've added a partial solution for this and can demo and discuss during the dev day. In the meantime a few notes...
After testing I realised the skip link couldn't simply point to #mainContent because that then always returned to page 1. So I added some script to application.js to change the skiplink on page change and to point to the relevant page[x]section1.
Originally I tried adding the skiplink to the body like in xot but I couldn't get it to display properly so added it to the jumbotron and included sr-only sr-only-focusable to get it to display properly.
However then with a screenreader like nvda running it wasn't finding that link on tab only on shift + tab so I also added a skip link for screen reader only to navbar-inner.
This all seems to work on loading of the project but when tabbing to and using the page navigation and changing page the focus remains on the page link chosen. I don't know if we should force the focus to move back to the top of the page so that next press of tab hits the skip link again and if so how to do that?

**Comment by ronm123** [comment]
@FayCross @torinfo I've reminded myself about where we got to with this and it does all seem to still work ok except my previous question in the last para still applies e.g.
This all seems to work on loading of the project but when tabbing to and using the page navigation and changing page the focus remains on the page link chosen. I don't know if we should force the focus to move back to the top of the page so that next press of tab hits the skip link again and if so how to do that?

So if you try on a multi-page Bootstrap like our demonstrator https://xot.xerte.org.uk/play.php?template_id=137#page1 you'll see that if you tab when it loads you'll get the skip link and if you had a link to go direct to say page 4 interactivity https://xot.xerte.org.uk/play.php?template_id=137#page4 again when you tab you'll get the skip link so all fine at this point. However if you then use the nav bar to go to a different page then the focus remains in the nav bar and if you use an internal page link to go to a different page then the focus remains wherever that link was set to go and not back at the very top. So I'm tempted to close this unless either of you think that when changing page in any way the focus should go back to the top? I'm not sure that would be correct especially when using the nav bar or section links but what about page links?
