### ISSUE TITLE
Workspace folders bug in develop

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1086]
The workspace list of projects no longer shows any folders (so you can't access projects within existing folders). If you try to create a new folder you get an 'error creating folder' message and no folder appears. It looks like the folder is created in database but doesn't show in workspace. Probably one for you @torinfo!

I first saw this in xampp but it's also a problem on https://xot310beta.dlearning.nl/ so likely to be something broken recently in develop (it's ok in 3.10)

**Comment by torinfo** [comment]
@FayCross Is this better? I think it is still broken for import pages.

**Comment by torinfo** [comment]
See https://github.com/thexerteproject/xerteonlinetoolkits/commit/654a43702ff7c9ee487e7f980749011ced03b256

**Comment by FayCross** [comment]
@torinfo yes - that's fixed in Workspace but it doesn't show folders when importing pages in the editor. I do also still see the error creating folder message when creating a folder but the folder does appear anyway

**Comment by torinfo** [comment]
@FayCross Thank you. I'll check the other issues early next week.

**Comment by ronm123** [comment]
@FayCross @torinfo I've only just noticed that this applies to 3.10.5 too? So installations upgraded to 3.10.5 aren't showing folders in the workspace! Or am I using an earlier 3.10.5 and the fix was added later?

**Comment by ronm123** [comment]
@torinfo @FayCross I noticed the other day that my local develop wasn't loading any longer but didn't have time to investigate at the time. I don't know if this is due to these changes in display_library.php and I don't know why you aren't getting the same problem? With debugging on I get a blank screen but with debugging on I get the following error:
Parse error: syntax error, unexpected ':', expecting '{' in \website_code\php\display_library.php on line 365
Any ideas? Why aren't you getting this?

**Comment by ronm123** [comment]
@torinfo is this perhaps a PHP compatibility issue? My local xammp is PHP 5.6.8 and in our release notes we say PHP v5.1.2 or later.

**Comment by torinfo** [comment]
Yep. This function (on line 365) specifies a return type, which is supported, starting PHP 7.0. I would suggest to just remove the 
': bool'.
Can you test and commit, or do you want me to do it.

**Comment by ronm123** [comment]
@torinfo was offline but just got back in and tested and although that removes the error and I now get further with the header and footer loading the left and middle panes of the workspace are completely empty.

**Comment by torinfo** [comment]
@ronm123 Could be caused by other compitibility issues with PHP 5.6. To be honest, would be easiest to drop support for that.

No errors in the PHP log?

**Comment by FayCross** [comment]
@torinfo do we need to add something to release notes ASAP about requiring a higher version of php or are these changes only affecting develop and not released code at the moment?

**Comment by ronm123** [comment]
@FayCross @torinfo I think it's only affecting develop installs at the moment but I agree if we are having to change the minimum compatibility then we need to make that known prominently and not just in the release notes but on the download page and set up screens too. Obviously it's long overdue that we specify and move to a later minimum version of PHP and even 7.0-7.3 are EOL. But I guess we could at least say that PHP 7.0 is the new minimum?

Tom - if I remove ': bool' as I said although that removes the error and I now get further with the header and footer loading the left and middle panes of the workspace are completely empty. I don't get anything useful in the console or the Apache error log although at the end of the apache error log I get The system cannot find the path specified. But nothing telling me what path.

I have local xammp that is PHP 8 but I've deliberately kept the xampp I use by default at 5.6 and until now that has always worked. So is there a solution to this current issue or do we now have to say PHP 7.0 is the minimum and test that to be sure?

**Comment by ronm123** [comment]
@FayCross @torinfo I'm adding this here rather than starting a new issue because I think it might be a related bug... I just noticed that there is something strange when trying to import pages from one Bootstrap project into another and you can see this in develop as well as 3.10.4+ e.g. on our xot.xerte install e.g. I was trying to import pages from a project that exists in a folder but when I select import pages I don't see that project. If I make a copy or move it out of the folder into the workspace then it shows when trying to import pages. In fact on my local develop I don't see any folders in the list when trying to import but on 3.10.4x I see folders and some projects but not all projects in a folder. Again you can see that on xot.xerte

**Comment by torinfo** [comment]
@ronm123 Yes, It's a known issue. I broek this when merging part of the folder sharing functionality intto develop. I am working on a fix. The issue is that content in subfolders is not shown.

**Comment by FayCross** [comment]
I've tested and folders now show in workspace and when importing projects in the editor. The one outstanding issue here is that if you select a folder in the workspace and click duplicate, the folder and all its contents should be duplicated (as mentioned in issue https://github.com/thexerteproject/xerteonlinetoolkits/issues/1093)

**Comment by torinfo** [comment]
As stated in de commit comment:

This never worked properly before.
 1. If the temlates were a mix of Nottingham and site, the current code would
    not have worked.
 2. If One of the templates did not have valid access permissions, none of the
    templates would have been copied
 3. Subfolders were not copied
 [develop](https://github.com/thexerteproject/xerteonlinetoolkits)
