### ISSUE TITLE
Folder properties not working in develop

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1093]
In the workspace, when you select a folder and click 'i' the folder properties don't appear. You instead see the same list of tabs as you would normally see for a project but with an error message at the top.

The workspace folder properties and project properties still work correctly.

This is a bug in develop but not in v3.10

**Comment by ronm123** [comment]
@FayCross I've just tested this with my local xampp develop and in fact if I select a folder and then select properties all I get is an empty grey window. However testing via an online install that is develop I get the same as you e.g. select a folder and select properties but the properties window shows project properties rather than folder properties. I checked on a couple of 3.10.5 installs and thankfully on those folder properties still seems to work correctly.

I'm guessing this is perhaps linked to the folder sharing functionality. e.g. in my local develop as well as online develop all the folders display the shared folders icon. @torinfo I think that was something we discussed previously and you were going to have a look at.

**Comment by torinfo** [comment]
@FayCross, @ronm123 Yes, I need to look into this. This is caused by a merge that only partially succeeded. I'll clean up the mess (hopefully today).

**Comment by torinfo** [comment]
@FayCross I'll have a look at that.

**Comment by FayCross** [comment]
Closing this as the folder properties not showing bug is fixed (I'll move the outstanding bug about duplicating folders over to https://github.com/thexerteproject/xerteonlinetoolkits/issues/1086 as I commented on the wrong issue)
