### ISSUE TITLE
Escape key to remove hover tooltips

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1114]
Allow tooltips that appear on hover or focus via keyboard tabbing to be removed with Esc key. https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

- [x] Glossary hover tooltips
- [x] Hotspot tooltips in 360 image page

There might be other places where a tooltip is used too?

**Comment by JohnSmith-LT** [comment]
Is that the kind of thing that you were thinking? I tried adding keydown event handler (with a check for escape) like all the other events and it works for tabbing but with mouseover the event wasn't getting to the handler - so I now add/remove it from the document.body every time the popup opens/closes.

**Comment by JohnSmith-LT** [comment]
I think I've done both now @FayCross

**Comment by JohnSmith-LT** [comment]
So I had to change this @FayCross to remove the handler in the "mouseleave" event rather than in the event handler because what was happening was that if you hovered and left then the handler remained attached until later down the line when you pressed escape and that could interfere with other functionality (like full screen video or similar) I suppose...

Seems to work ok in both pages now but I notice in the 360 page that there are a lot of event handlers being added and then removed inside the handler - you may be able to reproduce similar undesirable cases with those too where a handler remains long after it was desired because if it's not used then it never removes itself...
