### ISSUE TITLE
allow for theme logos to be logo.svg rather than just logo.png

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#1120]
I'm working on new themes for xot and bootstrap where ideally a theme logo should be included that is .svg rather than .png. I can probably get around this by adding script to the theme's .js files but it seems to me it would be useful to change our existing code in xenith and application.js to look for logo.x regardless of file extension. Perhaps even logo.jpg, logo.gif, logo.heif, logo.heic, logo.webp, logo.avif too?  What's the best way to do this?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123, there are many ways to do this... probably the simplest (which uses the built in dependency loader) is something like this:
```
var logos = ['svg',  'png', 'jpg', 'gif', 'heif', 'heic', 'webp', 'avif'].map(function(ext) {return 'logo.'+ext;});
loadjs.path('img!' + FileLocation  + 'media/');
loadjs(logos, {
    before: function (path, el) {
      	let div = $('div#logoHere');
        if (div.find('img').length < 1) div.append(el);
        return false;
    },
    async: false // Fetch files in parallel but load in series
});
```
It's probably the shortest I can think of off the top of my head but not so efficient if you have several logo.*** in your folder since it will attempt to load them all in parallel and then will go through them in the order specified and insert the first one it finds...

I know we discussed IE support going forward but the modern, recommended 2022 method would probably be to use some routine using fetch()...

You could also do something similar using jQuery:
```
var logos = ['svg',  'png', 'jpg', 'gif', 'heif', 'heic', 'webp', 'avif'].map(function(ext) {return 'logo.'+ext;});
logos.forEach(function(logo) {
    (function(logo, url) {
        $.ajax({
            type: "HEAD",
            async: true,
            url: url,
        }).done(function(message,text,jqXHR){
            let div = $('div#logoHere');
            if (div.find('img').length < 1) {
              div.append(
                  $('img').attr('src', url).show()
              );
            }
        });
    })(logo, FileLocation  + 'media/' + logo);
});
```

**Comment by ronm123** [comment]
@JohnSmith-LT thanks John but I probably should have explained more clearly and included a snippet of our existing code from xenith and application.js. 

When I think about it further there are a few reasons why we should change the existing code and this is about the default logos not the author options per project. The following is my understanding of the current situation but I could be wrong!

1. I think it's more common for logos to be .svg rather than .png now (or at least sometimes) but our default logo code doesn't currently allow for this.
2. With both XOT and Bootstrap server errors are currently generated every time a project is played or previewed if the install doesn't have a default .png logo in /modules/xerte/parent_templates/Nottingham/common_html5/logo.png or /modules/site/parent_templates/site/common/img/logo_left.png and the trouble is many installs do not have or require a default logo.
3. If a default logo is in place either in the default locations or the selected theme folder then they are loaded automatically unless an author has added a logo via optional properties. We don't currently have an option for the author to hide the default logo in XOT projects but we do in Bootstrap.

Personally I think we have the following objectives here:

- [ ] Enable at least .png, .svg, .jpg and .gif as default/alternative formats for default logos and theme based logos.
- [ ] Prevent the current server error logs if a default logo is not in place in the two default locations.
- [ ] Add an option to XOT template for an author to hide the default logo whether loaded from the parent template location or the selected theme..

I'll add this to the agenda for our meeting on Friday afternoon but if you @JohnSmith-LT @FayCross or @torinfo have further thoughts please add those here.

**Comment by JohnSmith-LT** [comment]
This maybe is better than the two above as it waits for one to either download or send back 404 before displaying or moving on to try next. This way you get the least 404 errors but still not perfect and perhaps still not even what you want...

var logos = ['svg',  'png', 'jpg', 'gif', 'heif', 'heic', 'webp', 'avif'].map(function(ext) {return 'logo.'+ext;});
(function (path) {
    function tryNext(i) {
        $.ajax({
            type: "HEAD",
            async: true,
            url: path + logos[i],
        })
        .done(function(message,text,jqXHR){
            let div = $('div#logoHere');
            if (div.find('img').length < 1) {
                div.append(
                    $('img').attr('src', path + logos[i]).show()
                );
            }
        })
        .error(function(){
            tryNext(++i);
        });
    }
    tryNext(0);
})(FileLocation  + 'media/');

**Comment by FayCross** [comment]
@ronm123 @JohnSmith-LT - Should we add a logo field to the database? So, use the logo specified in the database and if it's not in there then fall back to try all the types of logo.xxx. This would help minimise 404s

**Comment by JohnSmith-LT** [comment]
I suppose I never thought of the server route of doing this...

We already put a placeholder in the play/preview file which is then replaced on-the-fly when the file is loaded off the server. When export is called it permanently replaces the marker with code to load the file...

So in our case we can just put %LOGO% where we want it in the rloObject.htm file and then, after checking which, if any, logo files exist, we can write out the <img> tag. Similarly in export we can write the tag and include the relevant logo file in the zip...

**Comment by ronm123** [comment]
@JohnSmith-LT @FayCross I think either the database or %LOGO% option would work. I guess the considerations would be:

database - perhaps better long term but possibly requires a change by site owners if they currently use the default location option.
%LOGO% - perhaps better as a quick way of enabling different logo formats without requiring intervention.

Either way we should add an option to hide the default logo in XOT like we do in Bootstrap.

**Comment by JohnSmith-LT** [comment]
Haven't done any PHP for a while so thought i'd attempt to at least get rid of those 404 errors...

The code I've committed adds a %LOGO% placeholder and then checks for logo.svg, logo.png, logo.jpg and logo.gif in the common_html5 folder and the first one it finds it loads, otherwise it clears the placeholder...

Not sure that does what you want in terms of different logos for different themes but at least it stops the 404 errors for now, in XOT at least. Still need to most likely add some code to do the same in export as well as including the correct logo file...

**Comment by ronm123** [comment]
@JohnSmith-LT just quickly tested and can see that removes the 404 errors from play and preview of XOT projects. It's always been a bit embarrassing when liaising with different people from different IT teams and looking at Apache error logs to have to say don't worry about those logo errors!

So yes it would be good to add the same functionality to remove the same 404 errors with Bootstrap and I know there are at least 2 if not 3 places where the placeholder has to be cleared or replaced for export and I think LTI and xAPI players too.

As you say this doesn't resolve the need to be able to use different formats in themes or the ability to hide the default or theme  logo in XOT projects but lets discuss all that tomorrow. Actually I can probably add the XOT author option to hide the default logo before the meeting tomorrow.

**Comment by ronm123** [comment]
@JohnSmith-LT at the moment I think the logic is as follows:
both XOT and Bootstrap automatically load logos if found in the default module locations e.g.
/modules/xerte/parent_templates/Nottingham/common_html5/logo.png /modules/site/parent_templates/site/common/img/logo_left.png
You've now resolved that bit for the XOT template apart from wherever else that needs to be replicated for export and LTI/xAPI etc but @torinfo can advise on those extra places.
The current code in xenith and application.js checks if there is a logo.png (but only png) in the selected theme and if there is automatically adds that and as a priority over the default logo.
Then if an author adds their own logo to an LO that takes priority over default and theme based logos.
In Bootstrap the author has options to hide the default left and or right logos and I'm about to add a similar option to XOT.

The relevant bit of code in xenith is:
`var type, fallback;
		if (x_params.ic != undefined && x_params.ic != '') {
			$('#x_headerBlock img.x_icon').attr('src', x_evalURL(x_params.ic));
			type = 'LO';
			fallback = x_params.theme != undefined && x_params.theme != "default" ? 'theme' : 'default';
		} else if (x_params.theme != undefined && x_params.theme != "default") {
			type = 'theme';
			$('#x_headerBlock img.x_icon').attr('src', x_themePath + x_params.theme + "/logo.png");
		}
		checkExists(type, fallback);`

and it's that bit where type=theme where I was initially looking to load logo.svg rather than logo.png and reminded me that it would be better to make this possible across the board rather than just in a particular theme.

**Comment by ronm123** [comment]
@JohnSmith-LT @FayCross I've added and committed the optional property to hide the logo in xot but added the following comment:
add option to hide rather than replace automatic logo on xot template. Note: this is just the option to hide with tooltip etc. The code in Xenith still needs to be modified to hide the default logos. Not sure if that should be done by adding && x_params.icHide != 'true' in the relevant conditions, or just to a new condition at the end of the existing code to hide whatever logo has been loaded if the option to hide is checked.

I had a look at adding && x_params.icHide != 'true' to the various if statements but there seem to be so many I'm not sure that's the right way to do it. Although I guess there's a potential for a 'flash' if the logos load and then just get hidden at the end. What's the best place to check and add this?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 last question hopefully...

Do any of the XOT themes actually have a default logo.png that I can see loading? If not then where do they go? I tried putting one in the futureteacher theme folder and it didn't load by default - do I need to do something else to make it load or is it in the wrong place?

**Comment by ronm123** [comment]
@JohnSmith-LT it should just be the presence of a logo.png in the root of a theme. But it looks like something has broken this because now even a logo added to a project doesn't seem to be showing? None of the bundled themes have a logo but I have a few custom themes with logos and now they aren't showing the logo either! :-(

I checked my optional property commit in case I had made a mistake and committed changes to xenith but I don't think I have. I did add trigger conditions to the optional properties so that if the checkbox to hide was checked then the option to upload a logo and add alt text doesn't show but I don't think that's the cause.

**Comment by ronm123** [comment]
@JohnSmith-LT @FayCross as far as I can see the last change to xenith.js was 5 days ago so unless I'm wrong about that it must be a change elsewhere that has stopped the logos from working and that change must have been today because I've had logos displaying this morning.

**Comment by JohnSmith-LT** [comment]
Oh.. for goodness sake it will probably be my changes! D'oh... If the logo doesn't exist in common_html5  them I don't put the <img> in the page so it can't then be updated by code... let me try that...

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 I've worked on the XOT logic for this just now and in my testing (and from what you've described) it seems to work for me:

- If you choose a valid log in the LO then it uses that
- Else it looks for a 'logo' with one of the 4 extensions ['svg',  'png', 'jpg', 'gif'] in the theme folder
- Else it looks for a 'logo' with one of the 4 extensions ['svg',  'png', 'jpg', 'gif'] in the default location (common_html5)

If you hide the icon then the logic above still follows but the icon is left hidden - not sure if this is ideal but allows showing the icon later by code or on some pages??

I've commented out all that logic in xenith.js that attempted to check asynchronously for logo existence as that was what was generating all the 404 errors...

If this is all good then I will port the logic over to Bootstrap and then think about the export/xAPI situation. @torinfo feel free to comment if you think any of this will cause you issue.

**Comment by ronm123** [comment]
@JohnSmith-LT just tested and at first I thought "something wrong - it's not working" :-( but then I realised that I'd only read your post but not yet pulled down the changes! ;-)

Tested with logo.png and logo.svg in the theme - works well and loads the svg as the priority.
Tested adding a logo via the optional property - works fine again.
Tested using the hide optional property - works fine.
Tested with logo.png and logo.svg in the modules folder - works well and loads the svg as the priority.

So all works fine. As far as I can see there's just one small issue when using an oversized svg but that's nothing to do with your changes and there's an easy solution that we can discuss during the meeting later.

**Comment by JohnSmith-LT** [comment]
Hi @ronm123  I've now committed the code to do the same logo thing for Bootstrap and it seems to be working fine for me for all 3x scenarios. Only issue is that for some reason making the < img> dynamic broke the CSS so i've updated that in custom.css here (https://github.com/thexerteproject/xerteonlinetoolkits/commit/fd7f0f52d2f6f5d6add000a5151ecf6dd124b43c#diff-c1c06bab11ea58ef851e71a02ab7853846947c298f1dccaf8de2620c4e30307b) but for some reason it's not filtering through to the themes... if you get a chance to test this and can figure that part out then please make any relevant changes to the scss files for the themes.

I still need to do the export but have identified all the points that I need to work on and nearly have that all working too...

Just one question:

If you add a logo in the LO  it takes priority and loads but if you then change the URL by adding a X for example so that it no longer is valid then the theme logo will load or the default logo will load... Question, if the LO url is populated then should we use that without checking for existence of a file because I can see that leading to issues where the wrong logo is being shown because the url is wrong but the end user cannot debug easily...

**Comment by JohnSmith-LT** [comment]
By "broke the CSS" I mean that the left logo should be on the left and the right on the right but just now they stack on top of each other because (if you right click inspect on a logo) the containing div expands to full width. I had it working at one point by changing the custom.css to div.logoL here

#overview div.logoR .logoR {
  float:right; 
  margin-top:20px;
}

but now that doesn't seem to get applied to the themes so they always stack on top - in fact now I check all 3x scenarios stack and that rule isn't being applied...

The broken placeholders showing is an easy fix (although I thought that I had?!?) - I'll take another look at that and fix the defaulting when a wrong url is added "feature"

**Comment by ronm123** [comment]
@JohnSmith-LT @FayCross I just tested on a 3.10 install with a logo.png and logo_left.png in the blue and grey bootstrap theme.
logo.png loads on the right and logo_left.png loads on the left.
If I just have logo.png in the folder then just that logo shows aligned right and no console errors about not finding a logo.
If I have neither then I get console errors that the files cannot be found in the theme folder.
I have both files in \modules\site\parent_templates\site\common\img\ but neither load.
So all of the above is with 3.10 so somewhat irrelevant but some of that is working whereas develop isn't fully working either.

In Develop if I add logo.png and logo_left.png to the modules folder I get both logos in the bootstrap but aligned centre one above the other. If I remove or rename those in modules but have both in the bluegrey theme then again both appear in the project but aligned centre one above the other. If I rename or remove logo_left.png then I get just logo.png appearing but aligned top middle not aligned right.

So there's clear differences between what happened in 3.10 and what we have now in develop particularly with logo alignment.

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 

I've fixed the defaulting issue - if you put a wrong URL in now you get a missing image icon

I've also fixed the left/right logo issue (I think)

I've also added a max-height: 200px to the XOT image and that seems to stop the SVG filling the screen - not sure if 200px is the right value though and needs done in Bootstrap too...

**Comment by JohnSmith-LT** [comment]
Morning @ronm123 

Yes it's most likely something to do with the specificity but that's what I was meaning by "broke the css" earlier - if left the < img> tag in the rlo.htm file and let xenith change it then it behaves different from changing the < img> tag in the PHP file and I couldn't figure out the issue...

There is something not quite right with custom.css rules though which may now be having some effect... some of the rules for the header are:
```
#overview .logoR {
  float:right; 
  margin-top:20px;
}
#overview.logoR .titles {
 float:left;
 padding:20px 5px;
 text-align:left;
}
#overview .logoL {
  float:left; 
  margin-top:20px;
}
#overview.logoL .titles {
 float:left;
 padding:20px 5px 20px 20px;
 text-align:left;
}
#overview.logoL.logoR .titles {
 float:none;
 padding:20px 5px;
 text-align:center;
```
But they make no sense and might just not be working the way they were intended - #overview.logoL.logoR .titles for example will only match an element that has id="overview" AND ALSO has both logoL and logoR classes attached to it... As far as i'm aware that never happens and some of the other rules are strange like that...

It seems that that rule above may have been intended to be something like:

`#overview .logoL, #overview .logoR, #overview .titles {`

since we have the structure DIV(id=overview -> DIV(class=logoL) and not what that selector seems to be expecting...

**Comment by ronm123** [comment]
@JohnSmith-LT @FayCross that's interesting ignore those hash links! I use that in email quite a lot to prevent automatic bulleting and indenting but here the hash + number seems to be picking up links to issues! :-(

**Comment by JohnSmith-LT** [comment]
I don't think it's a big deal to fix the CSS to make it work as it did before, just pointing out that it's probably why you are not seeing any difference in the code - the browser just seems to be reacting to the current, strange css in a non-predictable way... not even sure why it was working in the first place since many of those rules are not even applying...

So just to be clear @ronm123, you are now happy that the functionality of the new code is working as you imagined it  and we just need to fix the presentation so that it behaves the same as in 3.10 or is there anything (other than presentation) that is still needing fixed?

I'll take a look at the css when I get a chance (tonight possibly) as I'm conscious I still need to fix the recorder (almost done though) and implement the export and TWITTERCARD stuff too...

**Comment by ronm123** [comment]
@JohnSmith-LT yes sorry John I think it's all working fine (I think) apart from the presentation. I've been busy with other things and noticed that I need to fix an issue with the new alternatiing section code in Bootstrap because it seems to be part of a condition related to the back to top button options and should be completely different. I'll fix that and also try to look at the logo display because I have a meeting this afternoon where ideally I need the logo and titles to be correctly displayed.

**Comment by ronm123** [comment]
BTW @JohnSmith-LT I noticed a whole load of logo related code commented out in application.js from line 950-1018 - I take it that's because you've commented that out but left it in for now in case needed for reference etc?

Those start/end numbers might obviously change but its the whole section that I guess @FayCross wrote with comments about the different logo options.

**Comment by JohnSmith-LT** [comment]
Yes @ronm123 there is code commented out in both application.js and xenith.js that can be removed - I just left it there for quick reference to make sure that I had included all the setting of alt property, hiding the logo if relevant, adding 'themeClass' etc...

It's been added to the checklist at the top of this post - pretty sure though that all the commented out stuff can now be removed and the only issues are directly because of the custom.css file...

**Comment by ronm123** [comment]
@JohnSmith-LT I mentioned that for a meeting I have this afternoon that ideally I need the theme logo to be displayed correctly. In this case a default logo.svg loaded from the theme and where the logo should appear on the right and the two titles aligned left. I've got that work by adding the following to the theme:
`#pageTitle, #pageSubTitle {
  text-align: left;
}`
However that's not correct but at least it gives me the presentation I need for this afternoon. 
Another difference with 3.10 is that at the moment if you resize the browser window to a narrow tall window or use the browser emulation the logo remains floated to the right whereas in 3.10 the logo and titles become centre aligned with the logo above the titles.

**Comment by JohnSmith-LT** [comment]
Yeah the css rules are screwed up for smaller screens too:
```
/* --TABLETS TO DESKTOPS-------------------------------------------------------------- */
@media (min-width: 768px) and (max-width: 980px) {
  body {
    padding-top: 0;
  }
  .jumbotron {
   margin-top: -20px; /* Offset bottom margin on .navbar */
  }
  /* Adjust sidenav width */
  .bs-docs-sidenav {
    width: 166px;
    margin-top: 20px;
  }
  .bs-docs-sidenav.affix {
    top: 0;
  }
  **#overview.logoR .titles, #overview.logoL .titles {**
    text-align: center;
	float:right;
	width: 100%;
  }
  **#overview.logoR .logoR, #overview.logoL .logoL {**
    text-align:center;
    float:none;
  }
}
/* --TABLETS-------------------------------------------------------------- */
@media (max-width: 767px) {
  body {
    padding-top: 0;
  }
  .jumbotron {
   /* padding: 40px 20px;*/
    margin-top:   -20px; /* Offset bottom margin on .navbar */
    margin-right: -20px;
    margin-left:  -20px;
  }
  
  .bs-docs-sidenav {
    width: auto;
    margin-bottom: 20px;
  }
  .bs-docs-sidenav.affix {
    position: static;
    width: auto;
    top: 0;
  }
  **#overview.logoR .titles, #overview.logoL .titles {**
    text-align: center;
	float:right;
	width: 100%;
  }
  **#overview.logoR .logoR, #overview.logoL .logoL {**
    text-align:center;
    float:none;
  }
}
```

Not sure why or how these ever worked...

**Comment by JohnSmith-LT** [comment]
Yeah I'm definitely happy if @FayCross looks at it ;-)

I thought for a second that there may be code in application.js that adds a logoL or logoR class to the #overview dive but that doesn't seem to be the case either so I'm not really sure - most likely i'm missing something obvious but since the actual html isn't changing then i'm not really sure either why the styles aren't being applied the same as they were before...

It's all a mystery...

**Comment by FayCross** [comment]
@ronm123 @JohnSmith-LT I'm looking at this but am also confused. I admit my initial css looks odd but it obviously worked! ;)

**Comment by JohnSmith-LT** [comment]
That's what I find strangest @FayCross - how has it been working across all browsers without issue for 6 years?!?

Also, when the < img> tag is hardcoded then it works but when exactly the same text is inserted via the PHP file (so it is in the html exactly the same when the page loads) it doesn't work... I was even thinking that it must be whitespace that is affecting it but could not find any difference at all...

**Comment by JohnSmith-LT** [comment]
Perfect, thanks @FayCross

**Comment by FayCross** [comment]
@JohnSmith-LT I'm still really confused though as I don't think any of the BS optional properties to override the default logo work. I don't think this is something I've done though. Do they work for you? Did they before?

**Comment by JohnSmith-LT** [comment]
Which ones don't work for you @FayCross ?

I've just tested again and the following seems to work:

- If you enter a url for (or browse to) a logo (right or left) then it shows that logo with priority
- If either url is broken then it shows the broken image placeholder to suggest that there is an issue with the url
- If either logo url is empty then it looks within the theme folder
- If there are no logos found in theme then it looks in common/img folder

for the theme and common/img folder it looks at [png, svg, jpg, gif] extensions in that order 

You can hide either or both logos by ticking the relevant

That still all seems to work for me...

**Comment by ronm123** [comment]
@FayCross @JohnSmith-LT Fay could it be caching? Just been quickly testing and like John all works for me too. Including the logo(s) moving to top centre when viewed via mobile emulation or by reducing the window width. That wasn't happening before the latest changes. Seems like we're there! :-)

**Comment by FayCross** [comment]
@ronm123 @JohnSmith-LT this has driven me mad but it's not working in the project I was testing in as targetFolder="site" was missing from xml. This is a copy of the UoN Bootstrap example project so probably is quite old but could do with still working. I can see that it works ok for newer projects

**Comment by JohnSmith-LT** [comment]
Sorry @FayCross , i'm using that here https://github.com/thexerteproject/xerteonlinetoolkits/blob/fd7f0f52d2f6f5d6add000a5151ecf6dd124b43c/website_code/php/xmlInspector.php#L233-L243 to determine if it's bootstrap or xot...

Need to find a different way then...

**Comment by JohnSmith-LT** [comment]
@FayCross are you able to share the oldest project you can of bootstrap - we will most likely need to make an educated guess at whether it is xot or bootstrap using the top node properties...

We actually had to do something similar to make sure that we could import old projects because in a similar way the importer could not tell if it was a bootstrap or xot zip file - that code is there and seems to work but I just want to make sure it still works in this situation....

**Comment by JohnSmith-LT** [comment]
In fact @FayCross I suppose the easiest question to answer may be: Were logoL and logoR present right from the start? If so I can just use the presence of them (and the related logoLHide, logoRHide) - they will only be present in Bootstrap...

I suppose it also raises the question - do I need to do work to get the Decision Tree template working too or have I broken it's logo handling...

**Comment by FayCross** [comment]
@JohnSmith-LT the option to have a logo (right & left) wasn't there from the beginning but the optional properties have always been called that (https://github.com/thexerteproject/xerteonlinetoolkits/commit/20b2b2b3b07b1c440cf8f38b31087a13459c934b) 

I'll email you the example project and check decision tree too
