### ISSUE TITLE
Add codesnippet plugin to ckeditor

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#1121]
I thin kit would be a good idea to add the codesnippet plugin into the ckeditor toolbar.

See https://ckeditor.com/docs/ckeditor4/latest/features/codesnippet.html

**Comment by ronm123** [comment]
@torinfo I think at least some users would like that too.

While we're talking about editor plugins and/or changes did you see my question in https://github.com/thexerteproject/xerteonlinetoolkits/issues/966 about whether there is a suitable solution for columns/grids etc?

Also looking at the features list I think we should also include the following:

Accessibility checker
https://ckeditor.com/docs/ckeditor4/latest/features/accessibility_checker.html
and
Find and replace
https://ckeditor.com/docs/ckeditor4/latest/features/findreplace.html

I was surprised to discover we already have the keyboard shortcuts e.g.
https://ckeditor.com/docs/ckeditor4/latest/features/shortcuts.html but what I had wondered about was whether ther wer any keyboard shortcuts we could use in our styles and scripts text boxes e.g. select a block of css and use something like Ctrl + Shift  + / to comment all of that selected code out rather than having to manually type /* and */ etc?

**Comment by FayCross** [comment]
@ronm123 I've added these two plugins and they seem to work well. I'll close this - not sure if any work needs doing for the shortcuts thing you mention above but maybe open a new issue if there is

**Comment by ronm123** [comment]
Thanks @FayCross just been testing these and they are both great! At first I was underwhelmed by the accessibility plugin! :-( but I hadn't paid enough attention to what it does and doesn't cover. e.g. In my test I changed the word Xerte to be black text on a dark red background and the word Toolkit to be light grey on white and then clicked the button and got the following:
![image](https://user-images.githubusercontent.com/5167146/176658101-96b11294-8f51-4bac-9f87-19a09f0557ce.png)

However it clearly doesn't check for colour issues but does check many others some of which are really helpful and may not be apparent to users. We just need to explain some of this in the release notes e.g. doesn't check for colours and contrast etc and also put a tip about using '' as Alt text for purely decorative images because otherwise the checker says Alt Text cannot be empty. Do you plan to add this to the release notes or shall I?

Some examples where it works well...
![image](https://user-images.githubusercontent.com/5167146/176658766-91a1f483-0e31-4d95-ac86-39d28ca3b586.png)

![image](https://user-images.githubusercontent.com/5167146/176658807-c1bbd710-b0e6-4bff-88eb-14dba853c2ba.png)

**Comment by ronm123** [comment]
@faycross BTW not for this release but we should investigate what has been used for the xhibitapp colour checker and see if we can add that too e.g.
![image](https://user-images.githubusercontent.com/5167146/176659498-81689c4b-ec59-40f2-b04e-2926938057d4.png)

**Comment by FayCross** [comment]
@ronm123 yes, I was the same with the accessibility checker initially too (I tested it ages ago and have been meaning to add it for months). I like the way that if you have missing alt text you can enter it directly in the popup warning and it adds this to the image for you. I thought it did check contrast but perhaps that's something I didn't check.

I can add to release notes later

**Comment by FayCross** [comment]
@ronm123 you're right - it doesn't check contrast. That's seems like an obvious thing that's missed out! I get this message when it finds an image with no alt text though, is this different for you?:
_Use empty alternative text only for decorative images
Empty alternative text can only be used if the image serves purely decoration purposes. If the image is supposed to convey any information whatsoever, you need to set a proper alternative text for it._

**Comment by ronm123** [comment]
@FayCross I get the same prompt but it doesn't say how you can set it as just decorative by adding ''
If you ignore it then that's fine but it will prompt if you check again.
If you click quick fix without adding anything its displays the alert saying Alternative text can not be empty
If you know about adding '' it accepts that and doesn't prompt again when you next check. So we probably just need to add that guidance to the release notes. There's an argument to say we shouldn't mention that but I suspect what some users will then do is add anything or poorly worded alt text just to escape the warning and as you know that's much worse than '' if the image is purely decorative.
If you do add '' then it doesn't prompt again and if you double click the image itself it shows the alt text box as empt but in source view it has alt="''"

**Comment by torinfo** [comment]
@ronm123 @FayCross About the codesnippet plugin:

When you use code snippet for code like <b>Test</b> it produces the following html:

```
<pre>
<code class="language-html">&lt;b&gt;Test&lt;/b&gt;
</code>
</pre>
```

That code is stored OK in the editor. When navigating away and then back again the code is still the same.

It is then added to a textarea with jquery:

First the fragment is chenged to a jequery object:

```
$textarea = $(textarea);
```

Then added to html, which is then converted to a ckeditor:

```
html = $('<div>')
	.attr('style', 'width:100%')
	.append($textarea);
```

The code is already modified in the first step:
```
&lt;pre&gt;
&lt;code class="language-html"&gt;&lt;b&gt;Test&lt;/b&gt;
&lt;/code&gt;
&lt;/pre&gt;
```

When this is loaded into ckeditor, all \&lt; and \&gt; are converted to < and >, including the ones of &lt;b&gt;...

Don't know how to prevent this at the moment!

**Comment by torinfo** [comment]
@ronm123 @FayCross Fixed :-)

That was easier than I thought. There was already code to treat content with the &lt;testarea&gt; in it differently (it put the valu in a data attribute and than after initiating ckeditor used the setValue of the editor to set the content. Than it works as expected!

**Comment by FayCross** [comment]
@torinfo great - this works now! thanks

**Comment by FayCross** [comment]
@torinfo I guess so - I've added a block to the release notes https://xot.xerte.org.uk/preview.php?template_id=81#v3.11section8 (code snippet tab) and it's not formatted correctly

**Comment by FayCross** [comment]
@torinfo it's because it's on a tab that's not initially visible I guess? I've just tried on a text page in the XOT template and it works

**Comment by torinfo** [comment]
Ok, I'll have a look. Should be fairly simple to fix.

**Comment by torinfo** [comment]
@FayCross It was not implemented properly in bootstrap.

Did that just now, and redeployed on xot.xerte.org.uk

The indentation is not correct in the source. It will NOT do autoformatting. I tried fixing the indentation on a copy and that works fine, but Ron is working on the Release notes, so cannot fix it.

**Comment by FayCross** [comment]
@torinfo it was indented correctly when I pasted in the code but then it did that thing when it changes if you move away and back to the page in the editor.
