### ISSUE TITLE
New customise button icon options

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1138]
I've just added some new options to allow you to customise the icons used for XOT interface buttons. Although this works for themes where the buttons aren't already font awesome icons, some tweaks of button colour and positioning are needed on the following themes:

- [x] Xerte Online Toolkits
- [x] Dark: Grey
- [x] Flat: Blue
- [x] Flat: Orange & Purple
- [x] Flat: Red
- [x] Flat: White
- [x] Informal: Sketch
- [x] Modern: Django
- [x] Simple: Black & White
- [x] Xhibit: Base Theme

Also, the following things need doing:

- [x] change wording of 'Title' fields that contain the tooltip for the buttons
- [x] add tooltips to the new optional properties / property groups to better describe what they do
- [x] add a new optional property to convert button images to FA icons (this should only appear when one of the older themes above is selected)

**Comment by ronm123** [comment]
@FayCross I had a quick look at this yesterday and I wonder if we should add a new option to 'Covert old theme to FA Icons'?
e.g. I don't think we should just change those themes but we could give users the option to change the selected theme to FA icons and then trigger the code that I think you originally added to hide the image buttons and change to FA icons. At the moment the new option to change icons with the image based themes doesn't really work unless you add every optional property to change them all? I'm surprised Xhibit: Base Theme' is an issue though - are there different issues with some/each of these themes?

**Comment by ronm123** [comment]
@FayCross also one of the theme related issues I was going to have a look at was the issue reported on the forums about not being able to use the new option to change the header colour on the Simple: Black & White theme https://www.xerte.org.uk/index.php/en/forum/bugs-and-issues/2901-can-t-change-header-background-colour-in-simple-black-white-theme#8207

I think that's because we have the gradient styles from the default theme  in some of those themes which isn't be replaces by background:xyz;
So while looking at that I'm happy to go through and also look at the FA icon styles in the themes you've mentioned but I think we should first add the option I've mentioned above to convert all the icons to FA and then they can be changed with the individual options. What do you think?

**Comment by ronm123** [comment]
@FayCross Sorry I forgot and meant to add - I think where you've enabled the changing of the tooltips for individual icons the label of that text field should perhaps be Tooltip rather than Title or have a tooltip icon explaining what Title means?

**Comment by FayCross** [comment]
@ronm123 I don't mind fixing the themes I've listed above, unless you find it's really quick to do when you are looking at the other issue. The buttons that are changed have a class added (customIconBtn) so the CSS just needs to target that. I think the Xhibit theme icons were just spaced out a bit strangely when I changed the icons (possibly because of the icon size?) but none of these theme changes should be hard.

Good point about giving the option to convert all icons at once on the themes that didn't originally used FA. I initially had all the button icons grouped together in one optional property group but decided to split them out to separate optional property groups in the end for various reasons. I could add a checkbox optional property 'convert button images to icons' that's only shown for the older themes and this would change all buttons to a default FA set. You could then check that box initially and then tweak individual icons using the new properties I've added if needed.

I also agree about the label for the 'Title' field not being right and adding tooltips. I was going to change them to Tooltip but some (TOC & glossary) are also used as title of dialog that opens so I wasn't sure that was right either. This is the first part of a much bigger piece of work I'm doing and I just wanted to get this committed even though it's not 100% perfect before I start on some other bits that are more time consuming and have the ability to break more stuff! I'll edit the 1st post above and add some more things to the to do list. Feel free to add more if you think of any. Thanks

**Comment by ronm123** [comment]
@FayCross turns out the fix for optional header colours in some themes was easier than I anticipated and didn't require changing each of those themes apart from flat white which had a white background set on the titles too. So I've dealt with that issue now and don't need to edit the other themes. If you are able to add that convert option I think that would be good because then we can also ensure there are suitable default, active and hover colours too for those themes.

I noticed the wcag logo and accessibility group changes and the ability to hide the icon and TBH I was surprised you added that option. I know it's been asked for on the forums on the odd occasion but I always have to wonder why e.g.
If to just hide the icon rather than prevent the functionality then the hide footer tools by default does that.
If it's because they didn't like the look of that icon then you've now added options to change that.
If to prevent the switching of theme because of branding etc (most likely the reason) then do they realise the implications of that and in any case there are so many other ways that a user could change the colours it's not a replicable way to prevent any change anyway.
Hiding the icon/button also prevent users from following the link to our accessibility guidance and I doubt most of those hiding the icon will be providing their own guidance/support.
But anyway it's there as an option now so lets leave it but yes perhaps strengthen the message and I wonder if the hide option should be at the bottom of the group rather than at the top?

While we're discussing al of this I wonder about the way all the groups look now especially at LO level with lots of optional properties added it can be difficult to spot where one group ends and the other begins. I wonder about making the top and bottom border stronger/thicker or perhaps alternating the background shading of each group. Or perhaps a collapse all/expand all toggle? Just thinking out loud really but might be worth doing something because it's now quite common to have lots of optional properties added. What do you think?

**Comment by FayCross** [comment]
@ronm123 probably worth opening a new issue for the group appearance issue. I agree it's cluttered now. I had wondered about whether optional property groups should be collapsed by default, except for when you add a new one when it should appear expanded initially. It's probably something we need to try a few things and see what works best

**Comment by ronm123** [comment]
@FayCross just to add...
Same issue in the accessibility group with the Title label should either be changed to 'Tooltip' or 'Button Tooltip' of adding a help tooltip after 'Title'.
I can see why the hide option is at the top and set as a conditional trigger but I'd still rather it be at the bottom so it's less emphasised that is an option. e.g. all the other options are arguably pro-active with consideration of accessibility in mind whereas hiding the button is the exact opposite.

Agree lets start a separate issue re optional group appearance and discuss then explore a few options. Perhaps give u a clue in that what you bigger project is too? ;-)

**Comment by ronm123** [comment]
@FayCross just testing via the browser inspector and even something like the following helps I think:
`fieldset.wizardgroup.wizardoptional {
    border-top: #b9b8b8 solid 2px;
    border-bottom: #b9b8b8 solid 2px;
}`

**Comment by ronm123** [comment]
@FayCross just tested this by adding those top and bottom border styles to the fieldset.wizardgroup e.g. around line 737
`fieldset.wizardgroup {
	border: 1px solid #ccc;
	margin-top: 10px;
	border-top: #ffffff solid 2px;
	border-bottom: #b9b8b8 solid 2px;
}`

Worth committing that for now?

**Comment by ronm123** [comment]
Looks like this:
![image](https://user-images.githubusercontent.com/5167146/179218678-d0517f78-c8ed-44ba-9fe2-cca9cae47897.png)

**Comment by ronm123** [comment]
easily removed so I have committed this for now - see what you think?

**Comment by FayCross** [comment]
@ronm123 looks good from your screenshot

**Comment by FayCross** [comment]
@ronm123 I've just committed some changes to xwd that introduce a new 'update theme icons' check box when one of the themes that use image buttons are selected. **I haven't added the code to xenith to get this to change the icons yet** so it won't actually work but what do you think about the way it works in the editor? I've added it as mandatory rather than an optional property but it only shows if relevant to the chosen theme.
