### ISSUE TITLE
New feature - page introduction optional property

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#1141]
Add new optional property group to all pages that allows you to add instructions / introduction for individual pages. This is already available on Media Lesson & Interactive Video pages but on these pages the intro opens in an accordion panel at top of page - ideally this could be set to open in a lightbox instead with a button on footer bar. Similar to the project intro, the optional property group should allow you to edit:

- Page intro text
- Whether the intro lightbox is opened automatically when page 1st opens (if so, should it open again when returning to page?)
- Whether to include a 'start' button in the lightbox which closes the lightbox (probably only useful if the lightbox is set to auto-open on page load)
- Include page title in lightbox?
- Icon & label used on button

**Comment by ronm123** [comment]
@FayCross sounds like this could be useful and popular. A few extra comments...
Would be good if there was author control over whether the into opens again when returning to the page or not e.g. I could see that you might want that in some case but not in others depending on the purpose and complexity of the intro.
Would be good to have an option to control the size (vw & vh) of the lightbox.
Would be good to have an option to control the opacity of the lightbox (%) and the colour and opacity of the background of the contents e.g. so rather than only a solid white/colour background for the contents panel the ability to change colour and opacity so that it could be a dark, or light, slightly transparent background showing some of the page contents in the background. This would benefit some of the image based pages including title page with background etc.
Presumably the new options would compliment or replace the existing options on Media Lesson and Interactive video without impacting existing projects with those options set?
Not sure about the button in the footer bar - do you envisage that being there throughout and just enabled/disabled on pages where the option has/hasn't been used? Could look a bit odd otherwise e.g. with the button appearing/disappearing as you navigate? I wonder if a button aligned center just below the header or just above the footer would be better a bit like the skip to contents link?
HTH
Ron

**Comment by FayCross** [comment]
@ronm123 I'm not sure where the best place to have the button would be - I need to have a play around to see what works best. I had wondered about a button in the header bar as an option too. I think if it was on the footer bar then the button would need to stay there throughout and be disabled/enabled depending on whether the page had an introduction. Perhaps we give authors the choice.

I also am looking at adding a project level intro but aren't sure whether this is needed if you have the option of page level intros too. Perhaps you just set up an intro on page 1 instead of at project level. Although it seems nicer in the editor to add that at project level - but then what happens if you add project level intro and a intro to page 1? I think I can only answer these questions by trying some thing out. I'll share something with you when I have some examples working

**Comment by ronm123** [comment]
@FayCross I was thinking just below the header or just above the footer. Obviously if the page has narration it would need to be just above that but would still work I think.
I know what you mean that the idea of an intro set at project level would seem better workflow wise but I think it would son be easy to follow that a project wide intro should just be added to the first page instead. In fact there are occasions where you perhaps wouldn't want that on the first/title page but do on the second or third page. So I think easier to just add the per page option rather than also LO option.

**Comment by FayCross** [comment]
@ronm123 I've committed the work I've done so far on this before I'm off for a couple of weeks. At the moment it adds a button to footer bar when this is added but I will change this to the header as discussed earlier in the week (or give option to choose).

**Comment by FayCross** [comment]
Issues to sort out:

- [ ] Move button to header instead of footer or give option to choose where the button goes
- [ ] If option remains for the buttons to be on the footer, the default icons need changing to distinguish from project level help / intro buttons
- [ ] In themes that use fontawesome icons, button appears blank unless a custom icon is selected - need to add to theme css
