### ISSUE TITLE
Bootstrap --> accordeon --> add video --> hide title does not work

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#1160]
In a bootstrap template, with a video in an accordeon navigator, the hide title function does not work. 
![image](https://user-images.githubusercontent.com/5703781/188719919-49986891-7d70-43dd-b34e-3ebcc655b9b6.png)

**Comment by FayCross** [comment]
Related to https://github.com/thexerteproject/xerteonlinetoolkits/issues/1024? Probably something to discuss at a dev day as we need a way that's not going to cause problems with existing projects

**Comment by ronm123** [comment]
@FayCross lets discuss this quickly when we meet again this afternoon. As you say it's similar or related to https://github.com/thexerteproject/xerteonlinetoolkits/issues/1024 and in that issue I mentioned that we thought we had a solution. I think we were thinking we could just add and use version=x to the Bootstrap xml. However the more I think about this it's arguably a bit more complicated than that because there are potentially so many occurrences in each project. So if you edited an existing project and so it automatically became the latest version and showed the titles where they didn't show before you would have to go through every page and every section checking. Perhaps a separate optional property like show previously hidden/all titles would be a solution?

**Comment by ronm123** [comment]
@ingedonke @FayCross obviously my previous reply here was about https://github.com/thexerteproject/xerteonlinetoolkits/issues/1024 whereas it's the opposite problem reported by Inge here but related and part of any solution we put in place.

**Comment by FayCross** [comment]
Just done some testing to work out exactly what the happens now (some of this is already detailed in #1024). This problem is only with accordion & carousel navigators:

- AUDIO: title is always ON
- VIDEO: title is always ON
- TEXT: title is always OFF
- IMAGE: title is always OFF
- PDF: title is always OFF
- XOT: title is always OFF
