### ISSUE TITLE
Graphics and Sound page: Transcript Position Optional Property

### ISSUE THREAD

**Issue by JMarco27** [thexerteproject/xerteonlinetoolkits#1205]
If you select **Below audio player**, a Transcript **button** is displayed **below** the audio player bar. If you select **Lightbox**, a Transcript **icon** is displayed **within** the audio player bar.  Do we need two different ways to access a transcript - can we just have the icon in the audio player bar?

**Comment by FayCross** [comment]
@JMarco27 I'm closing this but I have changed the default position of the transcript button on the graphics & sound page to be on the audio bar (rather than below). This brings it in line with position of button on other pages but means existing projects won't be changed automatically & there is a way for old projects with button below to be changed to have button on audio bar instead.
