### ISSUE TITLE
Hotspot Image: Auto-play audiofile?

### ISSUE THREAD

**Issue by JMarco27** [thexerteproject/xerteonlinetoolkits#1259]
Is it possible to add as an an OP for a Hotspot, an audio file that autoplays when the hotspot is clicked on?  This could either be as an alternative to the text that is displayed or in addition to it.

**Comment by FayCross** [comment]
@JMarco27 you can do this on hotspot image connector page already (remove destination page optional property, add sound optional property instead and change type to auto-play). I agree it could be useful to add to hotspot image page too though as I don't think it's necessarily obvious that hotspot image connector page can be used without destination pages.

**Comment by ronm123** [comment]
@JMarco27 @FayCross you can already do this on the hotspot image page too but I guess it depends if you want the player to show or not. But for accessibility it's probably a good idea to have the player showing if you're going to set autoplay on because then at least the user has the ability to stop if they want. So with the normal hotspot page just use the editor toolbar to add the audio and set it to auto play. Obviously you can include or remove the text from what appears too.

**Comment by JMarco27** [comment]
Many thanks @ronm123 and @FayCross . I tried out both your solutions and they worked well.  I'll add them to the wiki page on **Working with audio**.
