### ISSUE TITLE
Editor - adding plain text page

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#148]
When adding a plain text page, should the text editor have the focus with the text 'Enter page text here' already selected for typing over? Otherwise you have to select it and delete it before you can type (FWS)
By Julian

**Comment by torinfo** [comment]
Don't know...

Would hate to figure something out for every indivudual page though....

**Comment by JohnSmith-LT** [comment]
Is it easy to check at any point what the default text is for a particular checextbox/textarea/script boxes. I mean is this loaded with the wizard page mode each time the editor loads or only when the page is added?

If so the you could check the default with the current contents -

- If its the same then select all when it gets focus
- If different then just put the cursor where the user clicks

That might be doable and would be better than just doing a select all when every field gets focus since its then easy to press a key and overwrite everything.

What do you think?

**Comment by torinfo** [comment]
Yes, that should work, and we could do it for only those pages tha have a 'main' text block.

**Comment by ronm123** [comment]
Personally I can't see this is worth the effort especially for all the pages.
It's never really been raised as an issue and in some cases if you just want to quickly add a new page to check how it works or to see how a graphic looks the default text will suffice and if given focus and selected automatically you're forced to edit. If it ain't broke don't fix it?

**Comment by JohnSmith-LT** [comment]
I kind of agree but it would only really need implemented as a single focus event and applied to 3 or so input types. So it wouldnt be huge. Lets mark it as enhancement and leave until later...

**Comment by JohnSmith-LT** [comment]
I'm gonna agree with Ron here and just close this.. if it comes up again later then fair enough...
