### ISSUE TITLE
Gapfill - mark word

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#202]
I can't mark a word in the gapfill excercise with the right mouseclick. How can I use the gapfill in the new editor?
By Katrien

**Comment by JohnSmith-LT** [comment]
Seems to work now so closing this...

**Comment by ronm123** [comment]
re-opening this because something does seem right. Not sure what the different text box is for gap fil but that doesn't seem to allow right click > mark word whereas the normal text fields do but obviously it's only the gapfill text box that needs this. Manually typing the pipe character either side of words does work but the right click in the current gapfill text box doesn't show mark word.

![image](https://cloud.githubusercontent.com/assets/5167146/8066872/02589a2e-0ee2-11e5-9772-b921eed80e8f.png)
![image](https://cloud.githubusercontent.com/assets/5167146/8066887/0f15fae0-0ee2-11e5-854d-cf19639874d1.png)

**Comment by ronm123** [comment]
Should have added I've tested this with both Chrome and IE and although the right click menu options obviously vary by browser the mark word option doesn't show via either browser in the gap fill text box.

**Comment by FayCross** [comment]
Oops. That's a change I did last week that's messed it up. I'll look at it tmw

**Comment by FayCross** [comment]
I've undone the change I'd made that broke this. I'd changed the field type as the p tags were causing problems in the layout of this page in the LO - I'll try find a way to fix it in the page code instead.
