### ISSUE TITLE
Peer review needs display mode --> default

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#213]
When you use another status you can't reach the buttons as a viewer. The Learning object is to big for the screen.

**Comment by JohnSmith-LT** [comment]
Hi @ingedonke, is this still an issue? I don't see this when I try...

![image](https://cloud.githubusercontent.com/assets/3907362/7724714/0127e14c-feec-11e4-889c-7e6060e51d44.png)

**Comment by ronm123** [comment]
@JohnSmith-LT This is still a current problem but only applies if the project is set to full screen or fill window by default or if the fill window button is clicked. Here's an example: http://training.mitchellmedia.co.uk/xot/peer.php?template_id=72 pw is: dev
Works because it is set to default but click the full screen button and you'll sess what happens if that was set as the default.

BTW in my test/example here the send button doesn't do anything.

Also an enhancement would be to give the password field focus when the page loads.
