### ISSUE TITLE
Minimising boittom panel in workspace

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#231]
If I minimise the panel that hs th resources links in, I cannot get it back. Again, I'm not sure it's necessary to allow the user to do this.

**Comment by ronm123** [comment]
If I understand what you mean correctly the restore button becomes available bottom middle but isn't very high contrast so easily missed. I think it is definitely necessary to allow the user to do this - partly to allow for maximum view if you have a lot of projects but also because on lower res devices like cheaper laptops where vertical resolution is limited this space is needed to make the workspace useable and to prevent the upper button panel minimising and hiding the buttons. I think Tom was looking into that.

**Comment by thexerteproject** [comment]
Ahh, I see that now, thanks. Easily missed. Do you think it's a useful feature?

**Comment by ronm123** [comment]
not only useful but possibly essential! Laptops with only 900px height or there about are quite common and if for instance an installation has additional links in those panel taking more space, or perhaps if you need to turn on dev tools the space becomes too limited and the top button row becomes collapsed.
The button should be higher contrast though but something to look at after the redesign.

**Comment by thexerteproject** [comment]
OK, fair enough!
