### ISSUE TITLE
Branding and Nottingham

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#232]
Need to remove all evidence of UoN from Toolkits in terms of branding and copyright statements etc.

**Comment by ronm123** [comment]
I think we need to be careful not to break logo display in existing installations here e.g. there are probably many installations that haven't changed the logos via the management page but I've lost track  of how the logo names stored in the database have changed over time. I think the defaults are as follows:
top left: website_code/images/xerteLogo.jpg
top right: website_code/images/UofNLogo.jpg

I'd suggest we still include these file names in the image directory even if the file named UofNLogo.jpg is actually now the apereo logo. 

Likewise I think we had edit_xerteLogo.jpg and edit_UofNLogo.jpg as the versions that appear in the editor window so these should be included in the images directory too.

I'm not suggesting that we shouldn't change the names and formats for new installs but obviously we need to be mindful of upgrades too. 

For new installs these logos should be .png or better still .svg.

The time to do this because of these older logo's being jpg and therefore not transparent is obviously after the new design is applied.

**Comment by ronm123** [comment]
Just to add to this I just tested a clean install from the develop code and although the two new logos appear in the workspace the editor window is showing broken image links because by default the database values are website_code/images/xerteLogo.jpg and website_code/images/UofNLogo.jpg

I suggest the following:
1. we update these two logo files without changing their names so that existing installs show the correct images (if not customised) 
2. We change the default database values for new installs to point to the new png logos but named xerteLogo.png (not just logo.png) and apereoLogo.png
3. We change the code so there is no need for edit_ counterparts of the logos.

Happy to do that if we agree?

**Comment by thexerteproject** [comment]
Sounds good to me, thanks,

**Comment by JohnSmith-LT** [comment]
These ones look to have been missed

https://github.com/thexerteproject/xerteonlinetoolkits/search?utf8=✓&q=University+of+Nottingham&type=Code

**Comment by ronm123** [comment]
Question here now that the new design is in place and I guess finished...
As always organisations will definitely want to add their own logo and often colour scheme too. Nothing we can really do to prevent the latter nor should we but in terms of the logos what we've had in the past is that organisations use the management page to change the UoN logo and typically leave the Xerte logo in place. If they do that now we will have installations without the Apereo logo which I think is slightly different to having installations without the UoN logo so does this matter? e.g. no Apereo logo after customisation?
Or perhaps should we have the Apereo logo hard coded elsewhere with a link to apereo or xerte.org.uk? Perhaps even detect if the default value for the top right logo has been changed and if so automatically display the Apereo logo to the left of the Xerte logo? Or are we not worried about this in which case we close the issue?

**Comment by JohnSmith-LT** [comment]
I dont have a preference either way but I can see your point although I think if they really want the Apereo logo gone then its always going to be relatively trivial to upload an alternative without changing any code...

Whatever is decided though there are still several references to University of Nottingham at that link above that need to be replaced with the Apereo blurb Before we close it.
