### ISSUE TITLE
Images missing on management.php page

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#286]
![image](https://cloud.githubusercontent.com/assets/3907362/7832907/70bfefa4-045a-11e5-86b9-bc2ac00a372f.png)

**Comment by JohnSmith-LT** [comment]
Is this the same as the other issue @ronm123 ? Can you see these images fine? Also, do you see anything when you click on "Feeds" button? I just get a blank screen but not sure what I should be seeing there...

**Comment by ronm123** [comment]
Hi John
I quickly tested for the management login error on my remote installation whish is what I reported doesn't have the error. I'm just cloning a new copy in xampp and will test with that and report back.
On my online site I have two LO's added to the rss and export feeds and they show under the feeds tab with buttons to remove from the feeds

**Comment by JohnSmith-LT** [comment]
Ah, I see what the problem is... we still have references to xerteLogo.jpg (https://github.com/thexerteproject/xerteonlinetoolkits/search?utf8=%E2%9C%93&q=xerteLogo)

If you upgrade an existing install then this logo will be there. If you do a fresh install then it is not...

**Comment by JohnSmith-LT** [comment]
That could also be the reason for the management page issues is suppose... referencing a file that has been removed...

**Comment by torinfo** [comment]
If you look at management.php, there is an if statement that checks whther the login is correct. If not you end up in e really old strange block of code. The comment says that it will check whether the usertype is an admin, but it doesn't happen.

I would suggest to take that whole block out. (starting around line 300)

**Comment by ronm123** [comment]
Hi John
yes the logos are still a bit of a mess I think in terms of both maintaining compatibility for upgraded installations and new installs. To my mind both should still be using the database values and I'm not sure they are now. A clean install has xerteLogo.jpg as the default top left value and uofNLogo.jpg top right. So we need to change the values in the install script and make sure the code is using the database values.
The images currently in the images folder by default are logo.png and apereoLogo.png
I think it should be xerteLogo.png and apereoLogo.png
But for those upgrading who haven't customised their installs their database values will still point to UofNLogo.jpg and xerteLogo.jpg
A couple of solutions to this latter point I think:
1. we include those file names but change the content itself to the new Xerte Apereo logo's even though the filenames would misrepresent the UofN logo
2. we deal with this via upgrade.php and check if the values are still default and if so change to the same as a clean install

Turns out I can replicate the errors too. I was only trying the username field. If a wrong password is added that's when the error appears regardless of anything in the username or not.

**Comment by JohnSmith-LT** [comment]
Ah good. Thought i was going crazy there... do you also see the white/grey background issue at different times?

As for the logos, I agree they seem to be a bit all over the place. A fresh install uses the xerte/apereo logos correctly everywhere except management but still puts xerteLogo.jpg into the database (we need to change that)

I think your point 2 is the best way to go, use upgrade.php to change them to the new values. The problem I see is that do the database values only get used in management.php? I had the xerteLgo/UofN paths in the database but logos show perfectly in workspace, editor etc. It was only management that freaked out because they didn't exist...
