### ISSUE TITLE
Error saving change to template

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#287]
Can anyone else get this error?

![image](https://cloud.githubusercontent.com/assets/3907362/7834487/b6cbb728-0467-11e5-9323-df00709585d7.png)

Open the properties of an LO
Make it public
Go to RSS
Tick Yes and press Save - you get the error above
Press Save again and you get the same message

Type something in the description box (the message implies it is optional)
Press Save again - this time the message doesn't appear

**Comment by ronm123** [comment]
Yes I can replicate that exactly.
To be honest I thing the description should be required rather than optional as project names are often too cryptic.
Suggest we change the error message to "Please add a useful description and then save."
and change the description to:
You must also add a useful description of your project before saving.

**Comment by JohnSmith-LT** [comment]
Ok, leave that with me and i'll change the message and commit.
