### ISSUE TITLE
Media Lesson: Should we respect order of things?

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#308]
![image](https://cloud.githubusercontent.com/assets/3907362/7961631/a691a752-0a00-11e5-8a29-dcf2d6fb1920.png)

**Comment by FayCross** [comment]
This template gave me headaches when trying to work out what it should and shouldn't look at with layout and timings etc.

You have a wizard option to say whether content appears above or below content already there and I thought that was enough. I think if I was making a media lesson page I would want to arrange things in the tree by their synch point rather than their position on the screen. I think that could get very messy, especially if you have a lot of content with different start and end synch points. Also, if we are going to add Brad's idea of relative synch points then you couldn't have them arranged on the tree both for their timings & their position.

**Comment by JohnSmith-LT** [comment]
Yeah, I can understand that completely... when you have conflicting settings it's always difficult to give one priority over the other... I'm just putting it out as a question as people expect the tree to be the order... 

This is the first time i've really played with the new page and I think it's fantastic what you've been able to do in the one place... so much functionality...

**Comment by FayCross** [comment]
Thanks! 

I'm happy to look at changing it if there's a general view that it's confusing as it is. I'm sure there are bits that could be more user friendly

**Comment by FayCross** [comment]
Closing this as it wouldn't work in conjunction with the new relative synch points
