### ISSUE TITLE
Editor - line break problem in TextInput fields

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#349]
Issue raised here (with screenshot): http://xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=877&Itemid=759&lang=en

When line breaks are added to text input fields the text is split into multiple boxes. Extra blank lines (each with its own field) are then added when the wizard is returned to. Can we stop line breaks being added all together?

**Comment by ronm123** [comment]
Just to clarify this is Title fields not the larger text fields?
Sometimes it's useful to have multiple lines in titles but I've often just used <br> to achieve that.
Having said that I tried <br> in the main title of a Bootstrap resource yesterday and it actually just displayed the <br> rather than a break.

**Comment by FayCross** [comment]
Yes, the single line boxes (TextInput in xwd rather than TextArea).
I don't mind if we leave it so that you can add line breaks to them - I just thought that might be an easy way to fix the problem of the lines doubling when return to the page after you add line breaks

**Comment by FayCross** [comment]
Reported again on forum - http://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=989&Itemid=207&lang=en
