### ISSUE TITLE
bootstrap export media issue

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#352]
Prompted by a question on the community forums I just re-tested Bootstrap export and not sure if this is just an issue when viewed locally rather than uploading and viewing online but when exporting and viewing locally the xml contains links to media like the following:
header="FileLocation + '/media/barrier.png'"
url="FileLocation + '/media/page_types_screenshot.png'"
The first forward slash means the media folder and therefore images aren't found.
Changing to:
header="FileLocation + 'media/barrier.png'"
url="FileLocation + 'media/page_types_screenshot.png'"
seems to work fine.
Like I say I haven't checked if that changes if the zip is uploaded, extracted and viewed via a VLE etc but I suspect it might be the same.
Haven't looked at how easy this would be to fix yet - I suspect quite easy but got to go offline for a while now.

**Comment by thexerteproject** [comment]
The problem is affexting both bootstrap AND xerte toolkits projects. FileLocation is an empty string (in bootstrap projects) and undefined (in toolkits projects), so paths cannot be properly eval'd.

In the case of the bootstrap example, a simple check an solve the issue:
If (FileLocation == ''){
  var FileLocation = String(window.location).substr(0, String(window.location).lastIndexOf('/')  + 1);
}

In the case of a toolkit project, FileLocation is undefined. Pesumably something similar will work in Xenith.js.

I'm trying to work out how FileLocation is set in toolkits, and how we can reliably test for an exported project and calculate the path. Tom m,ay have some other approach?

At least we know what the issue is: it's not an additional slash being added; the paths do actually work fine if Filelocation is what it should be. 

So we need to test and set it.

**Comment by torinfo** [comment]
Be careful:

The FileLocation is supposed to be set in the main htm file for the exported object. The source is rloObject.htm (modules/site/player_html5 and modules/xerte/player_html5). On export the %XMLPATH%  is supoosed to be replaced by a proper value (like '.')

If this doesn't work anymore,we need to check the export code!

**Comment by ronm123** [comment]
Just noticed a perhaps related issue with the stand alone decision tree template...
Create a project based on the project template, using the editor add an image. The image displays in the editor itself but doesn't show when playing the project. Looking at the xml it has FileLocation + '/media... so wondering if this is a related issue?

**Comment by thexerteproject** [comment]
It seems all paths from the new editor have /media (i.e. with the leading slash): in the old editor FileLocation always held the trailing slash. The new format works as expected on the server: I expect the decision tree template is expecting the old format?

**Comment by torinfo** [comment]
Hmmm.... I changed the code back so that only media is used in stead of /media like the old editor did.

Otherwise offline export won't work, because it cannot get the current location in all cases.

It would be good to test this.

This can be problematic for some of the new objects. If you export before publishing again, you might end up in the situation that the export doesn't work. Publish and re-export should solve that.

**Comment by daustin100** [comment]
attempted to export from bootstrap on v3.0 and it says it works with VLE but i want just the offline version like one can do in XOT so i can put on a website i am building with laravel  
what do u suggest?
