### ISSUE TITLE
Problems with export of Decision Tree template

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#361]
Deployment Zip only
Media included using ckeditor not exported with zip

Both
English language file not included giving 404 error
NOW FIXED mediaPlayer not firing the mediaMetadata function to complete display of video

**Comment by ronm123** [comment]
Hi John with my testing yesterday the media did seem to be included in the export but perhaps that's because I'd added the media via the optional property rather than the editor.
Can confirm that with your updates in place the video now plays in the exported copy.
Will leave you to close this if that's everything covered.

**Comment by JohnSmith-LT** [comment]
Hi Ron,

I've now fixed the missing language file 404 but i'm still seeing a missing media file if the only place it is referenced is in the ckeditor, i.e. not as a xerte property... are you able to confirm with a new project?

**Comment by ronm123** [comment]
Hi John do you mean images or video/audio?
I just created a new decision project, added an image to the first intro box, added a question so that the LO plays, clicked publish, clicked play to verify the image displays. Then deployment export and the image is in the export and displays when viewed offline.
I don't see an option to add uploaded video direct via the editor itself unless adding via the url option.

**Comment by JohnSmith-LT** [comment]
I suspect @ronm123 that your image is included in the xml somewhere... the issue i'm seeing is:

![image](https://cloud.githubusercontent.com/assets/3907362/8927793/df773302-3511-11e5-9e1e-a71c6966b091.png)

The image is in use in the wysiwyg editor but is not identified as in use by the Media tab (left, above) or by export. So it shows in Play (right, above)

What I mean by uploading in the editor is using this dialog

![image](https://cloud.githubusercontent.com/assets/3907362/8927836/3d2c996a-3512-11e5-8598-2485a0c316e8.png)

**Comment by ronm123** [comment]
Hi John
I can't replicate this.
I created a new decision project, added an image via the image button in the editor (not the image optional property) added an information step so that the project plays and check that the image displays when preview. Then check properties media & quota and the image shows as in use. Exported the project and the image is included and displays in the offline copy.
