### ISSUE TITLE
Issue with Glossary and/or spaces in editor

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#374]
I mentioned to Julian that I'd had reported an issue with some glossary entries not appearing but needed time to investigate further. After further investigation it seems this was down to the word (in this case "carnivores") followed by a &nbsp; rather than a plain space. That wasn't something added deliberately by the user, it's more likely that they inadvertently added two spaces rather than a single space after the word which it seems the editor treats as a request or need to add a non-breaking space and in fact if you type 3 spaces it adds two non-breaking spaces and so on. I'm not sure if that's desirable or changeable or not? But the other solution is to update the glossary code in xenith to deal with words preceded and/or followed by &nbsp; I had a quick look at xenith.js but not sure how to update the regular expression to deal with this?

**Comment by FayCross** [comment]
There are some other problems with words being highlighted for the glossary that a user here has found.

Words are only found if they have a space on either side or are followed by .,!?

Words at the very beginning or end of a text field used to be found but they're not anymore (unless followed by one of the punctuation above). This is because of the <p> tags added by the new editor. 

Words aren't found if they're next to any tag (i.e. preceded by > or proceeded by <)

I'll have a look at the regular expression and see if I can work out how to update it.
