### ISSUE TITLE
Interactive Diagram

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#382]
Cannot import images via the editor: user reported on the forum and confirmed here.

**Comment by ronm123** [comment]
Do I remember this being discussed elsewhere too? I've been supporting a project who have used the interactive diagram quite well previously but now in version 3 the imported image in each interaction doesn't show so can't be easily edited unless switching to the Flash editor. The existing LO's play ok but editing and for instance moving or adding the hotspots can only be done via the Flash editor. Is there any risk to the other pages e.g. stripped html if opening and editing these page types in the Flash editor?

**Comment by thexerteproject** [comment]
I've never been clear whether this was related to the issues of uploading media in Firefox, and the changes that were made to accomodate that weren't applied to this template, or whether it is something else. I thihnk it is the case that media doesn't upload, but media uploaded previously does play properly, so I assume it is to do with that file upload stuff?

**Comment by ronm123** [comment]
Not sure it's just the upload because editing via the html 5 editor doesn't show existing images and switching to the Flash editor does. Normally I might suggest they use the hotspot image or connector hotspot instead but in this case they are quite nice interactions with arrows pointing to areas of a photo and the arrows are obviously highlighted when clicked so it works quite well. Just a bit wary of suggesting that if they need to edit or add hotspots they switch to the Flash editor in case that has a wider impact? Obviously switching to the Flash editor isn't ideal anyway.

**Comment by thexerteproject** [comment]
I think Tom or John need to chip in their knowledge as I have no idea how it's all wired up now.

**Comment by FayCross** [comment]
Should we deprecate this page until we have this working? So that existing projects still work but you can't create any new ones. It doesn't seem to be working for us in the Flash editor either now

**Comment by FayCross** [comment]
Does this page work now John? Great if it does!

**Comment by JohnSmith-LT** [comment]
Works for me Fay, can anyone else confirm?

**Comment by FayCross** [comment]
Just checked - works for me in Chrome but not FF

**Comment by JohnSmith-LT** [comment]
Ah, I suspect that that is related to the Flash cookie bug that we spent so much time trying to solve for the flash editor. Tom modded that editor specifically to work with the new HTML5 editor so i'm not even sure whether it supports the cookie passing code that we used before.
