### ISSUE TITLE
Synch time on synched video pages

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#390]
I noticed yesterday that there is no property for the synch time showing on synched video nested pages. I'll look into this.

**Comment by thexerteproject** [comment]
Hmm, it checks out on localhost in a new piece, this might be something to do with legacy pieces, we changed the nested pages a little bit for v3.0

**Comment by FayCross** [comment]
This will be because it used to use the 'nestedPage' that only the navigators use now. I guess the synch point property was removed from it as it's not used on the pages that use this child now so for old video synch pages still using this child it doesn't know how to show the data from the xml in the editor.

I would have thought adding it back into the xwd will fix it. Not sure the best way to do this so it doesn't end up as a property again on all the navigators again that still use the nestedPage child though

**Comment by thexerteproject** [comment]
I'm going to change the name of the nestPage in the xml in this case - it happens in our page types demo . I don't think it is used too often (having some analytics that can tell you how often and in what piece a page type is used on an installation would be really handy).

**Comment by FayCross** [comment]
I've just come across this problem in the transcript reader page too. I'll add the synch property back so that it shows for pages like this but won't appear on the navigator pages still using nestedPage
