### ISSUE TITLE
<textarea> tags in plain text page (and elsewhere presumably

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#410]
If you add code along the lines of 

<p><textarea></textarea></p>

<p><textarea></textarea></p>

<p><textarea></textarea></p>

to the source of a plain text ppage and play, it works. If you quit, and return to edit in a new sesion, the two text areas are displayed in the editor window and things go wrong. Is there a way to distinquish textareas for the editor, and text areas that are part of the html content?

**Comment by thexerteproject** [comment]
ah.
`<p><textarea></textarea></p>`
`<p><textarea></textarea></p>`
`<p><textarea></textarea></p>`

**Comment by FayCross** [comment]
This has come up before but we just had a work around of creating them in jquery - see #394

**Comment by ronm123** [comment]
What's the purpose of adding the textarea sections selectable code? This works for me but if it's code untick auto complete. When switching back to non-source view some of the code get's converted but still displays ok?

![image](https://cloud.githubusercontent.com/assets/5167146/12507828/2666fd64-c0f0-11e5-893a-9dcd96d1be88.png)

BTW still love the way it's possible to copy and paste an image here on github - definite wishlist item for our editor!

**Comment by FayCross** [comment]
@ronm123 not sure what you mean by 'What's the purpose of adding the textarea sections selectable code?'

The bug is only obvious if there's some content after the text area code tags. In Julian's example with three text areas the editor looks like this if you leave the page and go back to it...
![textarea](https://cloud.githubusercontent.com/assets/8926470/12610503/1749705c-c4e0-11e5-925e-b2552b90902e.png)

Or if there's just text after a text area it also messes up...
![textarea2](https://cloud.githubusercontent.com/assets/8926470/12610591/87886bd4-c4e0-11e5-89a9-fc63374736b8.png)

Both of these examples look ok when previewed though.

**Comment by ronm123** [comment]
I think I found another bug with textarea tags.
If you have a `<textarea>` on the page any code after that e.g. `<p><button onclick="myFunction()">Print this page</button></p>

<script>
function myFunction() {
    window.print();
}
</script>`

gets removed when you move away and then back to the page in the editor.

**Comment by ronm123** [comment]
anyone got a solution to prevent that?

**Comment by FayCross** [comment]
Shall I add ckeditor's forms plugin to get around this? It means an extra section on the toolbar but would mean we don't have to do workarounds for adding textareas. This would be useful for some things I'm looking into too.

![form](https://cloud.githubusercontent.com/assets/8926470/19526405/44e43ec6-961c-11e6-8484-0dd00f8d58e0.JPG)

**Comment by ronm123** [comment]
@FayCross sorry missed this message and question previously and notice nobody else has replied :-(
Yes I think that would be very useful to have those options as part of the toolbar. Perhaps if possible they should be at the end rather than between more commonly used features but definitely useful I think unless others have any concerns?

**Comment by FayCross** [comment]
Fixed with #828
