### ISSUE TITLE
username == USERNAME

### ISSUE THREAD

**Issue by thexerteproject** [thexerteproject/xerteonlinetoolkits#411]
We have a user who had a custom user name set up, say ABC. If he logs in as 'ABC', all the workspace works, projects show etc, but he cannot edit them: the editor opens without a project in it

If he logs in as 'abc' all works as it should.

So there is some sort of toLowerCase() thing going on somewhere in the editor?

**Comment by ronm123** [comment]
I've just been trying to troubleshoot a similar issue. In this case a completely new user created a test project using the Bootstrap template and was able to edit and populate that. However every subsequent project including this original won't open in the editor. Looking at the user-files directory the original had an uppercase username but all subsequent projects have lowercase username. I asked if she could try logging in using lowercase username but apparently that makes no difference. In this instance I don't have remote access to the database but I'm guessing this is somehow dependant on how the username is created in Xerte and then how it is subsequently used by different parts of the code.

**Comment by torinfo** [comment]
What I do know, is that the foldername in USER-FILES normally have lowercase usernames. Even if the username itself has capitals in there. 

As far as I can tell this has always worked, but perhaps it's broken recently.

**Comment by ronm123** [comment]
In my case this was a brand new user logging in for the first time to 3.1 via ldap. The first project they created had username format 3329-XYZ-Nottingham and was editable but after that project folders were 3330-xyz-Nottingham etc and not editable. Have now got a copy of the db and will investigate a report back later...

**Comment by ronm123** [comment]
Just to confirm the logindetails username for this user was created as all uppercase. Changing that via a mysql command to lowercase meant that all the projects in user-files with a lowercase username are now editable but I had to manually rename the first original project folder which had an uppercase username so that became editable too. Not sure why this happened for this user and not others e.g. there are other new users since this install was upgraded to 3.1 who's usernames have been created as lowercase.

**Comment by JohnSmith-LT** [comment]
Closing as this issue is linked to from #570 and covers a lot of the same problems...
