### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#413]
After updating to 3.1 we have several messages that the responsiveness doesn't work like it should. What we know so far is that in the default Xerte Online Toolkits theme the top bar gets higher then normal and it doesn't matter if you use or use not the checkbox responsive text. The top bar off the other themes respond ok on the responsive checkbox as far as I can see.

The other thing is that there is a different behaviour in the different browsers in the height of the text on a page. Below a few examples.

IE11 looks ok
![image005](https://cloud.githubusercontent.com/assets/5703781/12672004/a545088c-c673-11e5-9310-74dcde94c101.jpg)

Chrome not
![image002](https://cloud.githubusercontent.com/assets/5703781/12672010/a8bbc21c-c673-11e5-87f3-5f7493a88e94.jpg)

Any ideas?

**Comment by ronm123** [comment]
Not sure about the top bar issue but different text sizes are possibly two or three different things:

1. If there are any font sizes applied in the editor these will override the theme styles. So if for instance text is selected and set to 14pt by the author then that will remain 14pt even when other text is responsive.

2. The responsive styles only work on html so if an existing LO is used which hasn't been edited with the new editor then some text may not be responsive until a basic edit is applied which then adds <p> tags etc so that the responsiveness works.

3. Finally different browsers do display vmin sizes differently so for instance body text in IE might be smaller than displayed in Chrome or Firefox but that's the case with other size values too.

**Comment by torinfo** [comment]
One of the issues is, that responsivetext is always switched on for the default template. I don't think that's desirabe. It's probably a bug, We didn't want to do this correct? By default responsive text should have been turned off

It is caused by the lack of checking for the value of the responsiveness paramater in xenith,js near line 451:

```
if (param == "theme") {
		if (x_params.theme != undefined && x_params.theme != "default") {
			$.getScript(x_themePath + x_params.theme + '/' + x_params.theme +  '.js'); // most themes won't have this js file
			x_insertCSS(x_themePath + x_params.theme + '/' + x_params.theme +  '.css', function() {x_cssSetUp("theme2")});
		} else {
---->		if (x_params.responsive == "true") {
				if (x_params.displayMode == "default" || $.isArray(x_params.displayMode)) { // immediately disable responsivetext.css after loaded
					x_insertCSS(x_templateLocation + "common_html5/css/responsivetext.css", function() {x_cssSetUp("stylesheet")}, true);
				} else {
					x_insertCSS(x_templateLocation + "common_html5/css/responsivetext.css", function() {x_cssSetUp("stylesheet")});
				}
			}
		}
	}
```

**Comment by torinfo** [comment]
Hmm. That is not the solution. If I do that, the whole object doesn't display anymore!!. Without so much as an indictaion why. Apparently responsitext.css is NEEDED by the default theme.

**Comment by thexerteproject** [comment]
Closed
