### ISSUE TITLE
Responsive text issue on Title page

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#421]
Because the text size of the title is always fixed on Title pages it looks very odd when the rest of the text is responsive. Not sure whether this can be corrected in responsive code ( @ronm123 ?) or whether we would have to remove the ability to control the size of the title text completely.

**Comment by ronm123** [comment]
Hi Fay
I just checked this and I seem to recall that the reason I didn't include in the separate responsivetext.css is because the title page title text doesn't seem to have a unique ID or class or is .centerAlign only used for the title page title text?

As you say it's also a bit more tricky because of the user controllable size property so perhaps this needs to be set to a vmin size from xenith.js rather than via the css?

**Comment by FayCross** [comment]
I'll have a look and see if I can change it to vmin

**Comment by ronm123** [comment]
Hi Fay
if you do keep in mind that the current vmin stuff is all within media queries and mostly only when min-width: 768px below that the vmin sizes aren't used because otherwise they would all have needed to be added and changed for lower resolutions e.g. 2vmin and 3 vmin is too small on most smartphones.
