### ISSUE TITLE
Timed release of pages / Bootstrap content 

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#438]
From Xerte Conference Developers Day

Make LOs available from a specific date and then use relative dates to release pages

Related to Show / Hide Pages #437

**Comment by FayCross** [comment]
I've committed this for the XOT template & will get it working for Bootstrap too.

It's part of the 'hide page' functionality so the hidden icon still appears against the page on the editor tree regardless of whether the current date means that the page will be shown in live projects or not. Do you think this will be confusing? I thought it was useful as a flag to show that the page may at times be hidden.

**Comment by ronm123** [comment]
@FayCross just quickly testing this and seems to work great! A few comments...
Re the icon yes I think there should still be an indication that hide settings are switched on although ideally it should perhaps change to a different icon if set to hide based on date/time?
I notice the tooltip currently says "Give a description here" Do you plan to add the description?
I wonder if the Hide From and Hide Until labels should show the format instead of just (Time) e.g.
Hide From (dd/mm/yyyy)
Hide From (hh:mm)
Hide Until (dd/mm/yyyy)
Hide Until (hh:mm)
I assume those formats are fixed and can't be empty? e.g. I tried hide until time 6.02pm and it stopped the LO from playing altogether.
I then tried 
Hide From 30/05/2018
Hide From 17:40
Hide Until 30/05/2018
Hide Until 18:00
Which worked and showed the page at 18:00 but if I then removed the 18:00 value the page no longer showed. Without a hide until time would that automatically show from 31st?

I can see this being a really useful feature perhaps with people wanting to be able to apply the exact same settings to multiple pages but apart from copy and paste or typing each field I can't think how that might be done?

HTH
Ron

**Comment by FayCross** [comment]
Oops, yes that description was a reminder to not forget to add one but I still have managed to! I’ll add it tomorrow along with changing labels to editor fields - I like your idea of including format there. Yes they do have to be in format DD/MM/YYYY & HH:MM.

You should be able to leave fields blank though, so just ‘hide from’ & no ‘hide until’ or vice versa. Can also have ‘hide until’ earlier than ‘hide from’ so it does hide/show/hide rather than show/hide/show if that makes sense.

I thought I’d done it so that if time was blank then it would default to hide & show at the beginning of the days selected - i’ll double check that as it doesn’t seem like what you are seeing

**Comment by FayCross** [comment]
Should all be working now. Also added to Bootstrap template
