### ISSUE TITLE
Add audio button to WYSIWYG toolbar

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#447]
From Xerte Conference Developers Day

So you can add audio anywhere you can have text without the need for an optional property (#25 #23)

**Comment by JohnSmith-LT** [comment]
Is this the kind of thing you mean @FayCross ? This simple Quiz plays clapping if you get the correct answer and booing if you select one of the wrong answers.

![image](https://user-images.githubusercontent.com/3907362/69014379-95fc6a00-0981-11ea-86f1-a3a6ae9004a8.png)

I was able to add this using the wysiwyg using html5audio plugin for ckeditor

![image](https://user-images.githubusercontent.com/3907362/69014396-c6dc9f00-0981-11ea-8ddf-832d380b289d.png)

It's a bit annoying to setup since if you set the audio to autoplay then it plays every time you go into the answer to edit. Also, it could maybe do with some work to add an option to be able to hide itself in the LO but be visible within the editor.

**Comment by JohnSmith-LT** [comment]
I decided just to commit it since I think we will use it in one form or another and it's easier for you to test. Have a look at this too @ronm123 when you get a chance and see what you think...

**Comment by ronm123** [comment]
@JohnSmith-LT this seems to work really well and having the advanced options is great too. Is that something we can easily add to? e.g. in your example where it's a clapping or a boing in answer feedback it might be useful to have those simple sounds auto play and therefore an option to hide the audio player. Easy enough to achieve with some css e.g. `.ckeditor-html5-audio {
    opacity: 0;
}` but easier to give authors control without having to do that?

Is there a recorder option we could add too? I created a resource for the future teacher project that we could link to somewhere https://xot.futureteacher.eu/play.php?template_id=67#resume=1 but even better if ther was a recorder button on the toolbar that uploaded automatcally to the media folder.

**Comment by FayCross** [comment]
This is great, thanks @JohnSmith-LT. The align options don't work for me though - it's always on left regardless of which option I choose.

**Comment by JohnSmith-LT** [comment]
Hi @FayCross yeah I need to do some work on that still to make someof the options work. I still haven't found how to detect if the player is in the editor or in the LO as I have added an option to hide the player (for feedback - works great with autoplay - if allowed by user) but then it hides it in the editor too and you can't edit it or find it easily...

I will get back to it soon.

**Comment by FayCross** [comment]
I've just tested this in develop & there are some things that don't work as I'd expect:

- [ ] Align centre doesn't work (appears on left)

- [ ] Auto play doesn't work in preview in Chrome for me but it does auto-play in editor if I return to the page where I've added it 

- [ ] Editing an existing instance of this in the editor is temperamental. When first added I can right click to get audio properties back but if I change page & go back again I can't see that option. You have to delete audio & start again. I think this might be the case with other things too & not unique to audio though

**Comment by FayCross** [comment]
Close as duplicate of #1117
