### ISSUE TITLE
Theme generation / Xhibit

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#465]
From Xerte Conference Developers Day

Include link (from Workspace?) to Xhibit website http://www.xhibitapp.com/

**Comment by JohnSmith-LT** [comment]
Something like this @FayCross or did you have something else in mind?

![image](https://user-images.githubusercontent.com/3907362/69013991-ca6e2700-097d-11ea-9b1f-93f8054c936e.png)

**Comment by ronm123** [comment]
@JohnSmith-LT @FayCross I don't think we should link to Xhibit with a logo in the footer like that. I think the current logos bottom right represent licensing etc rather than useful links/other tools. I do however think we need to look at the various links and blocks in the workspace as well as how some of those are populated and controlled via management and/or populated during installation and updates. Probably something to discuss during a future dev meeting.

**Comment by JohnSmith-LT** [comment]
Hi @ronm123, yeah that sounds reasonable. There are other places as you say - for example those Site 1, 2 & 3 can be changed in management but have never been populated by default...
