### ISSUE TITLE
Crashes when second video is minimised after viewing full screen

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#485]
Two pages containing video. View 1st one full screen and then minimise. View 2nd one full screen. When you then try to minimise it always crashes.

**Comment by JohnSmith-LT** [comment]
Hi Fay,

Do you have steps to reproduce this? Or an example you can share? I just tried with 2 videos i Multiple Perspectives and both played, went full screen, played for a little, went back to normal view and did this several times with no issue.

Is it a specific browser or platform issue or has it been fixed in develop by a library or code update?

**Comment by ronm123** [comment]
Hi John I think this only happens with the video page. To replicate create more than one video page and then test the maximise minimise buttons on the video player- the first page will probably work fine but the second will cause the crash?

**Comment by JohnSmith-LT** [comment]
Thanks Ron, yeah i've managed to reproduce and it is a bit catastrophic.... i'll have a look and see if I can figure out why it does that...

**Comment by JohnSmith-LT** [comment]
I have no idea why removing that intercept works. Even commenting out the single line call to textVideo.init() does not work... It doesn't appear to be needed in this page model though - unless i'm missing something and the comment is the same as that of the multiple perspectives page.

**Comment by FayCross** [comment]
Closing as it looks like John's fix has worked
