### ISSUE TITLE
Capital disappears in the interactivity Dialog

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#501]
Add optional property 'case sensitive' to Dialog as in Gap Fill

For example the answer to "... est votre nom?" I want to write "Quel". As soon as I press the button the word changes into "quel" but is shoul stay "Quel".

**Comment by JohnSmith-LT** [comment]
Hi Inge,

I've fixed the issue where the case always changes to lowercase when you get it correct but do you also want it so that if you type it in the wrong case then it would be wrong? i.e if the answer is 'Apple' and you type 'apple' then that wouldn't match?

At present it skips all leading and trailing spaces and any differences in case so Apple, APPLE, apple ApPle would all be considered the same.

**Comment by ingedonke** [comment]
I think when you add the optional parameter 'case sensitive' that the student has to fill in exactly what the teacher added. So the teacher can choose what he wants.
