### ISSUE TITLE
Transcript Reader can't add labels anymore

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#526]
It's not possible anymore to add a lable to the nested page in the transcript reader.
![transcript_reader](https://cloud.githubusercontent.com/assets/5703781/15801874/fe6ea7c2-2aa2-11e6-98af-f7fce777d3c0.png)

**Comment by JohnSmith-LT** [comment]
Looks like @FayCross removed it back in https://github.com/thexerteproject/xerteonlinetoolkits/commits/develop/src/Nottingham/wizards/en-GB/transcriptReader.xwd

Easy enough to add back in but was it removed for a reason?

**Comment by FayCross** [comment]
I removed it because it seems weird to me to fill things in that don't appear anywhere in the final project (the text shown in LO is 'page text' not the label field). I may have removed similar things elsewhere too.

I know Tom has recently added in a label field to mcq answer options though (the text appears in editor tree but not in LO) so I might be alone in thinking it's confusing to add text that's not used outside editor.

In cases like this could we get the editor to use the first few words from the page text field (or equivalent) in the tree instead of adding another field that's only used to name tree item? Or add the (useless ;) ) field back in if everyone disagrees with me.

**Comment by JohnSmith-LT** [comment]
Ah, I didn't look closely enough at it. Personally I agree with your reasoning - otherwise people add something in there and spend ages trying to figure out where it appears in the LO.

I think the problem with showing the first few words of Page Text is that how do you decide when to do it? You'd need to have a page specific rule (which could become unruly) to decide when to as with a deprecated property the issue is that in old LOs it might be in the xml.

What happens to deprecated properties if they are required in the Flash engine now? Do we support backward compatibility to the old Flash engine for these (although obviously new pages will break it anyway).

**Comment by FayCross** [comment]
We could have an attribute added to the field we want to be used instead...
` <text label="Page Text" type="TextArea" height="250" tree="true"/>`
So the default would always be to use the value from the name field but we can override that when we're hiding that field from the editor.
If it's in old LOs I don't think it would be a problem as it would just change tree appearance rather than break anything.

We don't have any backward compatibility for newly created projects and Flash. Projects from before xenith changes should still work in Flash except where new pages have been added (including new old pages if that makes sense as the inserted page won't include the deprecated properties). I think most deprecated properties have been optional ones though so would be ok.

**Comment by torinfo** [comment]
Clearly, I do not agree, otherwise, I wouldn't have added labes to questions and options in a.o. the quiz.It serves two purposes:
1. It makes authoring and maintaining an LO a lot easier, as you can immediatle identigy a question and or answer from the tree. It is not that obvious to use the text, as the text can be a single image.
2. It makes identifying questions and answers in the tracking code a lot more sensible as well, because now, I can use the labels.

So, all in all, I am in favour to add labels to items, even just to able to identify them in the page tree during authoring.

**Comment by JohnSmith-LT** [comment]
Hadn't considered these reasons Tom so these obviously outweigh any perceived disadvantage so I agree that they should go back in...

**Comment by FayCross** [comment]
But the single line text fields can also be images rather than text. Maybe it does make more sense for pages with tracking but on this page (transcript reader) it's literally just for tree label.

I would still prefer to not have and to find a better way - but I won't take out any that you've added Tom!
