### ISSUE TITLE
Allow hidden pages to be linked to

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#531]
From a conversation Inge & I had at the Apereo conference...

Now that there's an optional property 'hide' on all pages (#437) would it be useful for page links to work to these hidden pages?

The hidden pages' titles appear in page link list in editor but the link created doesn't work.

I'm not sure what the page would look like when you followed the link though - I suppose you would have to hide its page number and the forward button so you could only go back to the page you came from?

**Comment by JohnSmith-LT** [comment]
Or would the player simply not go to a page that is hidden? It might be that a page is hidden only for the reason that you are working on it at present and you still want to be able to link to it so that when it is unhidden the page link then works. There are several options, such as go to the page after the hidden page (perhaps not desirable) or simply showing (hidden) after the page name in the Page Link dropdown?

**Comment by FayCross** [comment]
Yes, the idea behind the hidden pages was so that you could work on a page while the project was live or do gradual release of pages.

I don't think I was very clear above but Inge thought it would be useful to allow the links to hidden pages to work - so you would get to the hidden page if you followed a link to it but otherwise the page wouldn't appear through normal navigation forward or on the page menu. Ignore this for now - I need to have a think about what would happen. Maybe it wouldn't add anything that can't be done with connector pages already.

**Comment by ronm123** [comment]
Just re-reading this and I added a related item about hidden pages in #580 about enabling lightbox functionality e.g. where the page could be hidden but still display in a lightbox if we manage to add that functionality. It's a popular feature in other tools.

**Comment by FayCross** [comment]
I'm working on getting links to hidden Bootstrap pages to work at the moment but have come across something odd. At the moment you can add links to hidden pages with the Xerte page link button in the editor. If previewing with author support on the links work properly (because author support allows you to view hidden pages). When viewing play version the links don't just break but take you to the next page that is available (or page 1 if hidden page is at end of project). Just wanted to check that no one objects to me changing this - there's a chunk of code purposely doing this (possibly written by me ages ago!). I think it would make much more sense to just have a link that doesn't work if a page is hidden (like in XOT template projects)

I am probably going to add another check box to the hide/show page optional property block that you can check if you want the page to be hidden from menu but available to link to. Any links to pages where this isn't checked won't work.

**Comment by ronm123** [comment]
@FayCross no objections from me to making the change you've described so that when viewing the public view the links just don't work when the destination page is hidden. The additional checkbox sounds useful too.

On a related note we've had a small issue with the author support styling on the Future Teacher project recently because we are now adding additional/new pages to our public projects in readiness for a re-run of each webinar so we're turning on author support and viewing the hidden pages that way until we are ready to un-hidethe new pages but the size of the author support text and hidden page text has quite an impact on the page display because it's so large. So I started adding some css to the projects to reduce the sizing of the red text and this works fine but I wonder if we should change the defaults because I'm not sure there's a need for the red text to be so large? Here's an example with the default and then my custom css applied as well as the css I've used:

Current default:
![image](https://user-images.githubusercontent.com/5167146/73446568-e8301300-4354-11ea-881f-2b8aee9ef495.png)

With custom css applied:
![image](https://user-images.githubusercontent.com/5167146/73446606-f5e59880-4354-11ea-8d29-df305c909ab2.png)

And css used:
`/* reduce size and impact of authoring support alerts*/
#x_authorSupportMsg {
padding: 0 !important;
}
#x_authorSupportMsg  p{
padding: 0 !important;
font-size:10px;
margin-left:10px;
}`
So questions are:
1. any reason not to reduce the size by default in one of the core style sheets and if so what stylesheet should I use?
2. I haven't checked if the same issue exists in Bootstrap and it may be less of an issue even if it does but if I/we do make this change should the change be for all templates?

**Comment by torinfo** [comment]
@FayCross Reading the original issue addressed here, it sounds like the link not working (or navigating to the next page) is not the intended behaviour.

However, I would prefer the link not working than linking to a different page.

**Comment by ronm123** [comment]
This is a classic example to me where we could end up with a much more flexible and powerful set of changes if we were able to have a verbal and interactive discussion about it at the beginning of an online developer day. e.g. the point I made earlier in the thread about being able to add hidden pages that don't show in the toc and open in a lightbox would make it very easy for authors to achieve that and overlaps with some of the other ideas.

**Comment by JohnSmith-LT** [comment]
@FayCross I agree that it's probably best if the link doesn't work than take you to the next page which might not even be relevant...

**Comment by FayCross** [comment]
@torinfo yes - this issue relates to being able to link to a page that's hidden. I thought adding an extra check box to allow this would avoid any examples out there where people actually don't want to be able to do this and maybe by accident do have some links to hidden pages already in their projects.

It was while looking at how we could do this that I realised that links to hidden pages sometimes do do something... just not something that makes sense! I've also noticed that if you have hidden pages then relative links (first/last/next/previous) can have unexpected results. I'll look at fixing all this before adding the new functionality in!

@ronm123 feel free to change the author support styles. They are a bit over the top at the moment. In Bootstrap the text is smaller already I think

**Comment by FayCross** [comment]
Done for Bootstrap template - would be useful to add same functionality to XOT template at some point. Instead of allowing hidden pages to be linked to there's a new optional property called 'stand-alone page' which removes the page from page menu but allows it to be linked to (either opening in same or new window). I thought it made more sense to do this & keep hidden pages as always hidden in live projects

**Comment by FayCross** [comment]
Closing as this functionality is now in XOT & Bootstrap templates. I've found a few bugs while doing this work that I'll add as separate issues
