### ISSUE TITLE
New page type/functionality for saving a page and form entries as Word document

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#547]
Hi all
just adding some thoughts/comments etc re the new functionality @JohnSmith-LT has been working on.
1. @JohnSmith-LT You asked the following in an email: "I was thinking of making the structure more like that of the Hotspot page where you could have Page -> Item and also Page -> Section -> Item where the additional Section wasn't required..."

I'm not sure if this is what you mean but I think it would be useful to have everything on one page including the download button (even if that introduces scrollbars) but also perhaps the ability to split into multiple pages/sections where appropriate. e.g. Form tools like Google forms and the Feedback module in Moodle have an optional page break option so the author can choose whether it's a long scrolling page or broken into separate pages with navigation. What we have right now is close to that e.g. Section > item > item >item >item except there doesn't seem to be a way to avoid having the first page and the download option as separate pages? e.g. the following screenshot without the navigation
![image](https://cloud.githubusercontent.com/assets/5167146/18787586/5d2dffde-819b-11e6-9d22-95292eb5ff82.png)
1. I can see why you added the borders and we can obvious re-style via custom css but I wonder if the borders should be an optional property along with the usual panel size options like Small, Medium, Large, Full so that there could be variable width of the form display similar to quiz and other page types.
2. I think you already said that the input field size and required field options don't do anything at the moment but obviously author control over field width and height is desirable as is input type e.g. single line entry, paragraph entry and ultimately other form elements would be useful too e.g. checkboxes, radio buttons, select lists.
3. I wonder whether by default the resulting document styles should be all black and perhaps Arial too but with an optional property to attach a custom stylesheet or customs styles text box to control the output styles. 
4. We've already discussed an optional property to control the name of the downloaded Word doc

I'm sure there is lot's more we could add/change but just a few thoughts to start with.
Cheers
Ron

**Comment by JohnSmith-LT** [comment]
Thanks Ron, that's great and gives me something to work from. Just making notes in response to your points above, not really needing an answer to them.

1. (well the first one since Github appears to want to show 1. twice) - I think this is really two separate things

a) You are right in that I could easy have an "item" which was just some text with no input fields and then if you want an "Introduction" first page then you add it...

b) the thing with the page ->section-> item and page->item is that perhaps having a section within a page only really makes sense (or more so is only required) if you have multiple items needing grouped or that are related. e.g

Personal Info
 - Name
- Age
- etc

If you only have a single item with no related items then you just add that as an item without adding a section for it to go inside. Similar to how you can have a single hotspot or a group of hotspots - i'll add it to show what I mean and it can always be reverted.

1. (the second one) - I really only added them so I could visualise the structure. I don't like how they look so intended to remove but they could be optional as they may be desirable in some instances.

2. Yes this is the plan, text boxes are easy to make work :)

3. Yes i'm happy with that - perhaps the styling for this is something Julian's friends son may be interested in working on - it's not my strong point!!

4. Yes, already done will upload soon.

**Comment by ronm123** [comment]
Cheers John
I'll keep an eye out for updates and I have some real world uses for this so will explore the possibilities including styling etc and add further notes here in due course.

**Comment by ronm123** [comment]
@JohnSmith-LT I noticed in a further bit of testing that if an LO was set to responsive text the page, section and item titles weren't being displayed as responsive. I think this is because responsivetext.css doesn't have any reference to #pages This is resolved by adding `#pages h2 {
    font-size: 3.0vmin;
} ` to responsivetext.css but would have to be done for each theme and I wonder if there is an existing class that could be used instead e.g. #mainText? I also vaguely recall a previous comment by Fay that heading in page content should start from h3 rather than using h1 or h2 but I could be wrong about that.

In the current responsivetext.css files we have the following controlling headings but nothing else relevant: `h3 {
    font-size: 3.0vmin;
}
.panelPage h3 {
    font-size: 3.0vmin;
}
#mainTxt h3 {
    font-size: 3.0vmin;
}

#x_headerBlock h2 {
  font-size:5.0vmin;
  font-weight:bold;
}
#x_headerBlock h1 {
  font-size:2.5vmin;
}`

I guess it's not too big a deal to add `#pages h2 {
    font-size: 3.0vmin;
}` to each of the responsivetext.css files but I wonder if there's a way to avoid that? 

I know @FayCross has done some tidying up of the responsivetext functionality recently and I thing @torinfo too so they may have further comments at some point.

**Comment by JohnSmith-LT** [comment]
Hi all,

I've uploaded some more changes to this. Download doesn't work as expected just now but some extra functionality added to the page model.

NEW
- Add 6 different elements to either the page or a section (Textbox, Textarea, Checkbox, Media (pics only just now), Description (text with no input element) and Horizontal Rule
- Sizes work on some elements now
- Optional property to set filename

TO DO
- Add Radio button and Select list options
- Fix download.php to accept all new elements
- Wire up the Required option (just now it just adds an indicator)
- Look into styling (Ron's stuff above and new elements)

All comments welcome!

John

**Comment by ronm123** [comment]
HI John this is great thanks.
I've been testing with a 'real world' example and added some custom css in the LO and you can view the LO here: http://training.mitchellmedia.co.uk/xot/play.php?template_id=208 

A few comments:
1. Ideally I'd like to be able to have form elements on the very first page a user sees e.g. to hide the document title and text, rather than having to add a page and then the user has to click next before seeing any text elements.
2. Might also be useful to have an option to set that Document title and text as 'sticky' so that it appears throughout the navigation. You'll see in my example that I've added similar text to the top of each page to try to achieve this but then obviously this is repeated in the downloaded document too.
3. Seems like font formats etc applied in the editor are carried across to the word document so perhaps download.php doesn't needs the font styles/colours enforced? I think better just black by default.
4. You'll see I manually added a page count to the bottom of each page. Might be better if that was automatically part of the navigation e.g. rather than just page number between the buttons 1/2, 2/2 etc
5. Would be good to be able to configure the final page e.g. where the download button appears to add instructions/notes etc
6. I tested on iPad and via Safari the download doesn't work but does via Puffin Browser. I wonder if there's the potential for a view option in than scenario rather than download. Or of course whether there's a solution to get it to work via Safari on iPad. Then again other tools with similar download functionality don't work on iPad either.
7. It seemed like the width option isn't currently controlling text entry items so I've controlled the width in this example with custom css.
8. Did you see my previous note that to get download to work on my server and also xampp I had to change the link in documentation.html to remove the forward slash at the beginning.
Cheers
Ron

**Comment by ronm123** [comment]
@JohnSmith-LT thanks for the update re Page x of y and download.php link.
I've added that to the install I'm using for the real world example so that previous link I shared shows the change. I've enabled [download](http://training.mitchellmedia.co.uk/xot/website_code/php/scorm/export.php?scorm=false&template_id=208) of that LO too in case useful
I'm not sure about the "No answer given." being displayed by default in the downloaded Word document given that the end user is doing this and will know whether they answered or not anyway. However I guess ultimately this could/should be part of the language string options anyway and so the author could change or empty that field including the ability to change the label on the download button etc.
It also occurred to me that it might be useful to have some way for the author to mark/tag something like an instruction that is part of what is shown on the LO page itself but isn't part of the download document e.g. isn't posted to download.php or in some way hidden.
HTH
Ron

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 

I've checked off most of the things above with a few exceptions:

6) Not sure I can ever enable this although I'll continue to look around and have a think about alternative ways to do the same. I've changed headers to the format that is most compatible and should work with Android 2+

Still have to patch download.php to take into consideration all the changes and add the stuff on the TODO list above but i'm done for tonight!!

Thanks for all your feedback, it's been very helpful and we now almost have a very useable page...

John

**Comment by ronm123** [comment]
@JohnSmith-LT indeed fantastic stuff and very useful and flexible new page type!
I updated my install and example to test the changes and have also shut down for tonight but will add further notes/comments tomorrow.
Cheers
Ron

**Comment by ronm123** [comment]
Hi @JohnSmith-LT I've been testing a bit further and wondered about the following changes:

Change the page counter to remove the word page and just have x / y? e.g.
`$('#pagenumber').html(page + " / " + $('#pages').children().length)` You can see this in my test LO linked previously.

Change the navigation buttons to use FA icons? e.g.
`<a href="javascript:void(0);" id="previous" title="Previous"><i class="fa fa-chevron-circle-left fa-lg" aria-hidden="true"></i></a> <span id="pagenumber" />
		<a href="javascript:void(0);" id="next" title="Next"><i class="fa fa-chevron-circle-right fa-lg" aria-hidden="true"></a></i>`

I guess any text used will need to be internationalised at some point?

I wondered about setting the navigation to float top right as in my example?

In my test project I've added margin-bottom:10px; to #navigation and also made #navigation font-size responsive so the buttons resize along with the text as long as display width is 768 or greater. This links to my earlier question about whether there's a way to minimise the need to update each responsivetext.css?

I'm wondering what further changes you were planning re checkboxes both in terms of display but also result in the downloaded doc? e.g. displaying the text box left or right of the line of text rather than below?
In the resulting document showing symbols to represent checked or unchecked e.g. `&#9745; and &#9633;`

Just some thoughts...
HTH
Ron

**Comment by JohnSmith-LT** [comment]
Thanks Ron,

I've now incorporated your changes above and put some code in to take care of 'required' flag and incorporated some of the changes above. Still to do are (feel free to add to the list as I might have missed something):

- [ ] Fix download.php to accept all new elements
- [ ] Look at styling (both in LO and download) and maintaining responsive sizing
- [ ] Add Radio/Checkbox/Select lists
- [ ] Rip out all English strings to the language area
- [ ] Look into alternative to download for iPad use

John

**Comment by ronm123** [comment]
Cheers @JohnSmith-LT I'll download and explore the latest changes as soon as I can and add anything that's missing etc.
With regard to iPad use I wondered whether hooking into the installations mail processing (if configured) might be an option. e.g. as well as a download button an optional property email button where the user enters their own email address (or a teacher I guess) and the results send via email? Optional property so that the author can decide whether to enable vs the risk of spam etc ;-)

**Comment by JohnSmith-LT** [comment]
Thanks Ron

The email thing sounds like a possibility - would the content of the normally downloaded file just be sent in the body of the email?

Also, have been thinking about the Checked/unchecked text and the use of symbols and also the No answer given text. What do you think of having the checked / unchecked as optional properties that you could put whatever you like into, similarly with the No answer given (which could also be set blank). If those were optional properties of each textbox/textarea and checkbox would it also perhaps be desirable to have a global No answer given field...

John

**Comment by ronm123** [comment]
Hi John
quick response for now...
yes was thinking the content would just be the body of the email rather than an attachment.
Optional properties sound like a good idea and yes a global no answer option too. Perhaps the default for that should be "Not answered" Rather than"No answer given" I have a couple of other real world examples where checkboxes are required that I'll work on and share at some point tomorrow.
Added 1 item to your previous list about some way of excluding content from the download.
Cheers
Ron

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 

Sorry it's taken a while to get some time to get back to this... i've added radio/checkbox support and also an exclude option but i'm pretty sure i've broken or not completely wired up some of the functionality. 

Hopefully i'll have more time this week to work on the other items.

John

**Comment by ronm123** [comment]
Hi @JohnSmith-LT my apologies too I had to park this to get on with less interesting VLE stuff but will pull down your changes and explore asap.
Cheers
Ron

**Comment by ronm123** [comment]
@JohnSmith-LT just testing the Radio Button listed functionality with the beginnings of a real example and on preview/play I'm seeing  a line of text saying 'Enter text for the list here' but I'm not seeing a text entry box in the editor to change or clear that? screenshot of preview attached:

![image](https://cloud.githubusercontent.com/assets/5167146/19244524/8776e694-8f14-11e6-9ccc-cae60c40846c.png)

Also I assume that the option for horizontal or vertical display is not yet functional? e.g. nothing seems to change at the moment.

I think it would also be better if the 'Option Name' fields weren't bold by default and perhaps like the document title fields where the author has basic control over formatting.

The text for the options themselves should probably be default size too but again perhaps with the minimal style controls? Currently the options appear much smaller than paragraph text. 

More comments tomorrow...
Cheers
Ron

**Comment by JohnSmith-LT** [comment]
Hi Ron, thanks for catching that. I have put back the text box and renamed them and also fixed the issue regarding the lack of wysiwyg editor and forced bold on titles.

I have still to implement the horizontal/vertical option you are right and I have no styles on the option text so it must be inheriting from the base stylesheet so if you were able to figure out from where then that should be easily changed or overridden - I'm surprised though that it doesn't manifest itself in other LOs...

I'll work on the horiz/vert next...

John

**Comment by ronm123** [comment]
@JohnSmith-LT sorry since my last test I've had to park this to complete some Moodle developments but should have time to explore further tomorrow and will investigate where the styling is coming from then.
Cheers
Ron

**Comment by FayCross** [comment]
Hi John & Ron, I'm a bit late to this but I've got a bit of time I could spend on helping out with this page if it's needed - it looks great so far. I think I've read all the emails & comments about this but apologies if any of this has already been covered, here are my initial thoughts:

1. Does this page type need to have multiple sub-pages or would it be more useful to be able to add multiple documentation pages to a project (at any point, e.g. pages 1, 4 & 10) and then be able to do the download on the last one? This would allow for notes to be taken throughout the project and just one file to be made rather than multiple ones. If this were the case then it would be great if you could add 'documentation' form fields to any page type through a button in the text area's wysiwyg editor - i.e. you could take note inside a text and graphics page that would be stored as part of the document too. Then at the end of the project the data entered everywhere could all be pulled together and downloaded to a document. I realise this last bit would be quite a change from what we have so far and require a lot more work though!

2. Some of the optional properties (e.g. not answered text) should really be language properties

3. In the media lesson page there is something similar to 'horizontal rule' but it's called 'divider' instead. Rather than being an item you add to the page it's an optional property on each type of content you can add and when added it inserts a hr between it and the content above it. I'd prefer this to be consistent across the pages as it does the same thing.

4. Some of the wording of things might not make sense to non-technical users (e.g. width of text areas is columns rather than width)

5. An option to have default text in text areas/fields could be useful (the grey text that prompts you what info to type in but disappears when you start typing)

6. Page layout - option to layout in grid with title next to form field rather than in long list:
<table><tr><td>Q1</td><td>text field here</td></tr><tr><td>Q2</td><td>text field here</td></tr><tr><td>Q3</td><td>text field here</td></tr></table>

7. I'm not sure what I think of the sections. I understand why they are useful but I think it's a little confusing that they appear in the same '+ New...' list as the rest of the content and then when you add one you see the same list of '+ New...' content items twice. I might be overthinking this though. There's something similar in the stand alone decision tree template but I made it so that questions had to be added within a section but you choose whether to show the section info or not. Maybe that's more confusing though!

8. Is the checkbox item needed when you can create one using the list item?

John, are you happy for me to make some small changes here and there (e.g. 2,4,5 above) or is that going to get in the way of the work you're still doing? I can look into the responsive text stuff mentioned above too.

**Comment by ronm123** [comment]
Hi Fay

1.       Re multiple sub pages – I think it’s very useful to be able to do what we can now with multiple sub pages so wouldn’t want to lose that but yes like the model answer and model answer results combination the ability to add not just text boxes but other form elements throughout with collated results at the end would also be useful. I think probably the best idea would be to treat the two things separately but use the common functionality where possible.

2.       Re language properties – do you mean instead of optional properties like some of them are now? Problem is users often miss the language options even more than the optional properties.

3.       Sounds like a good idea to make consistent but debatable whether divider or horizontal rule is a better description.

4.       I did wonder about that but figured John had a reason for calling it columns

5.       Yes as an option somehow agree

6.       Yes this would be useful especially with radio buttons and checkboxes but also short answer fields too

7.       Perhaps this ties in with your question about help icons alongside optional properties but also perhaps anywhere a bit like Moodle help icons that provide contextualised guidance

8.       I guess there could be reasons for separate options rather than combined but not thinking clearly about that at the moment. :(

 

HTH

Ron

**Comment by FayCross** [comment]
Hi Ron

2. Yes language property rather than optional property. I know that most people don't know they're there but I'd still prefer them to be in there for consistency. Otherwise we might as well just get rid of language section all together

3. I don't mind whether it's this page or media lesson page that's changed to make it consistent. I just wanted to make a note of this so I could sort it later.

I don't want to tread on John's toes with any of this so I'll probably just do a bit of work on layout / css / responsiveness for now.

**Comment by JohnSmith-LT** [comment]
Hi Fay,

Your suggestions look great and there is no problem with stepping on my toes, feel free to change anything you wish to make it more consistent with the look and feel of the other pages. I probably won't have any time to work on this over the next few weeks as I have to go with my wife to Leeds as she's having an op so there will be no code conflicts to worry about and if you have the time then it would be good to see what you can come up with. Just a few notes to add to what you and Ron have already added:

1. I think being able to add to the documentation throughout the LO as well as having a page like we have now is great... perhaps another item on the documentation page which simply has an option to reference the text entered on another page, or some kind of templating system as that would allow you to add a Name: box on page 1 and then have a "Thank you {{name}}" on the documentation page... I agree with Ron though that I can see a use for both...

2. Yes, agree but i'm just not always 100% sure when it goes in there and when not...

3. I don't have an opinion either way about this; if divider is the more consistent terminology then i'm happy for it to be that. On't caveat is that the reason it's not an option but an item is because you have the exclude option which can determine whether it shows on the LO, the documentation or both. It also makes it easier I feel to know where it is in the grand scheme of the layout and also easier to move around...

4. Again, i'm all for consistency but I think the confusing thing for me is that textboxes it's pixel width but textareas it's columns so width: 50 isn't the same in both cases... or am I wrong?

5. I like this idea too.

6. Sure I can see it being used and the more flexible the layout the better.

7. Happy for them to be removed I just liked the way you could group things so you could have defined sections like you might in an application form...

8. The checkbox was the original but I felt that i didn't want seperate checkbox, radio and select lists (not implemented yet) as occasionally I have seen cases where you think you only want the user to select one thing but then it becomes more than one, like how did you get here - they may have driven to the station, got the train and cycled from the station to work...  As for a separate checkbox, like you I don't think there is any need but i've been taking Ron's lead on most of this and he may have a specific use case...

I still really need to work on the download section and email functionality (for ipads) so if I have time then I will work on that which won't interfere with anything you decide to do on the page model.

John

**Comment by FayCross** [comment]
Great, I'll do some bits and pieces but won't make any major changes to the way it's structured or works. I hope the next few weeks go ok for you

**Comment by JohnSmith-LT** [comment]
Cheers Fay, i'm sure all will be fine.

If you are doing anything with the model code then you might notice that the event handling looks a bit weird with self executing functions all over the place, like this

```
(function (p, s, i, d) {
	$input.on('change', function () {
		documentation.updateData(p, s, i, $(this).val());
	})
})(page, section, item, display);
```

This is because the page, section, item etc values are needed in each of the event handlers but obviously change in the loop. Rather than have 4 secondary var declarations for each i've used a closure to store the passed in values until they are used.

**Comment by torinfo** [comment]
Hi, I see that the html is using download2.php to download the filled in form, but I don't have a download2.php in my (up to date) develop in stallation. What am I missing?

**Comment by JohnSmith-LT** [comment]
Sorry, should just be download.php... download2.php was being used for testing out the email functionality which i've not been able to get working yet.

**Comment by FayCross** [comment]
I've made quite a few changes to this page in the last few days. I think it's nearly in an ok state to release (although not sure what else John has planned to add)

From my initial comments I haven't haven't done anything to allow multiple documentation pages to be combined in 1 downloaded file or added a grid layout option but I'd like to do these at some point.

A few things I wondered about:

1. Required field isn't on list - should it be? I guess this would mean it would count as unanswered if set to checkbox and no boxes where checked
2. Do you think the format of the sub page buttons & 1/5 text look confusing as it's a similar format to main page buttons?
3. Is 'List' & 'Description' the best wording for these sections? Would 'Multiple Choice Question' & 'Text' be better?
4. Is there any need for Media to be a separate section? Could we just put a media optional property in Description instead? (Same with checkbox being separate to list too)
5. In downloaded document should we include:
	- list of options that weren't selected in radio / check box questions
	- horizontal rules
	- images (not sure if possible)
	- line breaks are lost from text entered in text area fields

I've just realised too that the exclude from properties seem to be breaking the page when added - this is probably something I've done so I'll fix this asap. Oh, and I haven't checked the required stuff so I'll test that now too

**Comment by FayCross** [comment]
I'm trying to put this page on the UoN installation but am having a problem with the downloaded file - it's always completely blank. The documentation.html & download.php files are identical to those on my xampp install where it's working perfectly so I'm confused about what's going wrong.

It seems to be a problem with the data received by download.php. I can see that what's posted to it from documentation.html is exactly the same on UoN & xampp but then if I echo $_POST['data'] on the UoN install in download.php it's all like this with escaped quotes:

`{\"filename\":\"documentation\",\"pages\":[{\"pageName\":\"Nested Page\",\"pageText\":\"...`

in xampp it looks like this:

`{"filename":"documentation","pages":[{"pageName":"Nested Page","pageText":"...`

Any ideas why this would be different on the 2 installs when the files are identical?

**Comment by JohnSmith-LT** [comment]
Hi Fay,

Do you have magic_quotes enabled on the server? You may have to look at doing something mentioned here ( http://php.net/manual/en/security.magicquotes.disabling.php ) to take care of installations that have magic_quotes on.

John

**Comment by ronm123** [comment]
@FayCross @JohnSmith-LT 
just checked my server where I have this working and magic_quotes is off.
Checked php info on another server with a later php and magic_quotes isn't even listed. Was it deprecated from a particular version onwards?

Hope all is well with you John.

**Comment by FayCross** [comment]
Thanks @ronm123 & @JohnSmith-LT - I've turned magic quotes off by this to the .htaccess file (suggested by John's link):
`php_flag magic_quotes_gpc Off`
and it works now. I take it there's nothing that relies on magic quotes being on that I should be worried about not working properly now? If not then you can start your work on moving your documentation projects onto the UoN install Ron.

**Comment by JohnSmith-LT** [comment]
Have all aspects of this now been completed @ronm123?

**Comment by ronm123** [comment]
@JohnSmith-LT I think so apart from the emailing option.

**Comment by FayCross** [comment]
Closing as documentation page was completed some time ago
