### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#563]
Some words in the glossary can be the same but have a different meaning. For example 'due' and 'due date'
That does not work in the glossary. So where due date is in the text it will take the explanation of due and not from due date.

**Comment by JohnSmith-LT** [comment]
Hi Inge,

I've just tried this with due and due date and the latest version of develop seems to work ok for 'due' and due date - what version are you using?

![image](https://cloud.githubusercontent.com/assets/3907362/22781781/0ca37df8-eebc-11e6-8506-a624f54771c0.png)

See due marked and also due date has been marked correctly...

**Comment by JohnSmith-LT** [comment]
It seems @FayCross fixed this 2 years ago - https://github.com/thexerteproject/xerteonlinetoolkits/commit/04340a6520c773ce7e2e2e5d0df6bd855d349f3e - so perhaps the xenith.js file you have on your installation is not right or the one that has gone into one of the releases?

**Comment by FayCross** [comment]
@JohnSmith-LT I think there is a bug. It works ok if the shorter word is 1st in the text but if due date is first then only due will be highlighted in it. I haven't had a chance to look at a fix yet though.

**Comment by JohnSmith-LT** [comment]
Ah, never thought to try that... interesting one...

**Comment by JohnSmith-LT** [comment]
Hi @ingedonke and @FayCross 

I've added a quick fix to iterate through the glossary terms in reverse since the longer of two similar terms (such as 'due' and 'due date') will always appear after the shorter one but should be replaced first...

This will work for the example Inge mentions above but may not where we have terms like ('due' and 'date due'). To do this we may have to iterate through the entire glossary list keeping track of the longest match and use that.
