### ISSUE TITLE
Uppercase User name issues when creating new projects

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#570]
When you log in with your username in capitals you can't create new projects properly.
A folder is created in user files folder but it doesn't contain the required xml files

Does anyone who knows this side of the code better than me point me in the direction of the files that look at login so I can force to lowercase?

Thanks

**Comment by torinfo** [comment]
I'll have a look and let you know. But just curious. Does that mean your login name is not case sensitive?

**Comment by ronm123** [comment]
I thought this was something Tom fixed ages ago but have also had this reported after a recent upgrade. Wondering if a previous change has been lost in the latest release?
Was this a new user Fay or a user who has created projects previously?

**Comment by FayCross** [comment]
No they're not! We can log in fine (edit, duplicate etc.) but it causes issues with new projects being created

**Comment by FayCross** [comment]
@ronm123 everyone as far as I know. Certainly causes problems for me

**Comment by ronm123** [comment]
I think it might only happen with LDAP authentication. e.g. with database authentication both login and password are case sensitive.

**Comment by ronm123** [comment]
The only times I've seen this is with LDAP authentication and where some projects have had uppercase username (usually a mix of letters and numbers) and others for the same user lowercase letter but otherwise the same username.

**Comment by JohnSmith-LT** [comment]
Similar to #411

**Comment by torinfo** [comment]
There is debugging code (including the paths names that are actually used by the system). 

You may want to consider setting develop to true. 

The username is used as entered. 

1. While creating the template, the username comes directly from the login ($_SESSION['toolkits_logon_username']), so there might be some manipulation going on in the authentication module, but I haven't found it.
2. While playing/previewing the username is retrieved from the database

Any difference between the two?

The actual copying of the files is done in modules/xerte/new_template.php

**Comment by ronm123** [comment]
I just tested this as follows:
Logged in to an installation that uses LDAP authentication using my usual login which is all lowercase and can edit and create projects as usual.
Logged out and then logged in again but this time all caps username. Login works and I can see and edit existing projects but if I create a new project the editor opens but without any tree/icons and in the user-files the folder created has uppercase username whereas all existing projects have lowercase username. This obviously replicates what Fay has reported.
As I mentioned yesterday DB authentication only allows case sensitive login and I guess because it has to match exactly what is used when the db account is created so if that were uppercase, lowercase or a mix when originally created the login would only work if matched.
Clearly this isn't the case with ldap authentication at the moment and this is anecdotal and possibly coincidental but whenever this has been reported 9 times out of 10 it has involved a Mac user. I've often wondered if the problem only usually materialises when a user logs in with a different computer/platform where perhaps caps lock is the default or the username isn't saved and so more likely to vary by how it's typed. Or perhaps varies between initial account creation and subsequent login.

Sounds to me that there may not be string manipulation in the ldap login/account creation but perhaps that there should be and forcing to lowercase?

**Comment by torinfo** [comment]
Hmmm. So, the username in all caps is the same username as in your first 
trial (i.e. the username is not case senstive in ldap)?

If so, would you mind switching on develop to tru and send me the log 
file from logging in and creating a new LO? That will give me some hints 
on how to fix this.

Op 17-2-2017 om 12:08 schreef Ron Mitchell:

**Comment by ronm123** [comment]
@torinfo I can do that but will have to do it on a test installation which I have to remote into so will schedule to do that later if that's ok. Once done I'll send you details offline.

**Comment by FayCross** [comment]
Closing as this seems to now work ok with (ldap) usernames in upper or lower case
