### ISSUE TITLE
difference between titles/labels that display and those that don't

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#578]
just adding this as a question/enhancement but I've noticed previously and certainly while delivering training this week that people get confused about what title/label fields show during play and what title fields only show in the tree. Wondering if we could/should indicate this somehow e.g. where tree only show to the left of the field as: Title (tree only) or perhaps an icon to indicate this?

**Comment by FayCross** [comment]
This has been discussed before as I was taking fields like this out and Tom was adding them in!
https://github.com/thexerteproject/xerteonlinetoolkits/issues/526

I still feel like there should be a better way of doing it rather than typing in text that's not used in the project (use text from another field as tree label?) but I am not deleting them anymore! Perhaps indicating fields like this would be useful but I'm not sure how - would most people know what 'tree' referred to?

**Comment by FayCross** [comment]
Tooltips added to all label fields where their purpose isn't immediately obvious. Most of these have been given one of the following tooltips:

- The label is used to identify this question on the results page and when tracking results, e.g. via xAPI
- The label only appears in the editor's project structure panel and is not shown in the project itself. Unique and meaningful labels can be used to make questions easier to locate for editing at a later date.

@ronm123 @tom7c1 I can tweak the wording of these if you have ideas for something clearer
