### ISSUE TITLE
Add chapters to the menu or to the content

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#58]
Question from two universities in the Netherlands. 
For example that the menu collaps when you click on it.

**Comment by thexerteproject** [comment]
Not a high priority for me: the software should encourage lots of small LOs linked to from, say, a bootstrap page, rather than large LOs, though I appreciate it there are possible use cases that justify it.

**Comment by FayCross** [comment]
@ronm123 @torinfo @ingedonke This is something that I will be developing in my new role. There will be a new optional property on every page that will mark it as the beginning of a new chapter & allow you to set the chapter title. Table of contents will show chapter titles and chapters can be expanded to show the pages within them. There will also be the option to show the table of contents on the sidebar instead of in a dialog or lightbox. Let me know if you have any concerns about this (can discuss on dev day)

**Comment by ingedonke** [comment]
Cool!!!
