### ISSUE TITLE
QR Code page in all versions now broken - displays blank page.

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#615]
Hi all
not sure if anyone else has noticed this so not sure how long it's been broken but it looks splashurl.net no longer exists so the code to add the image fails and displays any qr code page totally blank.
The shorturl bit still works but doesn't show because the image load is obviously failing.

**Comment by ronm123** [comment]
Is LGPL licence ok to use? If so perhaps we can use http://phpqrcode.sourceforge.net/ ?

**Comment by ronm123** [comment]
Alternatively this site http://qrickit.com/qrickit_apps/qrickit_api.php seems similar to what we were using but would obviously be better not to link off to an external site if can implement our own version.

**Comment by torinfo** [comment]
I would prefer javascript generation:

https://davidshimjs.github.io/qrcodejs/

MIT license.

**Comment by ronm123** [comment]
I only did a quick search - supposed to be doing something else - but yes looks good!

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 when you get a chance can you check that this now works for you...

**Comment by ronm123** [comment]
Hi @JohnSmith-LT yes the QR code is displaying now. However the short url isn't. I think we used to call is.gd for that and that site is still working e.g. https://is.gd/apishorteningreference.php Or is there a better way to do that too?
Cheers
Ron

**Comment by JohnSmith-LT** [comment]
Hi Ron,

I think this must again be down to some cross-domain shenanigans as it works fine here on localhost...

![image](https://cloud.githubusercontent.com/assets/3907362/24494557/999d2d8c-152a-11e7-957d-5b9221c7561d.png)

Do you get any console errors or network codes in the network tab?

John

**Comment by ronm123** [comment]
@JohnSmith-LT no errors in the Chrome console. A few advisory's in the Firefox console but I don't think they are relevant:
![image](https://cloud.githubusercontent.com/assets/5167146/24496026/0816e880-152f-11e7-9bb9-2f7774dd21cd.png)
I'm testing via xampp/develop but also I think I updated an online install with the latest develop last night so what do you get viewing this quick test: http://learningapps.co.uk/futureteacher/play_7

**Comment by JohnSmith-LT** [comment]
The problem seems to be that your rss_proxy.php is not returning the code...

If I do this on my server

/rss_proxy.php?rss=https://is.gd/api.php?longurl=http%3A%2F%2Fwww.google.com&_=1490865480290

Then I get back the correct short code

whereas if I run the same on your server then it gives an empty return...

I'm not sure whether your domain or ip is being blocked by is.gd or not but you say this also happens on xampp/localhost? I have a local url setup so it could be that http://localhost/ as a referrer is also being blocked. We can't get around this though as I'm sure I contacted them before and they do block localhost.

Can @FayCross @thexerteproject (Julian) or @torinfo reproduce this?

**Comment by torinfo** [comment]
Hmm. Regardless whether we can reproduce this or not, this code is not working when the LO has been exported, because obviously rss_proxy.php is not available. We should be able to do an javascript call to is.gd directly shouldn't we? Or do we get issues with cross domain calls in that case? (I suppose it depends on the setup of is.gd)

**Comment by JohnSmith-LT** [comment]
Yeah there are numerous cross domain issues with it and it has never worked offline as far as I can see....

This could perhaps be better handled in the editor anyway? Could we create a short_url input type which takes a url and changes it in the editor to a short one... but then that would lose the long one in the editor unless we retain both?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 I've changed the code to use the is.gd service directly. Can you test if this works on your install? And on http://localhost/ and offline if possible?

We may have to implement multiple options to cover all occasions...

**Comment by torinfo** [comment]
This seems to work fine on my localhost xampp. Will try in a minute on my Linux install.

However, url is hardcoded to www.xerte.org.uk. I don't think that was the intention. ;-)

**Comment by JohnSmith-LT** [comment]
Oops... not had enough coffee this morning - that's it fixed...

**Comment by torinfo** [comment]
Works fine on my Linux server as well

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo sorry been in an online meeting until now but have just updated my xampp install and online install and both working now e.g. short url as well as qr code displaying correctly.
Cheers
Ron
