### ISSUE TITLE
Script not executed if you enter the page for the second time

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#629]
I added a script to a page through the optional script parameter. (In this case some code in a historical page where the optional navigation button option is set to none, and then want to enable home button again).

```javascript
setTimeout(function(){

  $("#x_menuBtn").button( "option", "disabled", false );

}, 100);
```

The first time the page is visited, this works fine. The second time the page is visted (during the same session) the script is not called. Is that a feature or a bug?

**Comment by ronm123** [comment]
I've never noticed this before but in testing your example I can replicate and even if you do something as simple as `alert("test");` in an optional script property it only works the first time viewing that page regardless of navigation settings.
e.g. I added 3 plain text pages with a script box added to each and first tried your code but then tried with a simple alert on each page. The alert fires on the first visit to each page but not when then navigating back and forth between those already visited pages.
I can't help wondering whether that's always been the case or whether it's a change but either way it seems like a bug! Although I can see why you ask whether it's a feature or bug because perhaps in some cases it's desirable to only run once? If that's the case then if there is a solution to enable running on each visit there should also be an option to prevent that either for the whole LO or specific pages.

**Comment by FayCross** [comment]
I'm not sure whether to call it a feature or bug but it's definitely always been like this. It should be easy enough to allow the code to run on every page view though. Shall I just add a 'Run script on every page view' checkbox as Ron suggests?

**Comment by ronm123** [comment]
Sounds like a good plan to me!
Does the same apply to the Bootstrap script option?

**Comment by torinfo** [comment]
Yes please. Also, would like to have a patch, to change a pecific installation. Can you please let me know where in the code I should do this?

Or, if you add the flag I can see for myself in your changes.

**Comment by FayCross** [comment]
Ok, I should be able to have a look this afternoon. I'm not sure if it is the same in bootstrap, I don't think I added the script option to that so aren't sure how it's set up. I'll have a look.

**Comment by FayCross** [comment]
Hmm, not sure this is the best solution actually. It's fine for things like alerts but if the script contains things like listeners for click events they end up being triggered multiple times for each click on later page views.

Would we be better off having two separate script boxes - one for 1st load & one for subsequent page views? Or is this overkill?

**Comment by FayCross** [comment]
I've just checked Bootstrap & it does re-execute code on page change but like the change I've just made it also means events are triggered twice

**Comment by ronm123** [comment]
@FayCross can see what you mean that two separate script boxes for each page would be overkill but also that if the toggle means all script in a box always re-runs then that might not be desirable either - especially given that we haven't had that so far so could be an impact on existing LO's if script always re-runs by default. Is there a way of achieving both options within a single box e.g. some script only runs once and other script always re-runs?

**Comment by FayCross** [comment]
I think the only way we could do that is if we set up a function in there by default & prompted the authors to put the code they want to run on every view inside it. I'm not sure this is ideal either!
