### ISSUE TITLE
Various issues with tree icons (hidden page, deprecated, don't mark for completion)

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#639]
- Add new page, add hide or unmark optional property & check box... the icon doesn't appear in tree (this is only an issue for newly created pages - adding a hide page or unmark on existing pages works fine)

- Add hide or unmark optional property to an existing page & check box. Then copy the page... the icons on the page you copied & newly created page disappear & won't reappear even with unchecking / checking box (this is only an issue for pages where optional properties have only just been added - if you add property, check box, refresh webpage & then copy the page, the icons show as expected)

- When copying a page where the icons are already on tree (so add property, check box, refresh webpage, copy page), checking / unchecking the box or deleting the property on the newly created page will not will not add / removed icon on page... it's stuck there until page refresh. The icon for page that was copied remains working ok though.

Hidden icon:

- There's an error when you try to delete the 'hide page' optional property that prevents it from being removed

**Comment by torinfo** [comment]
Ah....

Whe a new node is created in the tree, the icons should be there as well, and should be hidden by default. That's not the case now.

I'll fix that. That should probably fix the first 3 items.

I'll investigate the last item.

**Comment by ronm123** [comment]
@faycross I'm offline at the moment but hadn't noticed any of this so will test and report back asap

**Comment by FayCross** [comment]
I think the last item is just because of a typo in the code (hiddenImg instead of hiddenIcon) but I'll leave it to you to sort @torinfo if you're looking at the rest of it :)

**Comment by torinfo** [comment]
Hi Fay, yes, found and fixed the typo.

This is no fun at all..... 

When you change things directly on the treenode using jquery and ID's, this is not replicated when you request the node using jstree. 

Ok, no problem I thought. Just make sure to update the jstreenode as soon as you change something, but that doesn't work either, because it does some special things with the <i> tag, and so all the icones are multiplied!

Sigh. So I will fix it, but it will take a bit longer.
