### ISSUE TITLE
Error when installing on xampp

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#699]
I've done a fresh install of Xerte on a laptop today & got this error when trying to use the develop code:
'Failed to execute query line 89 page2.php'. I think it's at the point that the database is setup.

I downloaded the 3.5 release from the website and this installed fine without this error so I guess there's something reasonably recent in the develop code that's stopping it working.

**Comment by jayaich** [comment]
I haven't changed page2, but the code in that area is using the file 'setup/basic.sql'. That file has only had one recent change since last year, and that was by me.
I modified that file to add in one new field to the 'sitedetails' table (see commit 8b69e7ca371e64a0e5924c36a86a1dfc256ac241). It's a one-line change, and I cannot see anything wrong with it.
You could check the database to see if the table exists. If it does, then it's not the above commit causing the problem. If it doesn't exist, then you could modify 'basic.sql' to remove line 94 which defines the 'enable_mime_check' field, and try installing again.

**Comment by jayaich** [comment]
Just sent pull request #700 to fix the problem.

**Comment by FayCross** [comment]
Thanks @jayaich
