### ISSUE TITLE
Exporting the offline zip it doesn't export the models_html5 folder

### ISSUE THREAD

**Issue by danieledivito** [thexerteproject/xerteonlinetoolkits#710]
Hi in 3.5 version exporting the offline zip there is no models_html5 folder, so it create many issues when checking activities. a workaround can be made adding manually the folder that can be found in other type of export zip

Another trouble is the following:
XMLHttpRequest cannot load file:///home/daniele/exported/media/matematica8.jpg. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
send @ jquery-1.9.1.min.js:5

obviously an offline package should access media, but here we have a trouble when accessing media files using the file protocolon an ajax call,  it is for security reasons that it is not allowed

**Comment by JohnSmith-LT** [comment]
Hi Daniel

The offline package is slightly different from the rest and the html5 models are converted and placed in the /offline folder - the models_html5 folder that is exported by the other methods should not be required. Can you tell us what specific "issues" you are having so that we can try to investigate and fix them?

Secondly, it looks like the XMLHttpRequest issue that you are having is because it is trying to access a file outside the folder that the offline export is in or that the actual LO when created had an incorrect "local" URL entered instead of uploading the file to XOT before export.

John
