### ISSUE TITLE
Navbar background colour option when added results in error and broken display

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#748]
@FayCross @torinfo I'm pretty sure this is a new bug but I can't spot when/how it has crept in...
Steps to reproduce:
In bootstrap add the navbar optional property
Change navbar to below header then play - all ok
Add text colour and text hover colour values then play - all ok
Try adding a background colour value then play - display is broken with the following error:

`application.js?versionunstable - installed from github:451 Uncaught ReferenceError: bgImg is not defined
    at setup (application.js?versionunstable - installed from github:451)
    at Object.success (application.js?versionunstable - installed from github:167)
    at k (jquery.js?versionunstable - installed from github:2)
    at Object.fireWith [as resolveWith] (jquery.js?versionunstable - installed from github:2)
    at y (jquery.js?versionunstable - installed from github:2)
    at XMLHttpRequest.d (jquery.js?versionunstable - installed from github:2)` 

I'll try and find when and why the change was made that is causing this but you might recognise it?

**Comment by JohnSmith-LT** [comment]
Hi Ron,

Seems that this probably hasn't worked since November as this line was removed then https://github.com/thexerteproject/xerteonlinetoolkits/commit/50dd3938d27178e392a02a8f75650b3773aa43f1#diff-7797d033f2485bbd93d50e4ae3b0302cL324 which declares the variable. As for as I can see this use of 

bgImg + '-moz-linear-gradient etc

isn't really needed or desirable as the CSS tag would just be -moz-linear-gradient without any prefix anyway but i'm not sure if i'm overlooking something more complicated that @FayCross was trying to do.

Could just add the line bgImg = '' back in before this block but perhaps this block has changed sufficiently that the references to this no longer decalred variable need to be removed...

**Comment by FayCross** [comment]
Hmm, I'll look at this. I can remember it was annoyingly complicated to get the default css, theme css and user defined css / optional properties to all work together nicely when I added the new optional properties. It looks like I must have inadvertently removed something that made the navigation bar section work though (the similar header & footer opt props still seem to work)

**Comment by JohnSmith-LT** [comment]
Sorry @FayCross for giving you more work! I would have added the apparently missing var in myself but just don't fully understand what that code originally did...

**Comment by FayCross** [comment]
No, that's fine. It's confusing & I can't quite work out what I was doing either!
