### ISSUE TITLE
Add lightbox code to each project template and make option available wherever relevant

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#758]
As discussed we should include the featherlight.js code in each of the projects and include an option in the editor and page types wherever relevant e.g. 

- [x] add to Target dropdown in editor links menu
- [ ] add to options seen when selecting iframe button in editor
- [ ] add as option on embed content page
- [x] add as option on hyperlinks page
- [x] add as option on multiple perspectives
- [ ] add as option on video page
- [x] add as option on new window page
- [ ] add as option on thumbnail viewer
- [x] add as option hotspot image connector

**Comment by JohnSmith-LT** [comment]
Hi @ronm123, found this while looking through the issues - I had no idea it was this old!

Anyway, I think we've now addressed the first item but is the second item still required and what would the options look like?

Also, what would the option be on the other pages and what would the functionality do?

**Comment by FayCross** [comment]
Closing as although there are other items in list, they are all things that can be done in other ways so no longer needed:

- add to options seen when selecting iframe button in editor: can add normal link and set target to open website in lightbox
- add as option on embed content page - use new window page instead, or use link with lightbox as target
- add as option on video page - to have video open in lightbox rather than embedded, use new window page, set open in to lightbox and add embed code to HTML optional property
- add as option on thumbnail viewer - can use multiple perspectives (set to grid) instead
