### ISSUE TITLE
End-user created variables

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#780]
From Forum: 
I'm not sure that I phrased this correctly, but I was wondering whether it would be possible to use a variable throughout a Xerte LO, for example, if you ask the participant to input their name at the beginning, you could use that throughout to personalise it. There could be other variables, but this is the one that I would probably use most.

[https://xerte.org.uk/index.php?option=com_kunena&view=topic&layout=reply&catid=13&id=1518&mesid=5162&Itemid=759&lang=en](url)

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

Not sure if you've put any thought into this or come up with a solution yet? Perhaps something like:

Please enter your name: [=name]
Hello [name] and welcome to...

[=name] could just be replaced by:

Textbox SubmitButton

When you press the SubmitButton it replaces the variable 'name' with the entered value or creates a new variable called 'name' and also replaces the textbox and button with the newly entered name?

We could also use a default name Guest/Visitor/Anonymous and if that is the value of 'name' then it shows the box & button, if not then it shows the entered name so that it more gracefully handles returning to that page. If a new name is required to be entered then the LO could/should be refreshed?

Do you like the sound of any of that?

**Comment by FayCross** [comment]
@JohnSmith-LT I like your suggested syntax of [=name] It should be pretty simple to implement that I would have thought. I think it's best to have the default values in the variables table rather than us assume what they might be.

**Comment by FayCross** [comment]
We could also have mark up for the submit button so if there were several text fields on the page you wouldn't end up with several buttons. e.g.

> Name: [=name]
Age:[=age]
[+submit]
