### ISSUE TITLE
Variables - option to allow decimals to be shown with comma

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#785]
Requested on the forum: [https://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=3&id=1538&Itemid=759&lang=en#5233](url)

Allow decimal points in variables to be displayed as decimal commas instead

**Comment by JohnSmith-LT** [comment]
Hi @FayCross, can you take a look at this commit when you get a moment and make sure it doesn't interfere with anything you are doing with variables or otherwise?

I was going to do something based on language/internationalisation but I thought there may be times when someone in Europe wants to use English but display the numbers in a more recognisable format to them.

Obviously there are many more places where this could/should? be adopted and perhaps it should be refactored into a function but at least for now it seems (in my basic testing) address the forum request.

**Comment by JohnSmith-LT** [comment]
I did contemplate this too but thought it much simpler that end user display was 0,5 even though internally and creator side stayed 0.5

We could adopt a similar style to csv file parsing where 1,2,3 becomes 3 items and 1,"2,3,4",5 also becomes 3 items... it would complicate the code but is certainly doable...

Only thing is "1,2" might be a list or a decimal and processing would introduce another step and have to go from comma -> dot -> calculation -> comma

It is all doable though i suppose...
