### ISSUE TITLE
Opinion page - print graph

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#789]
Add option to print off graph produced at the end of the opinion page. Requested on Community Forum:

[https://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=12&id=1550&Itemid=759&lang=en#5319](url)

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

How complex do you envisage this to become? Do you think this just needs a printer icon and a call to window.print(); and let the browser handle printing or do you think it requires rewriting into a new popup with a print stylesheet to remove the unnecessary and improve layout first? Or would creating a PDF (if easily implemented) so that it can be saved or printed?

**Comment by ronm123** [comment]
@JohnSmith-LT try the bottom of the 3.6 release notes page https://xot.xerte.org.uk/play.php?template_id=81#page4section21

**Comment by FayCross** [comment]
@JohnSmith-LT I think priniting off just the graph would be particulartly useful. Although a button just to call window.print() would be ok as a quick way if it's time consuming to implement

**Comment by JohnSmith-LT** [comment]
Was going to look at clearing this issue @ronm123 but the Opinion page seems to have been turned off on the v3.6 release notes - is this on purpose or accidental?

https://xot.xerte.org.uk/play.php?template_id=81#v3.6

**Comment by ronm123** [comment]
@JohnSmith-LT just had a look and have made a change so it's showing again now. This was because previously an LO could be shared via it's xAPI link but still private under access, however I think @torinfo changed that so projects shared via xAPI but not LTI have to also be public. I think that's correct and the embedded opinion was still private so I changed it to public.

**Comment by JohnSmith-LT** [comment]
Is this Print button useful as is or does it need some Optional properties to control:

- Whether print is allowed?
- A field to allow the title at the top to be configured
- Selection of what html sections to include in the printout - at present we have #textHolder, #qNo and #diagram

Looking for any more suggestions @FayCross @ronm123 @torinfo

**Comment by FayCross** [comment]
@JohnSmith-LT yes - there should be a way to turn print on/off.

Options to specify what text should be included would be useful but I think by default it should be page name, instruction text, feedback & graph. At the moment, the feedback's not included but the completion language string (you have completed the questionnaire) text is.

**Comment by FayCross** [comment]
@JohnSmith-LT there is a bug with print button. If you have the default layout (1 question per page) then the print button appear as soon as you submit the 1st answer. It should only show when graph is drawn.

**Comment by torinfo** [comment]
@JohnSmith-LT @ronm123 @FayCross I am in the process of merging all my/our work into develop and this is an interesting one, as I implemented this the same way it w3as implemented inthe Results page and the adaptiveContent page by using html2pdf.

Attached are the results of both methods. I think it would be best to try to standardize on one method. Agreed? So which one to use. I like the headers in your print better, and I could add those as well.

[Opinion_html2pdf.pdf](https://github.com/thexerteproject/xerteonlinetoolkits/files/8861712/Opinion_html2pdf.pdf)
[Opinion_printThis.pdf](https://github.com/thexerteproject/xerteonlinetoolkits/files/8861713/Opinion_printThis.pdf)
