### ISSUE TITLE
greyscale issue with IE

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#812]
Hi all
I've just been doing some testing of an issue that cropped up recently that appears to be IE specific. I'm not sure if it's new and due to a change or has been there for a while but not picked up because it requires specific circumstances. However I can replicate with latest develop...

1. Create an LO and add a title page and plain text page.
2. Add a background image to the title page, make public and view in different browsers including IE - all good so far!
3. Apply the Greyscale property to the background image by ticking that option and view again in different browsers including IE. What you will find if you get the same as me is that in most browsers all is well but in IE the greyscale image loads but the header and footer and navigation buttons do not load?
4. If you add a plain text page before the title page and refresh in IE the LO then loads but upon navigation to the Title page containing the background image set to greyscale the navigation buttons now stop working. Untick the greyscale option and all is fine.

I've just been have a quick look at the xenith code and there is reference to the greyscale code working differently in IE and needing pageBg ID but I'm not sure if this is something that has changed or always been there. @JohnSmith-LT do you recognise this? Can you replicate?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 I don't remember whether I did that or whether it was @FayCross but in any case I can't test until perhaps later as I use a Mac at work. Sounds like there must be an error and some of the javascript is ending before getting to the bit that loads the buttons.

Do you see any errors in the console? If I was to guess then i'd say there would be one in the section lines 2256-2263 where a method is being called but doesn't exist...

**Comment by ronm123** [comment]
@JohnSmith-LT no I'm not seeing any relevant errors in the console. What I have since tested is that the same thing happens if the background image is added and set to greyscale at LO lcon level rather than just title page level. 

If I comment out 2257 e.g. //$pageBg.gray(); then the title page loads complete with navigation but obviously the image isn't turned grey.

**Comment by torinfo** [comment]
Strange indeed.

No errors, but navigation doesn't work. Even stranger, hover doesn't even cahnge the colour on the navigation buttons.

If you inspect the navigation buttons, you end up on the svg filter, so the filter is over the buttons. You can also see that the svg has a height of 100%. If you toggle that off, everything seems to work fine again, and the image is still gray.

**Comment by JohnSmith-LT** [comment]
Hi. It is a strange one.

Seems to be a timing issue. @ronm123 can you try changing 2257 to 

`setTimeout(function(){$pageBg.gray();}, 25);`

and see if that resolves things for you? I'm still unsure why it stops the other parts loading though without giving any errors etc...

**Comment by ronm123** [comment]
@JohnSmith-LT are you saying that setTimeout addition resolves the issue for you and without the newer plugin? It doesn't for me but I haven't tried the newer plugin.

**Comment by torinfo** [comment]
@ronm123 @JohnSmith-LT I can fix it using CSS, See my last comment. Not much time today, but I'll try to fix it later today.

**Comment by JohnSmith-LT** [comment]
Yes @ronm123 it fixes it for me with the delay in and reverts when I take the delay out.

I'm using IE10 though in a VM. Tom can fix it via CSS but perhaps just for Edge, not sure how backwards compatible we need this to be. At present the delay works for IE10 but when I drop back to IE9 or 8 then it doesn't. I know many people may still be using IE9...

I'll look over the .gray() code also - it must be doing something which is perhaps messing with the DOM and that's why there's no error - the header/footer code runs fine but the DOM elements perhaps aren't where they expect to be or something...

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo I'm testing with IE11. I don't get the same problem with Edge or any other browser.

Curious that the setTimeout works for you with IE10 John but doesn't for me with IE11. But having to do that doesn't sound like the right solution anyway?

@torinfo re-reading your earlier response and inspecting the buttons why on earth would nv.d3.css and the svg styles be having any impact on this? I can see that disabling either width:100%; or height:100%;  or both in nv.d3.css (lines 155 & 156) resolves the issue but why is that even having an impact?  What's that comment in there about "/* Trying to get SVG to act like a greedy block in all browsers */"?

**Comment by JohnSmith-LT** [comment]
Yeah @ronm123 it's not the best way to do this but we've had to resort to doing it in several places.

Anyway, It now doesn't seem to be working reliably for me although was last night. If @torinfo can fix using css then that would be ideal but I thought the reason for this plugin is that IE 10/11 and Edge 12 don't support css grayscale and use a js polyfill to do the work. There are a number of caveats with the gray plugin though and one is the use of percentage size, so that may be it...

Caveats
Non-numeric background-size and background-position
Non-numeric background-size (cover, contain, ...) and background-position (center, ...) are not currently supported.

Percentage-based background-position
Percentage-based background-position (ex. 50% 50%, ...) is not currently supported.

Non-visible elements will not be correctly initialized
Calling the plugin on hidden images (or other images that cannot have their size calculated) will fail in polyfill browsers. Workarounds can be found in the discussions at #57 and #40.

Child elements removed in browsers without support for CSS filters
Target elements with child elements will have those child elements removed in browsers without support for CSS filters. #61

Event listeners removed in browsers without support for CSS filters
Target elements with event listeners removed in browsers without support for CSS filters. #65

Colored borders
Colored borders will be also converted to grayscale in non-polyfill browsers. To also convert to grayscale in polyfill browsers, the class grayscale-replaced can be used:

**Comment by JohnSmith-LT** [comment]
Yes there are a lot of them and I saw that cover/contain are also not supported. There seems to be more that isn't supported in that plugin than actually is so there may be something better that can do gray and also cover/contain etc.

Some of the polyfills are great but sometimes they can actually do more harm than good and interfere with each other...

If width or height being removed fixes it then i'm assuming that removing one or t'other must break something too or else why are they there in the first place?

**Comment by torinfo** [comment]
@ronm123 @JohnSmith-LT I suspect (but don't know for sure) that the reason why the size of the svg matters, is that is is kind of an overlay, and apparently prevents mouseinput on IE when the overlay is over the buttons.

Indeed, changing the css breaks the dashboard, but I am sure we can overrule the svg css when the svg is not a dashboard

**Comment by torinfo** [comment]
@ronm123 @JohnSmith-LT I noticed that the width and hheight of this pasrticular svg were already set to 0, but using attributes in stead of styles. 

If I add the follwing fragment to mainStyles.css, everything seems to work:

'''
/* Specifiaclly for grayscale handling on IE browsers */
body > svg
{
	width: 0px;
	height: 0px;
}
