### ISSUE TITLE
Issues re the Top X question page in latest develop

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#825]
no thumbnail when selecting insert page
shows all the possible answers and feedback not just for the answers given - need an option to stop that and only show feedback for answers given
possibly need option for incorrect feedback for each answer too
ticking show answers repeats the list of all answers which perhaps is as intended but means that the default feedback list showing all answers and feedback for each is incorrect
Probably need to change the default language option text
ideally needs a retry option

**Comment by FayCross** [comment]
A few additional issues from my quick testing today:

- [ ] Not marking correctly. I have 4 possible answers & 2 answer fields shown on screen. I enter correct 2 answers (they are ticked as expected) but text below says 'Not all answers are correct'

- [ ] Attempts shouldn't be optional - if I remove it then null shows when previewed. If it is optional & not added then I think the text on the screen showing attempts should be removed

- [ ] Attempts text would be clearer if it said 'Attempt x of y' as I think it implies that it's showing the number of attempts you have made rather than the total you have left.

- [ ] If I don't enter anything then text says not all answers are correct - would be better to say not completed & I can still try again/not count as an attempt

- [ ] Disable changes to text field when correct answer submitted or when max attempts have been made

- [ ] When show answers is on it would be clearer to only list 'Other possible answers' rather than repeating all the correct answers

- [ ] When show answers is off the tags where they would be shown are still there so the feedback is pushed down too far

- [ ] Text fields, attempts text & 'this is not correct text' aren't responsive (some of these are responsive if intro text is shown but not when panel is full screen)

- [ ] Incorrect text is cleared from the text fields when answers are checked (except if it's the last attempt). It would be better if they always stayed there so they can see what they entered

- [ ] Would there ever be a need to enter more than one identical answer? I can create multiple answers with the same text but it will always mark only the first of these as correct

- [ ] Some strings & properties could be worded more clearly (I will do this)

**Comment by FayCross** [comment]
Various fixes committed in this commit https://github.com/thexerteproject/xerteonlinetoolkits/commit/b2c90656d03d61101bbc53c0639e3a65f9afba3e
