### ISSUE TITLE
issues with new text correction page latest develop

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#827]
no description when selecting insert page and thumbnail doesn't look like correct page
The text incomplete default text is: You have not filled in any answers correctly. Please try again.
Should probably change to: You have not entered a response. Please try again. 
Not entering an answer and clicking the check button shows the answer but shouldn't
The answer text doesn't display as html and perhaps that's because it can't valid if the answer is html but ideally it should be possible to show the correct answer with for instance correct words in bold or a different colour which can be done in the editor text field but doesn't show when the answer is displayed.
Needs a margin or padding after the incorrect text. Added paras seem to be removed.
Any formatting or media added to the incorrect and correct text boxes appears to be removed. If that has to be the case then the textboxed is the editor should be just text areas without wysiwyg controls.

**Comment by FayCross** [comment]
A few additional issues from my quick testing today:

- [ ] With attempts set to more than 1, when check is clicked with the text field empty a message appears saying you haven't answered question. The check button is now disabled so you can't try again

- [ ] Similiar to above (& mentioned in Ron's testing) with just 1 attempt allowed if you submit with an empty box it says incorrect & show the answer. Ideally they should be promted to make an attempt before they can see the answer.

- [ ] Attempts text would be clearer if it said 'Attempt x of y' as I think it implies that it's showing the number of attempts you have made rather than the total you have left.

- [ ] Disable changes to text field when correct answer submitted or when max attempts have been made

- [ ] Not sure it's necessary to display the correct text below the feedback when they have answered correctly

- [ ] When panel is full screen the attempts text isn't responsive

- [ ] When panel is full screen the wrong text above the text area field is no longer visible

- [ ] Agree with Ron above that incorrect & correct text fields in editor should be for plain text only (see modify exercise for similar setup)

- [ ] Not sure 'Show further clarification' option is needed. Normally just added the optional property would be enough to show we want it included

- [ ] Should further clarification be reworded to feedback (to make consistent with other pages)

- [ ] Some spacing issues with text / feedback. Some text is very close to other lines

- [ ] Some strings & properties could be worded more clearly (I will do this)
