### ISSUE TITLE
Using more than one textarea tag upsets the editor

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#828]
From Neil Pollock on the forums: https://www.xerte.org.uk/index.php?option=com_kunena&view=topic&catid=4&id=1671&Itemid=759&lang=en#5644 

Using more than one <textarea> tag in a page seems to upset the editor display window. The first text box will appear in the Page Text editor panel, but any subsequent boxes will appear below the Page Text box as part of the editor window itself (and so can no longer be edited via HTML).

**Comment by JohnSmith-LT** [comment]
So this is a really strange one... It seems that you cannot nest textareas as when a textarea tag opens then it's contents are read right up until the first closing /textarea, I thought it might be a jQuery thing because we are using v1.9.1 which is quite old but I can reproduce with latest jQuery on jsfiddle (https://jsfiddle.net/JohnSmith_LT/L8rwgtyj/3/), so

<textarea id="ckeditor">
     `<textarea>Some stuff here`</textarea>
</textarea>

when parsed by jQuery takes the highlighted part above as being the textarea contents for the editor, so it swallows up the first <textarea> tag

So i'm about to commit an update to try to address that - basically if the contents contain the <textarea tag then we delay the inserting of the content until after the editor has been setup.

Seems to work but if someone can test then that would be great.

**Comment by ronm123** [comment]
@JohnSmith-LT Hi John
just tested and seems to work fine now e.g. allows multiple textarea tags and doesn't strip them out or display one under the main editor text box like it did previously.
The OP on the forums managed to use the documentation page for what he wanted but great that this will work in a future release.
Cheers
Ron

**Comment by JohnSmith-LT** [comment]
Cheers @ronm123 . Yes it's quite weird that it's never cropped up before but at least it was an easy fix.

**Comment by FayCross** [comment]
Sorry I've been away so only just seen this - it has come up before (2 years ago!) [https://github.com/thexerteproject/xerteonlinetoolkits/issues/410](url) I'll shut down that old issue now. Thanks for the fix @JohnSmith-LT

**Comment by JohnSmith-LT** [comment]
Aah, I never noticed that one before - good catch @FayCross ...

Just now it only does the delayed insert if <textarea is present but maybe later it should be refactored to insert all data after the editor has created since it will simplify code and there's probably no reason not to if it works in this instance...
