### ISSUE TITLE
xApi Dropdwonbox Learner id mode

### ISSUE THREAD

**Issue by eduh** [thexerteproject/xerteonlinetoolkits#834]
In the project properties I choose the LTI\xApi tab (Tsugi is installed) and choose 'email' from  xAPI LRS learner id mode. I can see the tsugi_xapi_student_id_mode  is updated. So far so good but when I refresh or call the property again it is switched back to 'Group' (while the db entry is correct)

**Comment by eduh** [comment]
Just to add some additional info: I'm using the static.php method and added the mail properties to the hardcoded user array

**Comment by torinfo** [comment]
The authentication mode of Xerte itself is not important, because that is not used.

The authentication of Xerte is used to authenticate content authors.

For xAPI, the learners need to be identified. Normally this is done through LTI, and for LTI you can (normally) use e-mail to be reported. If you do not use LTI, but use use the xapi_launch fetaure (lti is diabled, and xAPI is enabled) the only available student_id)mode is group, and the interface should revert back to group mode in that case.
