### ISSUE TITLE
In Chrome, Bootstrap unexpectedly scrolls when clicking in embedded XOT with 'Interactivity > Hotspot Image' 

### ISSUE THREAD

**Issue by suuuz** [thexerteproject/xerteonlinetoolkits#839]
This (minor) issue occurs in Chrome, not in Firefox or Edge. 

**Reproduction**
Open Chrome browser
Go to https://www.nottingham.ac.uk/toolkits/play_8222#page5section8 (Page 'Embedded Content', Section 'Xerte Learning Object')
Go to page 'Interactivity Hotspot Image' in the XOT. 
Click on a hotspot
--> The Bootstrap aligns the XOT to the top of the page. 

**Expectation**
--> The Bootstrap page doesn't change position.

**Comment by JohnSmith-LT** [comment]
This is a Chrome bug that has apparently been around since 2012 and persists across Windows and Mac versions - it isn't a bug within Xerte itself and happens with any iframe embedded in a page such as Youtube.

There is chatter online about possiblle workarounds but none appear to be 100%  solutions although this one sounds promising - https://github.com/shellinabox/shellinabox/issues/402

I will take a look at it and see if it can be worked in to Xerte without breaking anything else.

**Comment by FayCross** [comment]
This no longer seems to be a problem. Bootstrap project doesn't unexpectedly scroll when interacting with embedded XOT hotspot image page
