### ISSUE TITLE
Related to #868, drag and drop functionality should but doesn't work

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#869]
This would be useful functionallity to have working:

![drag drop uploading not working](https://user-images.githubusercontent.com/3907362/69496606-d9982c00-0ecb-11ea-972a-a07679e89efa.gif)

It's the same for copy+paste uploading (like Github has) except it doesn't even fire the upload event.

**Comment by JohnSmith-LT** [comment]
It seems like there is functionality built into the current editor to handle drag drop... did this work in the past @torinfo @ronm123 ?

**Comment by ronm123** [comment]
@JohnSmith-LT I guess this is directly related to the other issue about renaming images etc so you'll have seen my comments there but yes this has worked for me for quite a while. However I can't be sure about server differences etc e.g. it works for me with my local copy of xampp and it works on xot.xerte.org.uk but I tested on another one of my servers and got the same error as you. Not sure if that's a xerte revision difference or a server config difference. Also TBH I sually either copy and paste from having the image open or upload via browse etc rather than dragging files into the editor.

**Comment by JohnSmith-LT** [comment]
Yeah I think it was my computer playing games - some service must've stopped in Chrome because it's all working now after a restart and putting back the old file, with slight correction. Sorry for adding to your workload :-(
