### ISSUE TITLE
Pasted images upload with original filename and overwrite existing image with same name

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#870]
This was fixed as part of #567 and reported as fixed but nothing has changed in that uploadImage.php file yet it is now broken again... perhaps something has changed since the update to CKEditor 4 but it definitely needs looking at again.

Can you reproduce this @ronm123 ?

**Comment by JohnSmith-LT** [comment]
I've modified the uploadImage.php file to fforce it to call pasted images pasted_image.EXT, pasted_image(1).EXT, pasted_image(2).EXT etc where EXT retains the extension/type of the original file.

I've also commented out several functions including sanitiseFilename since it's not needed if we are renaming the files to a format of our choosing...

**Comment by ronm123** [comment]
@JohnSmith-LT I'm not sure about this and have not had a problem with the way this has worked up to now. But I think I do have a problem with the way it works after your changes! ;-)

I might be wrong but my perspective on this is as follows and I thing we need to differentiate between drag and dropped files vs copy and paste images...

With the wysiwyg editor window open if I have a screenshot or something in my clipboard and click paste I expect that image to be uploaded and automatically named e.g. image.jpg. If I then repeat that process either with the same image or a different image I expect the same to happen again e.g. the new paste becomes image(1).jpg and doesn't overwrite my original because I'm effectively pasting unnamed images. I usually then rename and re-select those files within the media browser so that I don't have loads of images without useful names.

However if I drag and drop an image file from my drive into the editor named for instance ron1.jpg and then repeat that by dragging a new copy of ron1.jpg that I have made changes to then I don't want that renamed e.g. I'm saying update ron1.jpg with this newer version. I also expect the same to happen when uploading via media and quota. As an example I've done this many times where I've uploaded a logo and then resized or made other changes to the logo and then uploaded the new copy to replace the old copy. 

Your change now seems to force the image to be renamed even when it's an already named file being uploaded and I don't think that should be the case. Is that your intention? Perhaps I'm wrong about what should happen here - what do @FayCross and @torinfo think?

**Comment by JohnSmith-LT** [comment]
Ah, ok, I screwed that up. Problem is that I couldn't get paste to actually work because I couldn't figure out how to enable it in the browser (perhaps that's something we need to add somewhere as a tooltip)

Leave this one with me and i'll figure that out and commit changes - there was something funky going on with the sanitiseName() function though because wasn't setup to have the 2nd parameter passed and upon my debugging $response is being set in that function but not being passed back.

**Comment by ronm123** [comment]
@JohnSmith-LT just to be clear - when you say you couldn't get paste to work how/what were you pasting? e.g. 

1. I've always expected and assumed this should work like it does in an open email for instance e.g. If I have an image open and selected in PowerPoint, or Snagit or Photoshop etc and select copy and then switch to the email or Xerte and select paste then I expect that to paste and see the image in the page. 

2. However if I simply select a file in a local folder and select copy or Ctrl + C then I don't expect that to paste, even if the file is an image and as I'd expect, that doesn't work. 

3. However if I drag that image file onto the Xerte editor window I do expect it to upload and appear as an image (using the name of that file) - at least since we've had all that working in whatever version it became available. 

Is your copy and past that doesn't work 1. or 2.?

**Comment by JohnSmith-LT** [comment]
Ok @ronm123 sorry about that... I've put it all back the way it was with that missing $response in place and i've restarted my machine and all seems to be working now. Can you check it's back the way it was for you?

I was definitely doing 1. above but a service must've stopped or something as it was only Chrome that didn't work and initially I got a purple-ish popop (like the upload successful message) which said something like Ctrl-C and Ctrl-V need to be enabled to do this. I only saw the messga eonce though and then googling said Chrome should be enabled always.... so I have no clue...

**Comment by ronm123** [comment]
@JohnSmith-LT yes seems like it works like it did again now.

I replied to #869 though and can replicate the error you reported with that install/server but assumed that was a server/firewall issue rather than Xerte code.
