### ISSUE TITLE
Problem with glossary and info panel on thumbnailViewer

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#871]
Reported on forum:

https://xerte.org.uk/index.php/en/forum/bugs-and-issues/1860-glossary-term-word-not-displaying-on-thumbnail-viewer-when-hover-text-overlay#6165

Was found to have several problems:

- [x] Glossary highlighted word was black text on black background
- [x] Glossary and panel would flash ash you move mouse across and glossry popup wouldn't show
- [x] On first load, before resize, panel would be 0px by 0px so would not show on hover

I have provided 2 files to end user to test

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 @torinfo and @FayCross have either of you come across this issue with thumbnailViewer before? Is it new or just never been spotted before?

If/when you get a chance can you test these commits to make sure they don't break anything you already have?

**Comment by JohnSmith-LT** [comment]
There appears to be another issue, if you click the close button it opens the image in the browser (if that option is selected in the LO) and it closes the panel in the LO (as it should). But then you cannot open the panel again with that same thumbnail but must cllick a different thumbnail...

I don't think that is right... agree?

**Comment by ronm123** [comment]
@JohnSmith-LT don't think I'd seen the issue before but I guess it's quite a unique combination e.g. glossary term has to exists and term used also be added to the thumbnail description. Testing your two files I can see that the glossary popup now works but I think there's a problem with adding `#panelTxt .x_glossary {
		background-color: white;
	}`
Because on dark themes like Dark: Blue Grey that then shows a white box behind white text. I think changing that to
`#panelTxt .x_glossary {
		color: #ffffff;
	}`
Is more likely to work without breaking with other themes but I can't be 100% sure about that without testing them all. However it seems clear that the glossary hadn't worked on the thumbnail page anyway unless that was a bug that crept in with other changes.

Re the other issue of not being able to re-open the same thumbnail after closing without first opening another - yes that doesn't seem right but unless an easy fix I suspect it's not that likely to happen in practice although I guess it could.

I've tested your two files and I think apart from the suggested css change they should fix the issue Anne has reported. But she isn't likely to be able to test that until she asks me to replace the two files on the Northampton installation! ;-)

**Comment by JohnSmith-LT** [comment]
Thanks @ronm123, yes it's those strange combinations that probably don't get tested enough by us...

After commiting those changes I did think that it may be an issue in other themes - changing it to #ffffff may work better as you suggest so i'll go ahead and do that and look at the close issue and commit some more files over weekend for them.

Didn't realise Anne's install is managed by you !

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 

I've now implemented your suggestion as well as fixing the close button opening the image (if that option selected) and the panel reappearing after closing it and clicking same thumbnail again.

John

**Comment by ronm123** [comment]
@JohnSmith-LT as far as my testing goes this works well now. @torinfo I'm not sure where we are with cherry picking or just making everything currently in develop part of 3.8.4 but if it's still cherry picking then I think this should be part of that too?

@JohnSmith-LT seems like this issue should be closed now.

**Comment by JohnSmith-LT** [comment]
Cool, i'll close. Have told the person on the forum that you will be updating their install soon.
