### ISSUE TITLE
issue with FA icons and page types/wizards with more than one text box by default

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#876]
Hi all
this was just reported to me so I'm adding while it's fresh in my mind. The example was using an orientation page but the same issue happens with a summary page and possibly others too. To replicate:

1. Add an orientation or summary page
2. Turn on Show Toolbar
3. Add an FA icon to the first text box which should work fine
4. Try to add an FA icon to the second text box - it won't work and will add something like the following:
`<p><span class="fav2"><i aria-hidden="true" style="color:#000000;" title=""></i><span style="position:absolute; left:-10000px; top:auto; width:1px; height:1px; overflow:hidden;"></span></span>Describe the target audience
</p>`
Can you replicate this?
A short term solution is to click on another page in the tree and then back to the orientation page and then adding the FA icon to the second text box works fine but you then have to repeat that again for the 3rd and 4th text boxes too so not really the answer.

Not sure how many places we have multiple text boxes by default or if the same issue arises with any of the other project templates. I guess also it might not just be the fa icon button where this happens?

**Comment by FayCross** [comment]
Yes I can replicate this (& there are loads of pages with more than one text boxes on XOT template - don't think there are any in Bootstrap template). I don't think it's an issue with any other buttons in ckeditor - I've tried a few out & they seem to work ok in multiple text fields.

I've tried upgrading fontawesome plugin in ckeditor but it still does this (actually I think we were already using most up to date version anyway).

The tags are added for the icon in the second text field but no class to say which fontawesome icon should show:

![fa](https://user-images.githubusercontent.com/8926470/73834413-90395680-4803-11ea-9acf-aebc9cec2e79.PNG)

**Comment by JohnSmith-LT** [comment]
Hi. This plugin hasn't been updated since 2017 by the looks of it, in which time CKEditor has moved on and we are using alater version than was available back then. I suspect that he has used a non standard way to access something (probably in the DOM) and the DOM structure has changed. Notice that when you insert in first and move to the second that the 'Alternative Description' doesn't populate either...

In addition the author has chosen to not only compress the JS but also to obfuscate it somewhat with PACKER before distribution - even if we can unobfuscate and patch then we may not be able to distribute as it may be against his terms...

**Comment by JohnSmith-LT** [comment]
Fixed in https://github.com/thexerteproject/xerteonlinetoolkits/commit/e6cba16a284aab6a421d502c9ac6de7e3a4d9759

**Comment by JohnSmith-LT** [comment]
A few more fixes applied in de4507a24210aa4242d43766ef98caa918f27616 so i'm now going to close this.
