### ISSUE TITLE
Hidden page seems boken

### ISSUE THREAD

**Issue by ingedonke** [thexerteproject/xerteonlinetoolkits#897]
It is not possible to delete the date in Xerte Online Toolkits projects.  See a video of Katrien here (in Dutch). She tries to delete the date but as soon as she goes to another page it is visible again.  https://drive.google.com/file/d/1vT77CRMdobbnCtqHV-UXnDZF3xrMEYlT/view
We noticed that as long you do not open that hidden page it stays ok but as soon as you open the hidden page (in the editor) you can't delete the date.

**Comment by torinfo** [comment]
@FayCross  Hmmmm... I think this is because of the way allowBlank has been added. T=If that field is NOT present in the xwd, than the editor assumes that the date may not be blank...

It works in en-GB. It is fixed by installing the latest nl-NL.

It only happens if you actively visit the hidePageToDate with an xwd that has not been updated yet.

**Comment by torinfo** [comment]
@FayCross do you agree to change this line:

`} else if (value.length == 0 && options.allowBlank != "true")`

to 

`} else if (value.length == 0 && (options.allowBlank != undefined && options.allowBlank != "true"))`

I'll test this for the case where allowBlank is set to false in the xwd and will let you know.

**Comment by torinfo** [comment]
Alos, just to be clear (because this will cause issues for Welsh as well). This is NOT caused by the security fix. This was part of #863 (which was part of v3.8.4)

**Comment by torinfo** [comment]
Nope... that won't do, because it will break what you're trying to achieve. Now all of a sudden datefields that you do not want to be blank can now be left blank. 

I will not commit this fix. Only way to fix it is to install latest language pack.

**Comment by ronm123** [comment]
@torinfo thanks for pointing out that this will cause problems for Welsh as well. Am I correct in thinking as long as I've installed the 3.8.4 language pack this should be ok or are there relevant incremental updates involved in the language pack since 3.8.4 too? e.g. on xerte.org.uk it just says 3.8.

**Comment by torinfo** [comment]
If you installed the langauge pack at the time you updated the install to 3.8.4 you're ok. The language packs are always updated together with releases. I can't use git to update the version number automatically.... (perhaps I should just use the version number of the Xerte Tookits package.

**Comment by FayCross** [comment]
Thanks for sorting this Tom. Out of interest, where else is the datepicker used (not hide/show page)? I think my October changes were because you had used it elsewhere & changed slightly how it worked which had knock-on effects on the hide page stuff. It's worth checking that my changes didn't break anything in your use of it.

**Comment by ronm123** [comment]
@torinfo sounds like a good idea to use the toolkits version number. I've never been sure about this because of the lack of language pack version number.

**Comment by torinfo** [comment]
@FayCross Hmm. Interesting. It's in the Adaptive Contents page. I'll have a look again on how we can make sure the code keeps working with out of date language packs, although I think its low priority.

@ronm123 I'll have a look
