### ISSUE TITLE
Glossary not working anymore

### ISSUE THREAD

**Issue by torinfo** [thexerteproject/xerteonlinetoolkits#902]
I was made aware that the glossary did not work anymore (at least in Chrome and develop). Need testing in 3.8.5. 

It turns out that when hovering into a glossary word, it tries to remove any popup that is already present. In that part of the code it checks for the folowing (around line 956 in xenith.js):

`if ($x_glossaryHover != undefined) {
	$x_glossaryHover.remove();
}`

It triggers an error that $x_glossaryHover does not exist, and as a consequence the definiton never pops up!

I changed it to:

`if (typeof $x_glossaryHover != "undefined") {
	$x_glossaryHover.remove();
}`

Then everything seems to work fine. It's only in that install. It seems to work fine in other installs.

Any ideas?

**Comment by JohnSmith-LT** [comment]
Oops, think it was me when I migrated the variables code out of Xenith. Looks like I dropped the $x_glossaryHover var at line 51 at same time.

I'll fix after meeting.

**Comment by JohnSmith-LT** [comment]
Hi @torinfo 

Fixed the issue - it was me who dropped the variable.

Also noticed and issue on an LO i'm working on where I have to wrap all the words in a <span> in order to highlight them in sequence - occasionally the regexp ends up with <a><span>WORD</span>SPACE_HERE</a>   , i.e "word " in the comparison "word "=="word" which fails so i've thrown in a few trim()s that should fix things but can you check that nothing else is now broken on any LOs that you have been testing? If you can test quickly too @ronm123 then that would be appreciated.

I have started ripping all the glossary code out into a module, like VARIABLES and the $glossaryHover must have sneeked in there - i'll commit the glossary code module once I confirm it's now all working again.

John

**Comment by ronm123** [comment]
@JohnSmith-LT in terms of testing is it just wherever a glossary is used or could this affect other areas too?

**Comment by JohnSmith-LT** [comment]
Just where they are used, but perhaps special use cases like use of images or where you have done some sort of dom maniputaion on the glossary word, like in my example I wrapped a glossary word in a span. The changes really only affected the removing of the glossaryHover bubble.

There shouldn't be anything and it's just luck that @torinfo reported the glossary problem that I found there could be an extra space getting into the comparison - but that bug has probably been around for a while

**Comment by ronm123** [comment]
@JohnSmith-LT  I can't see any issues in the projects I've checked but I pulled down the latest commit before checking. @torinfo was the issue reported to you by someone using develop or is the issue part of 3.8.5 too?

**Comment by torinfo** [comment]
@ronm123 Only in develop.
@JohnSmith-LT As far as I can tell the issue is resolved. Thank you!
