### ISSUE TITLE
Lockfile issue - invalid email addresses

### ISSUE THREAD

**Issue by jayaich** [thexerteproject/xerteonlinetoolkits#909]
I have been receiving a few messages from our mail system about emails trying to be sent from our Xerte server. Looking at one of these messages shows:

`A message that you sent contained one or more recipient addresses that were`
`incorrectly constructed:`

`  09:37:20),@...ac.uk: missing or malformed local part (expected word or "<")`

As can be seen the recipient part of the address is '09:37:20),' which is obviously wrong.

Looking at the code this seems to come from a 'lockfile.txt' file which seems to be created to prevent multiple editors of a template. So, if the file exists the user cannot edit the template, but their username is added to the lockfile and they will be emailed when the template becomes free for editing.

The problem is the format of the lockfile. As an example we have:

`user1 (2020-05-29 13:22:46)*user2 (2020-06-09 09:37:20), `

where 'user1' is the creator of the lockfile, the user currently editing the template. 'user2' is a user who has tried to edit the template, failed, and their username added to the lockfile.

However, looking at the code in the 'website_code/php/versioncontrol/template_close.php' file, the lockfile creator is extracted by 'exploding' the file based on the asterisk(*) character. The user email addresses are obtained by exploding the rest of the file based on the space character.
But looking at the example above, this would gives the users as 'user2', '(2020-06-09' and '09:37:20), ' - the last two of which are obviously wrong.

This seems to come from the 'edithtml.php' file. The commit adding in the date to the lockfile is ('Add date to lockfile' -  Tom Reijnders committed on 5 Apr 2018 ) [https://github.com/thexerteproject/xerteonlinetoolkits/commit/1b95c7b027aa19e7a95dcdc4551f3bf60438d9ce#diff-9093bd6670cd6396b8318cc62d2847cb](url)

I don't know why the date is added - it doesn't seem to be used - but for non-creator users it seems like it shouldn't be included. After the asterisk it should just be a space-separated list of usernames.
I'll see if I can do some testing without the date being added

John.

**Comment by torinfo** [comment]
@jayaich I don't know what the original idea was to do it like this. I don't know if the lock date was added at that time, or all the dates. However, it is important to make sure this works properly, because we intend to use the lockfile more (even to lock oneselve, to try and prevent users from opening the editor window more than once (in a different tab, or a different browser).

I could also imagine that we use the dat in the email, to indicate when the request was made (when the user tried to edit the file).

So, for me the explode on space in template_close.php should have been an explode on ',' and than an explode on space to get the username.

Hope this helps.

**Comment by jayaich** [comment]
Pull request #914 merged.
