### ISSUE TITLE
XWD language properties can't be mandatory

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#944]
In this commit (https://github.com/thexerteproject/xerteonlinetoolkits/commit/4ec8790d0b3937a51a92ecd0a3ffe26f36e1202c ) I'd like the new pinAlt language property to be mandatory so it can be edited on existing interactive diagram pages however it doesn't get added to the editor. It looks like mandatory="true" in xwd only works for normal properties & not those marked as language="true"

**Comment by FayCross** [comment]
Not high priority now that the Interactive Diagram page is deprecated but it still might be useful to allow at some point.

**Comment by JohnSmith-LT** [comment]
Hi @FayCross it probably is high priority now because i've just added an aria-label language field for Dictation page and have run into the same problem - fine for new pages but isn't added to existing ones...

Did you not see this @ronm123 with the modelAnswer page when you added the `<answerFieldLabel label="Answer Field Hidden Aria-Label" type="TextInput" wysiwyg="false" language="true" mandatory="true" defaultValue="Answer" tooltip="This is a hidden label specifically for screen reader users so that the text field where they should respond is labelled and the label is spoken to the screenreader user. e.g. Answer."/>` recently?

**Comment by ronm123** [comment]
@JohnSmith-LT now that you mention it I think I did notice but didn't raise it because there are so many other things on the list. There's a balance to be had I think e.g. we're adding default values in the code so if the wizard option doesn't appear then that default value is used e.g. Answer. Yes that would be incorrect for another language but in the case of aria-labels only relevant to screen reader users and just indicating that its a text box to type an answer. So ideally yes we should find a way to ensure that new fields do appear where relevant but if that's not easy at least we should put the options in place for new porjects/pages and revert to the defaults in code for existing?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 yes defaults are good too but that forces the english version of a word and doesn't allow author to change...

It's all moot now though because I'm pretty sure i've fixed it. Just about to commit so please test as i'm a bit wary of changing too much in the editor at such a late stage...
