### ISSUE TITLE
Glossary term problem reported on forum - link breaks if term is in a link

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#956]
Hi @ronm123 

I know you answered this in the forum (https://www.xerte.org.uk/index.php/en/forum/bugs-and-issues/2213-using-the-same-word-as-a-glossaet-term-and-a-link-results-in-link-not-working#6888) with a workaround but this is still an issue if people don't realise since it actually breaks the links. Not sure why we even have glossary terms as < a > tags but we could switch these to < span> and make this work... i've mocked this up by editing the Html but would you say that this is too much/overkill text decoration?

![image](https://user-images.githubusercontent.com/3907362/94033940-5bd9d100-fdb9-11ea-8615-c2ed8d927825.png)

the markup would then become

```
<p>Enter text for <a href="http://xerte.org.uk" target="_blank">the <span class="x_glossary" def="stops links working" >page</span> here</a></p>

<p>Normal <span class="x_glossary" def="stops links working">page</span> link</p>
```

By doing this the link still works and so does the tooltip...

Wouldn't need much change to the css... but would need some update to the xenith code...

What do you think @FayCross although i'm quite surprised that this hasn't been reported before TBH

**Comment by FayCross** [comment]
I think a tags were probably used to make them easier for screen reader or keyboard only users to access them. It's fine to change them to span tags as long as they can still be tabbed to & accessed by screen readers etc.

**Comment by JohnSmith-LT** [comment]
That's a good consideration @FayCross that I hadn't thought of... I think just adding a tabindex="0" to the < span> will solve that issue but i'll test it... Thanks...

**Comment by JohnSmith-LT** [comment]
Hi @FayCross. Now I know VERY LITTLE about the accessibility stuff so I did some reading about aria-label and role on < span> and < div> and between that and the tabindex="0" I have it working "I think"... the new code comes out as:

<span class="x_glossary" def="DEFINITION" tabindex="0" role="tooltip" aria-label="TERM" title="">TERM</span>

Now to the best of my knowledge I haven't broken tabbing and internet said that to have an aria-label on a < span> you need to give it a role and there was one called tooltip so I chose that...

Let me know what you think (and you as well @ronm123, @torinfo) and feel free @FayCross to change anything that I have got glaringly wrong!

**Comment by FayCross** [comment]
@JohnSmith-LT I think that's fine. Tabbing to definition & accessing tooltip while still allowing the link to work seems fine. @ronm123 would you be able to check with screen reader please? I've just tried with Windows narrator & can't seem to access definition but I think that's probably just because of my inexperience with it. If it's fine then we'll need to also make this change in the Bootstrap template as you can also add a glossary there

**Comment by ronm123** [comment]
@FayCross no I don't think it does work with a screen reader but I don't think it did before the change @JohnSmith-LT has made either. I suspect the pop-up needs to be given focus or have aria-live="polite" added or something like that?

**Comment by JohnSmith-LT** [comment]
Hi,

Maybe I got it wrong, this says that the role="tooltip" should be added to the tooltip container and not the initiator and perhaps instead we add aria-describedby="x_glossaryHover" to the < span>

![image](https://user-images.githubusercontent.com/3907362/94711545-27798e00-0340-11eb-8720-eeb2144f6f56.png)

https://www.accede-web.com/en/guidelines/rich-interface-components/tooltips-aria/#:~:text=Examples%20of%20components.-,Principle,which%20is%20the%20title%20attribute.

**Comment by FayCross** [comment]
@JohnSmith-LT Yes i noticed this but I've been trying this for the past hour & just can't get it to work. It doesn't seem to work with role="tooltip" on tooltip div & aria-describedby on span & I've tried various rewrites of code alongside this but can't get it to work. I thought maybe it didn't like that the tooltip tag doesn't exist until it's rolled over but just using hide/show doesn't help either. Also tried using aria-live polite. Your fix for links is fine though - I think Ron might be right that this don't work before either

**Comment by FayCross** [comment]
This now works in NVDA (can't get working ion Windows Narrator though)

**Comment by JohnSmith-LT** [comment]
Well done @FayCross , it's working for me too on NVDA but is it not a bit verbose? Mine seems like it is reading everything out twice...

**Comment by FayCross** [comment]
I think it's because it reads the glossary word on the page out, immediately followed by the contents of the tooltip (which starts with that same word) e.g. 'Cat, cat: an animal that says miaow'. I think I marked it up so that the tooltip div was referenced in 'aria-described-by' - it might be better to specify just the definition bit of the tooltip

**Comment by JohnSmith-LT** [comment]
Yes, perhaps that's it - thought it was reading the description twice too but was probably mistaken or had messed with the code at my side... Have you tried emulating the image above with the glossary word actually in the link? Do you think that is sensible or is the screen reader output very verbose and awkward or should we try to skip that and put the glossary on the next occurance of the word? I suppose then what happens if the word is only inside the link and nowhere else on the page...

**Comment by ronm123** [comment]
I tested this with NVDA and Narrator and got the same as you @FayCross e.g. the tooltip was read by NVDA but not Narrator. I tried changing the role attached to x_glossaryHover to alert rather than tooltip and then it was read by both but I'm sure that's not correct. So I changed it back to tooltip and investigated Narrator settings. It turns out that by default the option to "Hear advanced detail, like help text, on buttons and other controls" isn't checked by default.
Press Ctrl + Windows Key + N then select Narrator in the left menu if not already selected and browse dow to the option labelled "Hear advanced detail, like help text, on buttons and other controls" and check that.
Now test again by tabbing to the glossary link and although there seems to be a slight delay before the tooltip is spoken (might just be the speed I have set) it does now read the glossary definition.
