### ISSUE TITLE
Editor opening in new window vs. tab

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#960]
I have often seen people lose track of where the editor is when they are first learning Xerte, especially after previewing as this then opens another new window. When editing a project I tend to copy the URLs of editor & preview into new tabs as I find it much easier to navigate between editor & preview in this way than search through multiple browser windows. If I do this in 3.9 I now always get the lockfile error when I try to edit again (I guess me manually entering editor URL into new tab always caused lockfile issues but it's more noticeable now that I get it on projects that aren't shared).

So 2 questions:

1. Do we need to still force editor to open in new window? Simply removing the height & width from window.open in template_management.js seems to change it to open in new tab instead. Will this have any implications for lockfiles etc.

2. If it needs to still be in a new window is there any way to do this so that it has the full browser bar - refresh etc? Then I could just drag it into a new tab in the browser window I already have open rather than copying & pasting the URL.

**Comment by JohnSmith-LT** [comment]
Hi @FayCross 

1. I doubt it will have any impact on lockfiles or anything else since the tab shoudl still behave as a named window would. In actual fact it is probably best practice now to allow the device and browser to decide where the new page is opened (based on user settings) rather than forcing a new window...

2. maybe make sure it has "toolbar=yes,location=yes" in the window.open features?

**Comment by torinfo** [comment]
Hi @FayCross 

1. No, not the lock code perse. But the the woindow gets a name, and that name is used to give focus to that window if you reopen the same LO again. If you give the window a name, it will always be created as a popup window. So don't know how to fix that. Perhaps keeping the returned valy will allow the tab to get focus, but I doubt that.
2. @JohnSmith-LT Regrettably that doesn't seem to work (at least not for Chrome)

**Comment by JohnSmith-LT** [comment]
Yeah @torinfo they've messed around with so many of these (because of some potential vulnerability) that many things have become impossible... if we only expect one widow to be open at a time then it might be sufficient to just store the return ref as you suggest and then call the focus method if it exists and clear it if the window gets closed... if there could be multiple windows open (like the flasg drawing editor or similar) store and array of window names and their refs and do a lookup...

**Comment by FayCross** [comment]
Closing as you can use Ctrl click to open in new tab rather than new window: https://github.com/thexerteproject/xerteonlinetoolkits/commit/139d710cb69256071ecd7a0153f8a6a3dc582f0c https://github.com/thexerteproject/xerteonlinetoolkits/commit/58d16b98af6fce109b46a756b1653194c451c8c0
