### ISSUE TITLE
Encoding in greek

### ISSUE THREAD

**Issue by kiolalis** [thexerteproject/xerteonlinetoolkits#973]
In some cases I think there is a problem with encoding in greek. E.g.: in the graph of the "Opinion interaction" a popup with "&Delta;&rho;&alpha...etc." appears and in the output of the "Results Page" when we put "Download PDF File" characters are not recognized. For more details, see the attachments.

![3](https://user-images.githubusercontent.com/2521530/96474609-aa08b580-123b-11eb-8ead-41b5b25a6add.jpg)

![4](https://user-images.githubusercontent.com/2521530/96474603-a8d78880-123b-11eb-83bc-d83e31bb8331.jpg)

![results](https://user-images.githubusercontent.com/2521530/96597560-a84ff800-12f6-11eb-94ad-631b0bccc591.jpg)

**Comment by JohnSmith-LT** [comment]
Hi @kiolalis & @ingedonke

Do you have a test LO that you can share here that demonstrates this and then I can play around with the encoding? I suspect that the PDF just needs to be told what encoding to use to solve this...

John

**Comment by ingedonke** [comment]
Hi John,

Here a link to an example, also a download link.
https://dev.tor.nl/~tom/xotdev/play.php?template_id=795
https://dev.tor.nl/~tom/xotdev/website_code/php/scorm/export.php?template_id=795&scorm=false

Bye,
Inge

**Comment by JohnSmith-LT** [comment]
Hi @ingedonke & @kiolalis 

So i've nearly ironed out all the issues. Firstly, in the Canvas, the labels were showing the full HTML entity reference (&gamma; &lambda; etc) instead of the symbol - canvas apparently cannot process them so I first rendered them in a div tag and then captured the text representation using a simple function:

function htmlToChar(h){
    return $("<div>").html(
        x_currentPageXML.getAttribute("name")
    ).text();
};

![image](https://user-images.githubusercontent.com/3907362/99891647-22f89400-2c64-11eb-9234-e00288a79024.png)

Secondly, the PDF needed to have a Unicode font embedded  but in order to do that I had to upgrade to the latest version of jsPDF. Sadly a lot of the api had been rewritten or deprecated and therefore I have had to re-write much of the table rendering code. I also took the opportunity to update the images to use the same as the results page:

![image](https://user-images.githubusercontent.com/3907362/99891725-fe50ec00-2c64-11eb-8684-5f4c268cba39.png)

I need to fix some of the formatting of the tables and positions of the images etc but I will get them done sometime this week and get the files uploaded.

John

**Comment by JohnSmith-LT** [comment]
Hi @ingedonke  & @kiolalis 

I've now uploaded the files. I had to pretty much rewrite the results page to use the latest jsPDF since the version that we were using didn't properly support importing of unicode fonts - this also meant that I had to upgrade AutoTable and rewrite those parts to use the new API...

Since I now had to include 4 files (jsPDF, AutoTable, + normal/bold fonts) I also rewrote the loader and aggregated the files into a jsPDF folder...

There has been so much changed in this that it's probably going to have some bugs so it will need extensive testing and unfortunately @torinfo I haven't made any changes to the export or offline code tto include the extra or relocated files so that will definitely need looked at..

Lastly, there seems to be a wee bit of a bug with the opinion page and possibly the results page - if you duplicate that opinion page so you have this structure:

Opinion
Opinon
Wordsearch
Results

And you start at page 1 but DON'T submit the opinion page and move to page 2 and DO submit (with the default options) then you don't get the correct chart but instead it is tiny (below). Also, when you get to results page it shows two solid blue circles but there is an option for a solid blue and hollow blue in the code which I can't seem to have on screen at the same time...

![image](https://user-images.githubusercontent.com/3907362/99948863-08144580-2d72-11eb-8fba-e0323f9bcc09.png)

I'm not sure if this issue is just the same as the problem that we have with many pages, in that you can't have two of the same page in the same LO without them interoperating somewhat... Perhaps some testing will help identify the issue...

John

**Comment by ingedonke** [comment]
@JohnSmith-LT @kiolalis I will test it this week and let you know. Thanks for all your work :)

**Comment by JohnSmith-LT** [comment]
Hi @ingedonke 

Did you ever get around to testing this and can this issue be closed now?

**Comment by JohnSmith-LT** [comment]
Thanks @ingedonke
