### ISSUE TITLE
Peer review - problem with links in emails

### ISSUE THREAD

**Issue by FayCross** [thexerteproject/xerteonlinetoolkits#995]
When using peer review, the emails that are sent containing submitted comments include a link to the play version of the project. This happens even when the project is private (so then the link doesn't work)

**Comment by ronm123** [comment]
@FayCross have you checked this with develop code? I think I already added a fix for this including checking if apache is true and therefore using /play_xyz as the link too. But without checking I can't remember if I removed the link if not public.

**Comment by FayCross** [comment]
@ronm123 No it's 3.8. Although, having a look at the code I think this would still be a problem. This is the [file](https://github.com/thexerteproject/xerteonlinetoolkits/blob/49cd9bc20f91f9676bf241666612a41685498bc5/website_code/php/peer/peer_review.php) that sends email & there's no check done there

**Comment by ronm123** [comment]
@FayCross this is weird! I'm sure I didn't dream it and sure I tested the changes I made because I noticed the same thing as you. I may have changed the files in one of my online installs without including those changes in my commit. I don't have time right now but I'll add to my todo list to check. I'm sure my thinking at least was as follows:

Show peer link in the email if the project isn't public.
Show public link in the email if it is public.
In both cases also check if the install has apache set to true and if so change the link format. 
That last point is why I'm sure I did this because I'm sure I tested the impact but perhaps I did just dream it! ;-)

**Comment by ronm123** [comment]
@FayCross I'm not going nuts and wasn't dreaming I did fix this and have the test emails to prove it! ;-)
So I know what install I have the changes on but need to track down where I made those changes in my local files.

**Comment by FayCross** [comment]
Thanks @ronm123!

**Comment by ronm123** [comment]
@FayCross try https://github.com/thexerteproject/xerteonlinetoolkits/commit/6141a65b1b70ce3d0977a3e6eb73e440f324bae7 and let me know?
Should work fine but I've added a note that I either need to add a bit more code, or use a copy, for the new feedback.php page otherwise that also includes a peer link if the project isn't public. But that feedback page isn't linked anywhere yet and @torinfo was going to look at a simple sanitization solution for peer and feedback to strip out html too.

**Comment by ronm123** [comment]
@FayCross @torinfo I've noticed a different issue with the peer review page but seemed better just to add a comment here rather than add it as a separate issue especially as I'm not sure what specific change has caused this...
With latest develop if I now view an xot project via peer review and try the 'View in lightbox' option the lightbox flashes open but then closes immediately. The same option still works fine with peer review of Bootstrap projects but not XOT and I'm sure it did work ok with XOT projects previously and in fact just tested with 3.9 and works fine. Can you replicate this too? Any ideas re cause/solution?

**Comment by FayCross** [comment]
Possibly to do with a change I made in this commit https://github.com/thexerteproject/xerteonlinetoolkits/commit/2368bfc1a4bc98a292c371c8a5929bb981b12b12#diff-f66f1c409c7dcf18db3236ef83736345c2f1d0caec82dfb7a164f3df02789631 where I force light boxes to close on page change? I think I introduced this as using page up/down keys when light box open would change page in background but still leave light box open on top. Perhaps it’s caused issues elsewhere? I’m not around until next Wednesday but will look at this then if you’re not able to fix.

**Comment by ronm123** [comment]
@FayCross thanks for the pointer Fay but actually I think the cause is this later commit by @torinfo https://github.com/thexerteproject/xerteonlinetoolkits/commit/065731d1d8b5171713f2429a59e7bde812ac4995 
e.g. it's the added try around 1875
`else {
		// If the whole Xerte object is loaded in a lightbox, we could trigger a DOMException (cross-origin)
		// So enclose in a try block
		try {
			if (parent.window.$.featherlight.current()) {
				// force lightbox to close
				parent.window.$.featherlight.current().close();
			}`

If I comment out parent.window.$.featherlight.current().close(); then the peer review lightbox works but Tom has obviously added that additional code for a reason and I'm not sure therefore what the solution should be?

Indeed it's not just the peer review where this is a problem. I tested LOs where we have other LOs linked as lightbox links and in develop those links also automatically close now too. @torinfo I know the new code you added is to deal with a cross-origin issue but does this mean it shouldn't be possible to display external LOs in lightbox windows?

**Comment by torinfo** [comment]
@FayCross @ronm123 
Ron, I only added the try block around the code. The actual close was added by Fay as she explained in the previous comment. As it causes more issues than just the cross-origin issue, we should probably look at a different way of dealing with the issue Fay tried to solve. For example by closing the lightbox if the pg up/pg dn key is used.

**Comment by torinfo** [comment]
@ronm123 The cross origin issue I had was completely diffrent..... The Xerte object was shown in a lightbox in a completely different environment (FutureTeacher) and Xerte tried to close THAT light box. That issue was solved by adding a try ... catch block. I think we explicitly want to allow external content in a lightbox.

**Comment by ronm123** [comment]
@torinfo agree that we explicitly want to allow external content in a lightbox. And sorry if I missed that it was still the code that @FayCross added which caused this and not the additional code that you added but what started as me noticing the issue with the peer review lightbox link is obviously a much wider issue and would currently break some existing projects where lightbox links open external LOs. In fact I updated one of my installations to the develop code to be able to demo the accessibility fixes during #xerte21 so I'm going to have to comment out that bit of the code on there until there is another solution to implement.

**Comment by FayCross** [comment]
I’m fine for that whole block to be removed in develop & I’ll look at a better way of fixing the keyboard change page issue when I’m back. The issue I was trying to fix is probably much rarer than the issues it’s caused. When not using keyboard to change page you have to close light box to get to navigation buttons anyway.

**Comment by FayCross** [comment]
Fixed lightbox issues in peer review with https://github.com/thexerteproject/xerteonlinetoolkits/commit/0668742bbdb90810b488973c124bfb6126d3792a
